### ISSUE TITLE
Legality Checker Errors (3rd, 4th and 5th gen save file)

### ISSUE THREAD

**Issue by Real96** [kwsch/PKHeX#1011]
These pokemon are seen as not legit:

[Deoxys from FireRed](https://github.com/kwsch/PKHeX/files/880809/386.-.Deoxy.-.2F0C67684909.zip)
[Manaphy from Platinum](https://github.com/kwsch/PKHeX/files/880783/490.-.Manaphy.-.9C317942EF72.zip)
[Moltres from SoulSilver](https://github.com/kwsch/PKHeX/files/880782/146.-.Lavados.-.CCFF5838C27A.zip)
[Lugia from Emerald](https://github.com/kwsch/PKHeX/files/880829/249.-.-.4BBC7942EF72.zip)
[Latios from Emerald](https://github.com/kwsch/PKHeX/files/880830/381.-.-.FAC77942EF72.zip)
[Jirachi from Colosseum Bonus Disk --> Ruby](https://github.com/kwsch/PKHeX/files/880835/385.-.JIRACHI.-.E02C987ED636.zip)
[Arceus from entralink Black 1](https://github.com/kwsch/PKHeX/files/880855/493.-.Arceus.-.413C98221B14.zip)
[Dragonite entralink - global link event Black 1](https://github.com/kwsch/PKHeX/files/880856/149.-.Dragonite.-.71FBFFD86DF2.zip)

The 1st pokemon get all 4 moves as invalid
The 2nd pokemon get: "Invalid: Can't obtain egg for this species."
The 3rd pokemon get "Invalid: Unable to match an encounter from origin game."
The 4th and the 5th pokemon get: "Invalid: Fateful Encounter should not be checked"
The 6th pokemon get: "Invalid: Unable to match to a Mystery Gift in the database."
The 7th get: "Invalid: Hidden Ability mismatch for encounter type."
The 8th get: "Invalid Move 4: Invalid Move."

**Comment by javierhimura** [comment]
- Deoxys. Done, pending merge request. Also it have another errors after transfering it to gen 4, done too
- Manaphy. Done, pending merge request.
- Moltres. Already done in the master branch
- Lugia and Latios. I also have myselft a lugia and moltres from navel rock with fatefull encounter. Maybe that means pokemon catch in the gen 3 event islands all have fatefull encounter?
- Jirachi. Events for generation 3 are not yet implemented.
- Dragonite. There are two valid static encounter for Dream World Dragonite. That part should be refactor to retun both and then check every possible one for valid moves
- Arceus. Already done in the master branch

**Comment by Real96** [comment]
There is also the Deoxys from Emerald,which have different moves and is flagged as illegal

**Comment by PrometheusG** [comment]
+ 3rd Gen Emerald SAV file : Shedninja shows as illegal. It has evolved at lvl 20 and has the same moves as ninjask
![2017-03-30 1](https://cloud.githubusercontent.com/assets/20145301/24525267/54b1fb62-15a2-11e7-8e84-221e368cbeb7.png)

+ 3rd Gen Emerald SAV file : SEASOR (Kingdra= in-game trade)It was also showing up PID-Gender mismatch but I "fixed" it by pressing the reroll button for the PID.
![2017-03-30 2](https://cloud.githubusercontent.com/assets/20145301/24525378/af0f0780-15a2-11e7-8f08-9b14cf609b4e.png)

**Comment by javierhimura** [comment]
- Aurora Ticket Deoxys is a gen3 event. Not yet implemented
- The special case of Shedninja with Ninjask move are not yet done too, Shedninja can learn one (and only one) move from Ninjask learset after level 20, only in generation 3 and 4, and only one move per Shedninja

**Comment by Real96** [comment]
The Deoxys from FireRed i uploaded is also from Aurora Ticket, what's the difference?

**Comment by javierhimura** [comment]
No, The Deoxys you uploaded is a Birth Island Deoxys.

**Comment by PrometheusG** [comment]
**_Using PKHeX Build 2768_**

A quick update

Gen 3 Legality Checks: 

I won't talk about the events(like 10ANNIV) because I know you are working on it, so I wait. 

+  Shedninja "internal error" on all 4 moves. it is legit but it throws this error.
 ![2017-04-10](https://cloud.githubusercontent.com/assets/20145301/24864845/20843b60-1e0e-11e7-9c29-894221b8dc1f.png)

+ SEASOR, the in-game trade Kingdra from Pacifidlog Town (traded for Bagon) still has the "unable to match an encounter from origin game

Gen 4 Legality Checks:

Some pokemon that were transfered from Gen 3 games throw an invalid move error. These pokemon are: 
**Beedrill** lvl.11 (Pal Park met lvl.5 as kakuna) from leafgreen with known "invalid" moves Harden and Fury Attack, 
**Venomoth** lvl.31 (Pal Park met lvl.23 as venonat) from leafgreen with known "invalid" moves Gust and Psybeam (Supersonic and Poison Powder are ok), 
**Sunflora** lvl.45 (Pal Park met lvl.33 as sunkern) from emerald with invalid move Leafstorm
**SEASOR** from above is shown as legal but in Gen 3 is not
**Mightyena** lvl.31 (Pal Park met lvl.3, I evolved it from poochyena) from emerald with invalid moves Assurance,Odor Sleuth and Bite
**Ludicolo** lvl.54 (Pal Park met lvl.16 as lombre) from emerald with invalid move Hydro Pump
**Swellow** lvl.22 (Pal Park met lvl.7 as taillow) from emerald with invalid move Wing Attack and Quick Attack
**Dustox** lvl.13 (Pal Park met lvl.13) from emerald with invalid moves Tackle and Poison Sting
**Breeloom** lvl.23 (Pal Park met lvl.5 as shroomish) from emerald with all 4 invalid moves, Mega Drain, Mach Punch, Stun Spore and Leech Seed
**Exploud** lvl.40 (Pal Park met lvl.6 as whismur) from emerald with invalid moves Crunch, Astonish and Supersonic( Uproar is ok)
**Manectric** lvl.26 (Pal Park met lvl.12 as electrike) from sapphire with invalid moves Quick Attack and Spark(Leer and Howl are ok)
**Swalot** lvl.26 (Pal park met lvl.13 as gulpin) from sapphire with invalid move Sludge
**Wailord** lvl.40 (Pal Park met lvl.34 as wailmer) from sapphire with invalid move Amnesia
**Altaria** lvl.35 (Pal Park met lvl.16 as swablu) from emerald with invalid moves Take Down and Dragon Breath

All these pokemon have something in common except Dustox: I have leveled them up in a Gen 4 game and evolved them. What I tested to possibly "fix" the error was to change the met lvl. at pal park match the current level they have and that made them legal again altough they are already. 
Many pre-evolded pokemon from Gen 3 that were transfered in a Gen 4 game and leveled up there,evolved and learned new moves have their moves shown as invalid

**Butterfree** lvl.16 in HeartGold has a Sport Ball and was caught in National park at lvl.14. it is legit and the ball too. http://bulbapedia.bulbagarden.net/wiki/National_Park#Generation_IV

Gen 5 Legality checks:

**Onix** lvl. 44 (poke transfer met lvl.44) from HeartGold only accepts Poke ball as legal not the Dusk Ball he is in or any other ball. it shows an error: "Invalid: Can't have ball for encounter type."
Same error with 
**Nidoqueen** from HeartGold that it's in a Great Ball and 
**Parasect** caught with an Ultra Ball 

Thank you, I hope I helped

**Comment by javierhimura** [comment]
Can you upload the pkm files? It will make more easy to debug the program for the error in the legal analysis.

**Comment by PrometheusG** [comment]
Yes of course, here they are in order, inside the zip file:

[pk4 files from gen 3-pal park.zip](https://github.com/kwsch/PKHeX/files/918170/pk4.files.from.gen.3-pal.park.zip)

I would like to add that testing the PKHeX build 2796:

In the Gen 4 game(Pearl) I now see that SEASOR-kingdra the in-game trade (inside the file I sent you in the .zip) shows invalid error: "Ability does not match ability number", whereas in Gen 3 it is shown as legal correctly

In the Gen 3 game (Emerald) Beautifly and Dustox show the invalid error: "Wurmple evolution Encryption Constant mismatch", even when transfered to gen 4 game

**Comment by PrometheusG** [comment]
A new Update after testing _PKHeX Build 2825_:

Gen 3 Emerald Save:
All ok

Gen 4 Pearl and Platinum Save:
All ok

Gen 4 HeartGold Save:
**Butterfree** from HeartGold Caught in National Park with Sport Ball in the Bug Catching Contest, says : "Invalid: Can't have ball for encounter type."
**Nuzleaf** from emerald, pal park to gen 4 has invalid move Leech Seed
**Shiftry** from emerald, pal park to gen 4 has invalid move Leech Seed
The move Leech Seed is an Egg Move in Gen 3 and Gen 4

These are the pokemon files:
[pk4 files.zip](https://github.com/kwsch/PKHeX/files/922965/pk4.files.zip)


I hope I helped
Thank you for the great work you are all doing with PKHeX

**Comment by javierhimura** [comment]
The Nuzleaf and Shiftry uploaded are not originated in eggs. Nuzleaf is inside a Ultraball and Shitry inside a Repeat Ball. 
Generation 3-5 pokemon hatched from eggs must be inside Pokeball.

Because the data that indicates the pokemon was an egg is lost when is traded from generation 3 to generation 4, the programa assumes that a pokemon in non-pokeball were not from eggs and identify any egg move as an invalid move.

About the butterfree error i have just found the problem. I didnt notice that the same species can be captured both in the bug contest and the national park as normal wild encounter, different encounter types at the same location. The program is only filtering by bug contest encounter type when is transfer to generation 5

**Comment by PrometheusG** [comment]
Oh yes you are right about nuzleaf and swiftry I am a retard, I have changed their pokeball in gen 4 after pal park that's why.they were in a pokeball but I changed their ball because I was testing other things and forgot to revert them, this is my mistake.

At least I helped with the bug catching contest 

Thank you very much, keep up the good work! 🥇
If I find any error I will post there again (It will not be by my error again like nuzleaf and swiftry)

**Comment by PrometheusG** [comment]
Hi, I just have one more update (and probably the last one):

**Gen 3**(E,FR,LG): All Ok

**Gen 4**(Pearl,Platinum,HeartGold): All Ok

**Gen 5**(White):

I have 4 pokemon that shown errors, that I forgot to upload:
[pk5 files.zip](https://github.com/kwsch/PKHeX/files/942375/pk5.files.zip)

1. The first is munchlax(gorge) from in-game trade
2,3,4. Onix,Parasect and Nidoqueen are poke transfers from Heart Gold that show the "Can't have ball for encounter type" error

Thank you
