### ISSUE TITLE
Hall of fame first entered.

### ISSUE THREAD

**Issue by SirAlexiner** [kwsch/PKHeX#102]
Hey, Is it possible to find out how to change the first entered hall of fame date on the Trainer card? I think that would be a nice add the the program. also i think an option to "Skip story" would be nice, say in ORAS that would be to after you have beaten the league once. (so at the start of the delta episode) 
and in XY it's pretty much the same, after you have beaten the leauge once. Other than that your program is pretty sweet.

**Comment by suloku** [comment]
The data for hall of fame is documented at https://projectpokemon.org/wiki/Pokémon_XY_Save_File_Structure block# 0x24

About your skip story:
There's so many flags involved in story mode... It'd be much better to "build" a minimal save that goes trough the game until after elite4 (wouldn't be too hard by haking in some level 100 pokemon and lots of repels). Then edit TID/SID of the save to whatever you want. This kind of save would need to be made for both genders though. Also, due to flag differences, it should be done in the 4 games, so 8 runs in total.

By minimal I refer to:
- Never have a wild encounter (repels!) nor catch
- Never trade, never go online
- Avoid all possible trainer encounters
- Never buy anything
- Never pick up any item
- Never talk to any npc except those mandatory for story progress

This would still have a problem with starter pokemon, unless we find what flags correspond to the selected starter. That would affect the roaming pokemon in XY too.

It'd be a hard (but interesting) work to get those saves.

**Comment by SirAlexiner** [comment]
well, there are alot of flags. (I'm pretty annoyed at the shabboneau Castle flag in XY as mine is still there) also I'm not sure where in an hex editor to change the hex to change the hall of fame First entered date, so if you can tell me i would appriciate it.

**Comment by kwsch** [comment]
There's a Hall of Fame editor which allows you to change the date.
