### ISSUE TITLE
legality checker

### ISSUE THREAD

**Issue by Orionsilver** [kwsch/PKHeX#103]
# **i think PKHeX should Add legality checker for Gen 5 and Below that would be AWESOME**

![ddasdc](https://cloud.githubusercontent.com/assets/18640392/14766324/3a47cb00-0a16-11e6-9844-56e626fb4e02.jpg)

**Comment by kwsch** [comment]
If it ever happens, it'll be because someone else implemented/maintains it as it's not in line with my vision for the program (being Gen6+ focused).

The current legality checker (being Gen6 only) allows players to check Pentagon Pokémon. Since past gen Pokémon are not allowed in VGC/Rating Battles, there isn't a pressing need to have legality checking.

To check past gen files there's 3 generations worth of things to check, which includes encounter tables for 16 games (instead of 4), different learn/egg move tables, tons of odd quirks which include PID/IV relationships, breeding chains, and at least a thousand different events. All of that information would have to be stored in the program. That would probably double the size of the program, for a feature which not a lot of people would use. It'd be better as a standalone app; however, I'm not interested in doing that.
