### ISSUE TITLE
Nickname doesn't match species name (Legality Check little bug)

### ISSUE THREAD

**Issue by jisn064** [kwsch/PKHeX#1072]
I made this egg to hatch it in-game
https://puu.sh/vmWsl.png

the baby gets this error:
https://puu.sh/vmWp8.png

in-game pic of her:
http://i.imgur.com/vDFQeV6.jpg

this happens to the easter egg events aswell.

**Build #2853** _SAV Lang: ESP_

**Comment by sora10pls** [comment]
- Your in-game language: Spanish
- Your Pokemon's language in PKHeX: Japanese
- Your Pokemon's nickname: Spanish

This isn't a bug; since your Pokemon's language is set to Japanese, and the nickname checkbox is **not** ticked, it's going to search for the nickname "ヌメラ"; had the checkbox been ticked, this would not have happened. That, or you could change the Pokemon's language to Spanish to match your language in-game.

**Comment by kwsch** [comment]
Language mismatches require the egg to be traded, which has a specific met location to indicate as such.

Please do not report legality issues if they originate from tampered pkm; it's a user error more often than not.
