### ISSUE TITLE
BACD 3rd Gen Detection

### ISSUE THREAD

**Issue by kamronbatman** [kwsch/PKHeX#1103]
A few things to note on the BACD detection & anti-shiny:

Because of the highest bit on IVs, it is a little quicker in some situations to just for-loop origin seeds 0-0xFFFF.  There are no overlapping IVs.

There is always only 1 seed for restricted BACD events.  So you don't need to do a seed to PID Enumerable.

There are no unrestricted BACD events except for Mystry Mew.  I recommend instead of checking dynamically, either check based on the original 84 BACD-R seeds, or check against the 420 total origin seeds.  None of the Mystry Mew were antishiny (or shiny) either.

**AntiShiny (Pre-GCEA event ~December 2005)**
If PID is shiny then do/while PID++ until not shiny.  It would be better in the code to do something like:
`if (pid - PID < 8)` as this doesn't break the idea of for-looping the entire seed range.

**AntiShiny (GCEA and newer)**
If PID is shiny, it is skipped and a new restricted seed is used entirely.

**Comment by kamronbatman** [comment]
@kwsch, per our conversation about unown in-game being BACD (which is super-weird in-of-itself), I see why you did it this way.

Also the antishiny stands.  It doesn't look like rerolling was ever used :(

**Comment by kwsch** [comment]
Recap of private convo over IRC:

* antishiny needs to handle the overflow situation for unrestricted seeds; will manually flip the bit and check
* since we're iterating for both BACD-U and BACD-R, it's best to check all possible seeds for both at the same time, similar to method 1/2/4.
* seed checking can be done on a case by case basis if ever implemented; for now, detection is fine
