### ISSUE TITLE
Friendship of past OT gets reset when transferred over generations

### ISSUE THREAD

**Issue by TORNADO03** [kwsch/PKHeX#1108]
Here when I transfer this Dragonite from Fire Red to my Moon, its Friendship of the FR OT gets reset.

https://vgy.me/JYuNKl.png

**Comment by kwsch** [comment]
Pretty sure this is intended; matches how the game does transfers. The friendship is reset as it is essentially traded to a new trainer.

**Comment by TORNADO03** [comment]
I have done previous transfers in which the friendship was retained. I haven't actually done any transfer through bank so I can't comment on that. Just thought you should check that out.

**Comment by javierhimura** [comment]
This is not a problem about transfer throught bank, after all you can't transfer throught  from Fire Red to Moon.

What PKHex do to make the trade is emulate every trade needed to move in-game the pokemon from Fire-Read to Moon, that means internally the pokemon is emulated for example the trade between FireRed and Diamond, then Diamond and Black, Black and X and finally X and Moon. 

The friendship is lost in the first trade because OT friendship does not exits in FireRed nor in Diamond, when you trade a pokemon between GBA and DS games the friendship is reset, even if the trade between X to Moon with the Bank retain the friendship it does not matter in this example because is lost many generations before that transfer
