### ISSUE TITLE
RBY Golbat with Screech marked as illegal

### ISSUE THREAD

**Issue by BeyondTheHorizon** [kwsch/PKHeX#1121]
Golbat can learn Screech at Level 1 in RBY, but PKHeX marks this as illegal. I don't know how Golbat can learn the move with no Move Reminder in Generation I, but if it can learn it, it should at least not be marked as illegal.
![pkhex error](https://cloud.githubusercontent.com/assets/20503303/25999565/9043e572-371d-11e7-82a9-e7605cfa1b54.png)

**Comment by javierhimura** [comment]
You have answer yourself why Golbat with Screech is illegal: there is no Move Reminder in Generation 1.
The move is in Golbat learnset but it is impossible to learn. Any wild Golbat captured in RBY will have forgotten the move Screech at the moment is its captured

The only way to obtain a Golbat with Screech is to catch a wild Golbat (not Zubat) with level 20 or lower, because if it have level 21 it will learn Confuse Ray and forget Screech, but there is any wild Golbat with level 20, and that means Golbat with Screech it is impossible: it is illegal.

**Comment by BeyondTheHorizon** [comment]
@javierhimura I'm really sorry for wasting your time with my stupidity. I saw the Smogon set for Golbat in RBY had Screech on their site, so I got confused.

**Comment by greenDarkness** [comment]
@javierhimura Even though this is invalid, it still provided some great insight. Thank you for taking the time to post that explanation.
