### ISSUE TITLE
legality in the batch editor

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1182]
Hi. first I wanted to say that the newest version of mono pkhex is actually the full version. By the time your looking at this you may have fixed it but I just wanted to let you know. I had a question on the batch editor. what are the commands you can put in for the legality option. Also i'm pretty sure I know what it does but I just want to make sure that it changes whatever pokemon are not legal with suggested options. Thanks and sorry i'm putting this here but obviously going to the creator is the best option and I couldn't find it online. I still think you should try to put together a text file or something of the sort with all of the options in the batch editor and the corresponding commands you can put it. Thanks

**Comment by kwsch** [comment]
Reuploaded mono version with latest commits since last release.

Keyword for editor is "Legal"
https://github.com/kwsch/PKHeX/blob/2fb3cd5207fde2988c02b77ca2eb2e3d1e223698/PKHeX.WinForms/Subforms/PKM%20Editors/BatchEditor.cs#L59

`=Legal=True`

Moves, RelearnMoves, and Met_Location suggestions can be applied:
https://github.com/kwsch/PKHeX/blob/2fb3cd5207fde2988c02b77ca2eb2e3d1e223698/PKHeX.WinForms/Subforms/PKM%20Editors/BatchEditor.cs#L477-L509

**Comment by kwsch** [comment]
Revised FAQ to add a description on "$suggest" parameters (at the bottom).
https://projectpokemon.org/forums/forums/topic/38168-frequently-asked-questions/
