### ISSUE TITLE
Moon legality bug

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#1223]
I have a Magneton that shows it was captured (not hatched) on route 1 in Pkmn Moon. It has a legality error i believe to be incorrect. Magnemite is available in that location and at that met level.

![image](https://user-images.githubusercontent.com/18354599/27089955-695761b4-5036-11e7-9121-f437d913d6ac.png)

**Comment by kwsch** [comment]
needs more info (pkm details)

could be insufficient current level (unable to devolve to magnemite)

**Comment by Odaxis** [comment]
Hope this is enough info, git wont let me upload the pk7 file in native or rar format

Invalid: Unable to match an encounter from origin game.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Move 4: Learned by Level-up.
Valid Relearn Move 1: Valid.
Valid Relearn Move 2: Valid.
Valid Relearn Move 3: Valid.
Valid Relearn Move 4: Valid.

Valid: Current level is not below met level.
Valid: Ability matches ability number.
Valid: Skipped History check due to other check being invalid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Invalid
PID Type: None

![image](https://user-images.githubusercontent.com/18354599/27102005-4b1e10c6-505e-11e7-9833-66061d0d38c1.png)

![image](https://user-images.githubusercontent.com/18354599/27102016-542c579a-505e-11e7-8bd3-22f45dc53b55.png)

![image](https://user-images.githubusercontent.com/18354599/27102022-5c32d752-505e-11e7-87f7-31ef8b5bbdcd.png)

![image](https://user-images.githubusercontent.com/18354599/27102035-6ccf1daa-505e-11e7-8450-9fe9f46886d5.png)

![image](https://user-images.githubusercontent.com/18354599/27102063-7d4cc56a-505e-11e7-95de-e568ca9f65e4.png)

**Comment by Odaxis** [comment]
added info. The Magnemite (according to its owner) was caught in game and not edited with PKHeX prior to discovering the error.

**Comment by sora10pls** [comment]
Route 1 is illegal if the Pokemon wasn't hatched from an Egg, because the actual Met Location should be Route 1 (Hau’oli Outskirts). Trainer's School is in Hau'oli Outskirts (west side of player's home), rather than Route 1 (north side of player's home). PKHeX is **correctly flagging your Magneton.**

Legit Magnemite caught on Route 1:
![image](https://user-images.githubusercontent.com/17801814/27105596-2cad741a-505e-11e7-82f6-17675e61cbe8.png)

Refer to Bulbapedia:
![image](https://user-images.githubusercontent.com/17801814/27105453-a09016cc-505d-11e7-860f-85dcbbf133a1.png)

**Comment by Odaxis** [comment]
Just double checked with the owner, it's possible something might have altered the spawn locations in the game. Close this. Thanks sora10pls and sorry Kap
