### ISSUE TITLE
legality issue...

### ISSUE THREAD

**Issue by lomejor18** [kwsch/PKHeX#1234]
hello... why do i get red flag? i believe everything is fine... thanks

![exeggutor](https://user-images.githubusercontent.com/24194552/27243141-87177444-52ae-11e7-832b-b40a97da6e07.png)
![florges](https://user-images.githubusercontent.com/24194552/27243142-872c8294-52ae-11e7-9ed9-1f9da89118c0.png)

[pk7.zip](https://github.com/kwsch/PKHeX/files/1081839/pk7.zip)

**Comment by sora10pls** [comment]
Exeggutor: PKHeX expects at least Level 2, despite Leaf Stone being the evolution method making Level 1 possible.

Florges: Instead of the default Relearn Moves for a hatched Flabebe (Tackle, Vine Whip), it's expecting the following for whatever reason:
![image](https://user-images.githubusercontent.com/17801814/27248519-a3406300-52d2-11e7-90de-f74d0ed713e6.png)
