### ISSUE TITLE
Gen 1 skipped level-up moves

### ISSUE THREAD

**Issue by White-Canary** [kwsch/PKHeX#1258]
Pokemon with empty move slots in gen 1 are incorrectly flagged as illegal if they're missing any level-up moves learned below their current level. Only the moves known at the encounter level and the current level are legally required, as gaining multiple levels at once skips any moves learned in between the starting level and the final one in gen 1. EDIT: Seems to only affect gen 1, they appear legal if traded to gen 2 or transferred to gen 7.

![capture](https://user-images.githubusercontent.com/23516075/27373221-157b3a14-562d-11e7-8f52-f1fe073e4988.PNG)

**Comment by javierhimura** [comment]
In gen 2 and 7 the pokemon is illegal because those games move deleter.

I suppose level up multiple times in one combat is only possible in the first levels depending on the best possible experience from a combat.

Being this a minor check for now would be enought to only make mandatory the initial moves for the encounter and other moves that the pkm currently have
