### ISSUE TITLE
[Question] Should Legality String V23 only be valid for Gen 7?

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1284]
V23 = "All EVs are zero, but leveled above Met Level."

If a Pokemon is put into the Day Care, right from Lv. 1, it will gain EXP for every step the player takes and not gain any EVs from it. In Gen 7, however, no Pokemon gain any EXP from the Nursery, so this is obviously fishy.

**Comment by 1412kaito** [comment]
Doesn't PokePelago Isle Evelup has an option to specifically for Exp? I think even in Gen VII it is still possible to level-up your Pokemon w/o ever getting EVs

**Comment by sora10pls** [comment]
I can't answer that since I haven't really bothered with Poke Pelago.

**Comment by kwsch** [comment]
Fishy does not imply illegal.
Fishy checks just flag legal properties that may either be due to bad hacking or intentional in-game behavior.

Examples:

All IVs = 0
* possible with RNG (for the lulz)
* hacked PKM, forgot to define IVs

Leveled above met level, no EVs:
* past gen daycare
* Rare candy used to evolve for dex entries
* EVs wiped with berries
* hacked to a certain level, forgot to define EVs
