### ISSUE TITLE
Gen 4 Legality

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#1318]
Feebas is showing up illegal in DPPt, its catch method is showing up invalid, and also if its higher than lv 20, game origin shows up invalid.

https://www.serebii.net/pokearth/sinnoh/mt.coronet.shtml

https://bulbapedia.bulbagarden.net/wiki/Mt._Coronet#Finding_Feebas
![feebas 1](https://user-images.githubusercontent.com/12572974/28049675-cfc57436-65c6-11e7-90d8-e1ea029e6b08.PNG)
(shows the level range to be 10-20) while several websites have different level's posted.

https://bulbapedia.bulbagarden.net/wiki/Appendix:Diamond_and_Pearl_walkthrough/Section_16
![feebas 2](https://user-images.githubusercontent.com/12572974/28049666-be5a89a2-65c6-11e7-9480-abae2d85d988.PNG)

**Comment by kwsch** [comment]
Probably because it's not an encounter slot in the tables

**Comment by Ninjistix** [comment]
![capture](https://user-images.githubusercontent.com/12572974/28252883-5a6ee82c-6a6a-11e7-8de1-d24006edf258.PNG)

**Comment by Ninjistix** [comment]
![capture](https://user-images.githubusercontent.com/12572974/28252921-ad9a0112-6a6a-11e7-8a09-b366d429f1b8.PNG)
this and the other version exclusive fossils should not be legal if obtained in wrong version

**Comment by kwsch** [comment]
Root Fossil is a held item in gen4, and thus can be traded to the opposite game for revival(?)

**Comment by Ninjistix** [comment]
okay didnt check that, but the feebas is still being marked illegal

**Comment by kwsch** [comment]
notes for later:

[target area for edits](https://github.com/kwsch/PKHeX/blob/4207df8d74706b6e6911161d38542ea17e8fcb0f/PKHeX.Core/Legality/Tables4.cs#L804-L806)
[disassembly of slot determination by](http://www.smogon.com/forums/threads/past-gen-rng-research.61090/page-36#post-4079097) @TuxSH
probably the feebas slot inherits the level range of the slot it overrides; will have to have this confirmed/denied so that the level range can be changed.
