### ISSUE TITLE
[Bug] FR/LG Gift Togepi PID

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1322]
An untouched Gift Egg Togepi from FR/LG is flagged as illegal by PKHeX. [Here's the PKM file.](https://github.com/kwsch/PKHeX/files/1141019/togepi.zip)

As always, TID and SID were zeroed out for potential cloning.

**Comment by sora10pls** [comment]
Found the problem, not sure how I'd go about fixing it though:

Because the Pokemon is a Gift **Egg**, PKHeX tries to search for the PID Method "None", despite being obtained via Method 1 in-game. I figured this out by attempting to re-roll the PID, to find that the PID Method was changed to "None" and was deemed legal.

**Comment by javierhimura** [comment]
The bug happens only in generation 4-7, right?
I think the encounter finder is skipping gen 3 gift eggs if the pokemon has been pal parked because back before PID analysis was implemented there were no way to difference a gift egg and a day care egg.

That is why Togepi is legal with the PID None, None is the method valid for player day care eggs

**Comment by sora10pls** [comment]
The bug happens in the FR/LG save file, haven't tested transferring to Gen 4+.
