### ISSUE TITLE
[Feature Request] Add Gen 3 Roaming IV Bug to Legality Checks

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1323]
Would work similarly to the IV3 check.

https://bulbapedia.bulbagarden.net/wiki/List_of_glitches_in_Generation_III#Roaming_Pok.C3.A9mon_IV_bug

**Comment by greenDarkness** [comment]
"In the Generation III games, the data for a Pokémon's IVs are stored in a 32-bit integer. However, when a roaming Pokémon is caught, only the last 8 bits are transferred. While the HP IV is unaffected, the Pokémon can only have a maximum Attack IV of 7. The other IVs will always be 0.
Due to this, their Hidden Power type will always be Fighting with a power of 30 or 31."
How did this one slip through. That's an awful bug.

**Comment by sora10pls** [comment]
I actually didn't know it existed until today! In their defence, they did fix it in Emerald. :P

**Comment by javierhimura** [comment]
Is already implemented ,  PIDType.Method_1_Roamer, this method is the only valid for generation 3 non-emerald roaming pokemon
Emerald instead use Method_1
