### ISSUE TITLE
PKHeX changing latest trainer to PkHeX 

### ISSUE THREAD

**Issue by RosalineAng** [kwsch/PKHeX#1324]
The current version of PKHeX appears to be changing the latest trainer automatically to PKHeX as the latest trainer. When trying to change the latest trainer to the right trainer PKHeX automatically changes it back to PKHex. The error persists on saved pokemon files too.

**Comment by kwsch** [comment]
This is a feature, not an error.

A pkm (in gen6+ format) has to have a current handler (based off the save file it is currently on). Since the OT details do not match the currently loaded save file, the latest handler data is automatically updated and set to match the currently loaded save file.

The default save file has OT=PKHeX.
This auto-fixing behavior can be disabled by unchecking the "Modify PKM Info" option.
