### ISSUE TITLE
[FR] Enable in-game clock setting for R/S/(E)

### ISSUE THREAD

**Issue by rboninsegna** [kwsch/PKHeX#1328]
After a couple of hours (which wouldn't have been possible without the disassembly), I have managed to manually unlock the one-off clock reset feature - Left+Select+B at the title screen - which is rather convenient for fixing the berry glitch on real hardware (both the classic 2nd-year-bug and the post-power-failure kind), assuming of course access to a save backup tool:

* In [block 2](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Saves/SAV3.cs#L25) (which holds flags and variables) of the save, go to address 3AC from the start of the block, and set [the bit worth 4](https://github.com/pret/pokeruby/blob/1c49064780f87a874c8f516ef20be61b17bafef0/include/flags.h#L59) to enable flag 0x862;
* Set [variable 402C](https://github.com/pret/pokeruby/blob/792a2c6976a3adcf0e6a21c570189e6bcf0cdbcf/include/vars.h#L25), residing at addresses 0x418-419 (little endian; relative again to start of block 2) to 0x920
* There's no step 3, apart from the already-working-fine fixing checksums on save :)

Congratulations again on the solidity of the editor!

**Comment by kwsch** [comment]
0x862 bits backwards from 0x3AC is 0x2A0; I'll assume 0x2A0 is the start for the EventFlags chunk

[FRLG](https://www.pokecommunity.com/showthread.php?t=349936):
>The next sub block is the story records sub block, containing 0x900 flags, 128 variables and 64 encrypted counters. Encrypted counters are used by the game to keep metrics, such as the ones shared via record mixing.


const 402C is at 0x418, so the base offset is 0x3C0.

0x3C0-0x2A0 = 0x120, so 0x900 event flags. Since RS/E is the same as FRLG... we'll assume the same amount of Event Variables:

## Block 2:
0x2A0: Event Flags (0x120 bytes)
0x3C0: Event Variables (0x100 bytes)
0x4C0: Player Stats (???) -- I looked at Pokemon Reader 2 but didn't care enough to continue

Sanity checking for RS:
[this site](http://furlocks-forest.net/wiki/?page=Ruby/Sapphire_Save_Data_Map) lists mirage island values at 0x408 in Block 2; 0x48 bytes into the event vars (0x24), [which matches the event var map](https://github.com/pret/pokeruby/blob/792a2c6976a3adcf0e6a21c570189e6bcf0cdbcf/include/vars.h#L19-L20).

For RS:
* 0x2A0
* 0x3C0

For E: (shifted by 0x50)
* 0x2F0
* 0x410

For FRLG:
* 0x000
* 0x120

Not sure on FR/LG or E offsets, but assuming the counts are constant between games it should be pretty easy to implement.

**Comment by rboninsegna** [comment]
@kwsch well, since I was somewhat bored, I've made a list of most flags :) https://gist.github.com/rboninsegna/a4a63c2b66c42e371a94f860eae55361

**Comment by Xlaits** [comment]
I know this is closed, but is it possible to write this as a gameshark code for use on actual hardware? Just replaced a battery in my original Ruby cart, and I'm kinda confused as to how to set it correctly.
