### ISSUE TITLE
[FeatureRequest] Gen 3/4/Colo/XD PID generation as native code

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1333]
Using code taken from RNG Reporter i was able to actually get PID generation working perfectly for a given set of IV's Here is a class in which i implemented the code. You just need to call the function from any class to get the proper PID. Hopefully this or an implementation of this is included in the next commit, I dont mind making a PR either if thats more convenient 

[PID Generation for Gen 3/4 and Colosseum/XD](https://github.com/architdate/PKHeX-Auto-Legality-Mod/blob/master/PKHeX.WinForms/Misc/IVtoPIDGenerator.cs)

**Comment by kwsch** [comment]
RNG Reporter is licensed under GPL v2; PKHeX is licensed under GPL v3.
[These Licenses are not compatible](https://opensource.stackexchange.com/questions/1777/why-is-gplv2-incompatible-with-gplv3).

A PID Generator is on the far-future todo list; since other tools already have this feature, it is not something with high priority. Gen2 VC and USUM in the next 4 months, and fixing/fleshing out more editing features are currently more important.

**Comment by architdate** [comment]
Fair Enough. Just suggested since it is a bit of an issue legalizing pokemon from these generations. 👍

**Comment by kwsch** [comment]
It'll be more of an issue when RNG related [Frames](https://github.com/kwsch/PKHeX/blob/3f38b123a36c830a48bcd471a57aa72b83318a3d/PKHeX.Core/Legality/RNG/Frame/FrameFinder.cs) and [Shadow Lock](https://github.com/kwsch/PKHeX/blob/master/PKHeX.Core/Legality/RNG/Locks/LockFinder.cs) checks are added ;)
