### ISSUE TITLE
Legality issues in 4th generation save

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#1355]
Shaymin, who learned air slash from a fourth-generation save file, is not legit.
Here is the pkm file.
This Shaymin is valid in 6th and 7th generation.
[492 - 쉐이미 - EA512C4A9A2B.zip](https://github.com/kwsch/PKHeX/files/1165323/492.-.-.EA512C4A9A2B.zip)

**Comment by architdate** [comment]
Ok so I looked through the code and realised that the `LevelUp` functions do not have a form argument yet. Because of this pokemon who have different forms as well as different levelup moves per form will be affected. This is not just going to be for Air Slash in gen 4, but also for quick attack and leaf storm which can only be learned in gen 4 when leveling up as Shaymin Sky, However since shaymin deoxys and giratina are the only 3 major cases, I will just hardcode in the additional moves that will be obtained with Shaymin Sky leveling up. 

The reason for this hardcoded fix is because of the mechanic in which the Learnset[] class is working right now (with no form attribute)

```Learnset[] LevelUpHGSS = Learnset6.GetArray(Data.UnpackMini(Util.GetBinaryResource("lvlmove_hgss.pkl"), "hs"))```

Will reference this issue in my pullrequest after fixing it
