### ISSUE TITLE
Gen 5 legality issues

### ISSUE THREAD

**Issue by host1126** [kwsch/PKHeX#1361]
Keldeo who learned secret sword in bw is not legitimate.
The error message is Invalid move : keldeo move/form mismatch.
but I think keldeo can learn secret sword regardless of form change in bw.

**Comment by sora10pls** [comment]
Keldeo's Resolute Forme did not exist in B/W but Secret Sword did; the Move/Forme mismatch only applies to B2/W2 onward.

**Comment by architdate** [comment]
The issue still pertains in Pokemon Black version (Shows a form mismatch for secret sword for gen 5 based games. Although it should be legal) 
![image](https://user-images.githubusercontent.com/17220860/28603270-b7b52bbc-71f5-11e7-8b31-11932fb661c8.png) 

Will submit a PR to fix this soon however

**Comment by architdate** [comment]
Wont the latest commit changes legalize Keldeo original form in B2W2 as well? Since the `pkm.format` is still 5. However in B2W2 the mon should be illegal itself. Shouldnt this be `pkm.format == 5 && !pkm.B2W2` ? for the proper fix? @kwsch

**Comment by kwsch** [comment]
trade it to BW, tutor it, then trade it back

**Comment by architdate** [comment]
I mean, if the save file is a B2W2 save file, keldeo cannot exist in the original form without secret sword right? The conditional allows this?

**Comment by kwsch** [comment]
https://pokemondb.net/pokebase/96401/turn-keldeo-resolution-already-have-secret-sword-traded-from

**Comment by architdate** [comment]
I believe that when keldeo is transferred back to B2W2 it retains back its resolute form (It wouldnt make sense for it to remain in original form since all that resolute form does is activate because of secretsword, there are no BST changes or any advantage of the form itself except for aesthetics. It just acts as an identifier for that move.) So I would think that on a trade back it should go back to being resolute. I'll confirm this and let you know soon however.
