### ISSUE TITLE
Add pokemon link injection

### ISSUE THREAD

**Issue by poutros** [kwsch/PKHeX#137]
The cases for using it legitimately are few but I think it would make the program more complete.

https://projectpokemon.org/wiki/6th_Generation_Pokemon_Link_Map

**Comment by suloku** [comment]
https://github.com/suloku/G6_pl_tool

I added data viewing a month ago, editing still has a couple bugs I haven't have time to sort out. Also, I mimicked pkhex's style for the class for (hopefully) easy integration

I wanted to add to pkhex and makey a pull request but:
1- pkhex is currently under heavy changes with all the past-gen support
2- I have not been able to compile pkhex since the switch to c# 5.0. Any ide recommended? I have only ever used sharpdevelop and have no clue on what I need to compile pkhex.

But just an import/export feature of the bin files would be nice to have in pkhex.
