### ISSUE TITLE
Sun and Moon Munchlax Snorlax Legality Issue

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1380]
I believe PKHeX is saying that Snorlax cannot have egg moves from Munchlax?

 Thank you for all your hard work.
PK7 in question:
http://www.mediafire.com/file/sfmfwksmy1dxbmb/143_-_Snorlax_-_8BB34D1C1A21.pk7
``` 
Invalid Relearn Move 3: Munchlax Inherited Move. Incompatible with Snorlax inherited moves.
===

Valid Move 1: Learned by TM/HM.
Valid Move 2: Learned by Level-up.
Valid Move 3: Relearnable Move.
Valid Move 4: Relearnable Move.
Valid Relearn Move 1: Base Egg move.
Valid Relearn Move 2: Relearnable Move.
Valid Relearn Move 4: Empty Move.

Fishy: 2 EVs remaining.
Valid: Able to hatch an Egg at Met Location.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: All ribbons accounted for.
Valid: Ability matches ability number.
Valid: Correct ball for encounter type.
Valid: History block is valid.
Valid: Geolocation: Country is in 3DS region.
===

Encounter Type: Egg (Snorlax)
PID Type: None
```

**Comment by javierhimura** [comment]
No, PKHex is saying an Snorlax hatched as Snorlax cannot have egg moves from Munchlax.

PKHex first check if the pokemon was a Munchlax egg, if the Munchlax egg encounter is not legal then it check for Snorlax egg encounter.

I cannot check the pk7 file but the first problem i see is your pokemon have an empty move in relearn moves but that is not possible for Munchlax eggs because Munchlax have 4 base moves at level 1, every munclax should hatch with 4 moves, egg mover or just level 1 moves.

**Comment by greenDarkness** [comment]
You are correct. The lack of egg moves was the problem. Thank you so much for your time.
