### ISSUE TITLE
How to resolve Encounter PID Mismatch?

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#1389]
A problem that I'm having in gen 3 and gen 4 games is that a lot of the Pokemon I've genned are throwing the error that it has a bad PID mismatch and yet, all I would've changed was maxing out the IVs and giving a good nature, I try to reroll the PID and yet it still throws the error. It seems to only be a problem within this program because its not tripping any hack checks, i.e. copying to battle revolution, but its so frustrating to have so many of my Pokemon flagged for this one issue. Is there any way for me to fix this or make the program exempt this issue when looking at my Pokemon?

**Comment by javierhimura** [comment]
Working as intended, when you have changed the IVs and the nature of your pokemon you are making your pokemon illegal, PkHex does not have any problem, the program is flaggin your pokemon illegal because they ARE ILLEGAL. A problem would be if PKHex flag legal an illegal pokemon or flag illegal a legal pokemon. 

Generation 3 and 4 has a very limited random generation method and that means not every combination of PID and IVs are possible to be obtained in-game, if you want to change the PID or IVs you must obtain a legal value with RNG Reporter
