### ISSUE TITLE
pokemon gen 5 poketransfer legality issues

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1390]
Hi I just transferred all of my legit pokemon I caught in gen 4 over to gen 5 using pkhex. All of the pokemon are legit and were caught in gen 4. when I transferred them I got a legality issue for a couple of them. They all had the same legality issue which was (cant have ball for encounter type. encounter type does not match encounter.) I also dont understand this because in the gen 4 games I caught them legit and they dont have a legality issue in those games. Only when transferring them to gen 5. This only occurred with a few pokemon so its not like its all of them. Thanks

**Comment by kwsch** [comment]
Please upload examples.

**Comment by xXAquaNightXx** [comment]
I think this is happening because pkhex is identifying the PID as Wild Encounter PID maybe old PID generation methods used this for hatched pokemon as well? Re-rolling the PID should solve this. Other than that you would have to set ball to safari ball and uncheck met as egg.

Generating a wild encounter PID:

![test](https://user-images.githubusercontent.com/24309423/29192556-d2d9670e-7def-11e7-8941-4f6dbc90d793.png)

Putting this value in pkhex with ball type as pokeball and pokemon hatched from an egg:

![test2](https://user-images.githubusercontent.com/24309423/29192576-e5df07be-7def-11e7-95bd-c013c4e1a50c.png)

Rerolling PID:

![test3](https://user-images.githubusercontent.com/24309423/29192617-07c2c834-7df0-11e7-9a47-fecfc0e6de4b.png)

OR

Changing ball to safari ball and unckecking met as egg

![test4](https://user-images.githubusercontent.com/24309423/29192636-1b91e228-7df0-11e7-8d8d-ea732cf6613e.png)

**Comment by NinFanBoyFTW** [comment]
[Kadabra.zip](https://github.com/kwsch/PKHeX/files/1216443/Kadabra.zip)
Ok well here is my kadabra. I included the pk4 and pk5.

**Comment by xXAquaNightXx** [comment]
Its not identifying the pokemon as a wild pokemon , changing it to pokeball  fixes this but checking met as egg also fixes it but it should be illegal because eggs cant be in quickballs. 

![3](https://user-images.githubusercontent.com/24309423/29193577-f12d27dc-7df3-11e7-98f8-4ab1d921f070.png)

![2](https://user-images.githubusercontent.com/24309423/29193574-ee1c9d3e-7df3-11e7-8973-4ee76f6f525a.png)
![1](https://user-images.githubusercontent.com/24309423/29193572-eabb1044-7df3-11e7-9d42-8cee616264ac.png)
