### ISSUE TITLE
gen 1 legality errors

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1417]
Hey I was able to find a bunch more legality erros in my pokemon yellow save. Im pretty sure that this is a similar issue to the last error, but instead of it being gen 2 learnsets as the issue is because pokemon yellow apparently had different learnsets than red and blue for some reason. ill just include the pk files.
[pk files.zip](https://github.com/kwsch/PKHeX/files/1250803/pk.files.zip)

**Comment by xXAquaNightXx** [comment]
The learnsets aren't different the LEVEL the moves are learnt are different. Your Nidorina for example would be illegal in Red and Blue and legal in Yellow. Its at level 23 and Double Kick is learned at level 50 in Red and Blue (it would be illegal in these games) and learned at level 12 in Yellow (it would be legal here).

**Comment by NinFanBoyFTW** [comment]
Thats what I meant by the learnset are different. Also it doesnt matter if they are illegal in red and blue. If I trade these pokemon from pokemon yellow to red and blue without using cheats of any kind then clearly they are legal. The same way if I transfer a pokemon up from gen 3 to 6 it wouldnt be illegal. The real problem with these pokemon is that there is no met data for these games and pkhex cannot distinguish between red and blue caught pokemon, and yellow pokemon. I think this also may apply for certain pokemon in gold/silver and crystal too. Either way, if I trade pokemon from one game to another without using cheats then they are still legal pokemon. Im not sure how you would get around this problem either. Maybe you would just have to just make the legality on these 2 gens much more lax and just let these pokemon have whatever movesets may be available across gen 1. I think gen 2 has more data available so I dont think that is a problem. One other thing. I just checked my yellow save and put these pokemon back into them and they are still showing up as illegal, so even if it was like you said where in yellow they are legal and in red they arent, they are still showing up as illegal in yellow for me.

**Comment by javierhimura** [comment]
PKHex do not flag a pokemon as illegal just because it have moves from red/blue and yellow at the same time. Trade between games to learn moves is included in the legal analysis.

About the lack of met data in gen1 in those cases PKHex do not have a lack analysis, if there is no way to tell what encounter the pokemon was caught the programa just check with every possible encounter, but if no encounter is legal with the current data the program show the errors from the last encounter checked.

Also the encounter changes what moves are possible for the pokemon in gen 1 and the future VC of gen 2 because there is no move reminder in those games. If a pokemon was from an encounter at level 30 only the last 4 moves for its learnse up until level 30 are legal, and only from one possible game red/blue or yellow.

Also when the program checks for encounters from red/blue and yellow it look throught all possible combinations.

An example would be Eevee, Eevee have more than 4 moves in its learnset at level 25, the minimun encounter in gen 1, only the last four moves of the learnset are legal, also those 4 moves are not the same between red/blue and yellow, making some moves combination illegal.
