### ISSUE TITLE
Add I and II generation save editing/pokemon importing

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#152]
Then we will have the ULTIMATE pokemon editor tool!

**Comment by kwsch** [comment]
Not happening in the next couple of months; the dust still needs to settle from the recent additions.

**Comment by ajtudela** [comment]
So bad :/ Yes, i saw Rhydon but it doesn't handle second generation.

P.S.: How about implementing wc6 full editor?

**Comment by kwsch** [comment]
https://projectpokemon.org/forums/showthread.php?42746
A program already exists that handles editing.

Not implementing in PKHeX as there's no point editing gift files as you can edit the resulting gift in the main window.

**Comment by ajtudela** [comment]
Thanks!

**Comment by JHorbach** [comment]
So, we can dream with that enhancement? Gen I and 2 Import to 3, but in a better way that Metropolis one does, like randomizing nature of the Pokémon...

**Comment by ajtudela** [comment]
I look at your code and I would like to star a new branch with this enhancenment.
What are the files I should start to modifyng to implement first generation pkm?

**Comment by JHorbach** [comment]
I think this will be very good for the future of the program , knowing that the first generation will again be important with the arrival of the Sun and the Moon.

**Comment by kwsch** [comment]
Implementing a converter would take less than an hour of work, as Rhydon already has the pk1 class. 

The only thing that is unknown is the final transfer process, which isn't worth speculating over until it is actually released.

**Comment by ajtudela** [comment]
I'll take a look at rhydon class.

P.S.: It would be possible that when you save a pkm change the extension as their generation?

**Comment by poutros** [comment]
@JHorbach You do know that generates ilegal pokemon, right?

**Comment by JHorbach** [comment]
Sure, @poutros.

**Comment by JHorbach** [comment]
But maybe The gen I and II can be made with a drag and drop system in PKHex and when gen VI launches we can study The new converter code and implemet it in PKHex to make legal pkm.

**Comment by poutros** [comment]
*VII

**Comment by JHorbach** [comment]
@poutros Sorry my bad. VII.

**Comment by ajtudela** [comment]
Well, I've been testing reading pk1 hex and I have some doubts.

This one is read/save using PKXDelta: [Bulbasur-PKXDelta](https://dl.dropboxusercontent.com/u/11602465/bulbasur.jpg)

And this one is read/save using Rhydon: [Bulbasur-Rhydon](https://dl.dropboxusercontent.com/u/11602465/bulbasur-rhydon.jpg)

The values marks are: 99 00 1f 0a 00 16 03, which means:
99 - Bulbasur  
00 1f -> Current HP
0a  -> Level 10 
00 -> Status not affected
16 03  -> Types grass and Poison

My question is: why that values doesn't starts in 00? 

PKXDelta starts in 17 and Rhydon starts in 03

**Comment by SciresM** [comment]
@ajtudela It's because PKXDelta uses a file format it made up for PK1 files. It concatenates nickname, OT name, and pk1 raw data.

Rhydon attempts to standardize the PK1 format by using a pokemon_list of size 1. Since pokemon_list is a game-defined struct, I personally feel this is the better solution.

Also, don't bother adding Gen I support to PKHeX.  We're not going to add importing of PK1s until the conversion routine gets documented following Sun/Moon's release. PKHeX may eventually see Gen I save editing support well after sun/moon support, but it's very unlikely to get added in the near future.

**Comment by ajtudela** [comment]
@SciresM  Okok What about Gen 2?

**Comment by BeyondTheHorizon** [comment]
Gen I and II support would indeed be most welcome, and it's disappointing to know that it won't be incorporated into PKHeX for a while.

I'm currently waiting for Rhydon to include Gen II support, and I've had to struggle against my own impatience for a while. I'm ashamed of myself for feeling so worked up over something like a computer application not being updated. It's silly, really.

But if it's ultimately not going to happen, I'll try not to go crazy as I wait for PKHeX to include Gen I and II support.

**Comment by SciresM** [comment]
Rhydon will almost certainly never support Gen II. 

If I decide to work on Gen II support, it will be in PKHeX, following adding Gen I support to PKHeX...but that will likely not be for a while.

**Comment by SciresM** [comment]
...I guess this is happening: https://github.com/kwsch/PKHeX/tree/rhydon-merge

**Comment by kwsch** [comment]
Gen I support has been merged #211

I expect there's a few things to iron out before any new game support will be added.

If a S/M demo is announced tomorrow on Nintendo Direct (all signs point to yes), then the target implementation timeline for core support will be as follows:

```
MAY: Gen V
JUN: Gen IV
JUL: GEN III
AUG: Gen I
SEP: Gen II
OCT: S/M Demo save editing, ROM Reverse Engineering (not PKHeX)
NOV: S/M Retail save editing
```

**Comment by poutros** [comment]
@kwsch Would it be useful to open 6 issues for every gen listing the missing features (not the bugs, only editing features and only the features that concern editing the save and not stuff like individual wondercard files)? It's easy to forget what features are missing if we don't play the games that often (especially considering the amount of features that exist for each gen). It could also help newcommers that are experienced in coding to help add said features.

The issue structure would be as such:

Title: Gen 1 - Missing Editing Features

Description:
Blue/Red only features:
- [x] Feature 1 (only put a check if the feature was added after the issue was made or delete the item from the list)
- [ ] Feature 2

Yellow:
- [ ] Feature X
- [ ] Feature Y

And order each feature according to its priority.

**Comment by evandixon** [comment]
Github issues are more for individual features or sets of related features, that can be closed when completed, instead of comprehensive lists of all features that can be added.  Splitting issues like this allows assigning developers to individual features/feature sets and allows assigning priorities through Milestones.

If we did want a comprehensive list of all possible features that aren't implemented, I'd recommend using the [wiki](https://github.com/kwsch/PKHeX/wiki).

**Comment by poutros** [comment]
@evandixon Ok then.
