### ISSUE TITLE
Pokemon Gen III Event Flag Research

### ISSUE THREAD

**Issue by bert-w** [kwsch/PKHeX#1532]
I'm using the "Research" tab right now for the Event Flags, however I dont know what the syntax does. I want to fill in the missing pieces, and find out what exactly it does.

my output for 1 simple test case is:
```
48: 33->15
60: 4->1
237: 289->292
```
How do I read this?

In addition, there are constants with names like `VAR_0x4003` and with `VAR_MIRAGE_RND_H`. Shouldnt this last variable name also have the original block name, for reference? I would suggest a new column (very first on the left) which keeps the hex-values, and the second column keeping the researched alias.

EDIT: Basically this file https://github.com/kwsch/PKHeX/blob/43d1c7740fb09b46bed0216c21b8b5f717038756/PKHeX.Core/Resources/text/script/const_e_en.txt , such that both values are visible

**Comment by bert-w** [comment]
Also, anyone got a clue why these blocks dont match with this source:

http://furlocks-forest.net/wiki/?page=Ruby%2FSapphire_Save_Data_Map

ctrl+f for "mirage island" and you get to a block that was noted as `0x2308`. The sources of PkHex say `0x4024`

**Comment by sora10pls** [comment]
<flag #>: before->after

**Comment by kwsch** [comment]
for the 'event constant'/variable output, it's the variable number followed by before->after as @sora10pls mentioned.

The 0x40XX values are not offsets within the save file; they are internal markup for the game to identify different event values. 0x0XXX is for event flags, 0x4XXX is for event variables and 0x8XXX is for temp variables.

These 0x4XXX values are the preferred representation as they are commonly used in the custom scripting engine the game uses (and ingame scripts can be used as a reference instead of doing before/after dumps).

The common user does not care about which internal value a name is for, hence it's only necessary to show the name. They can always refer to the source code for more information.

For adding event variable entries, it's tab separated `var_num \t var_name \t var_valueAndDescriptions`. The value-descriptions are split by a colon `:` and each unique pair is separated by a comma `,`.
`0x402C	VAR_RESET_RTC_ENABLE	00:Disabled,2336:Enabled`

The current variable descriptions match [the disassembly](https://github.com/pret/pokeruby/blob/e424136fc5e648084125775e45f9084c33ea7303/include/vars.h), and can be easily referenced for uses ingame for easy research.
