### ISSUE TITLE
Gen I and II Games: Language of save game is wrong

### ISSUE THREAD

**Issue by kurainooni** [kwsch/PKHeX#1540]
**Possible feature request:**
When using any non english save games from Gen I and Gen II games, english is set as the default language( unless it is a Japanese or Korean save game; not tested by myself with these languages). Therefore all Pokemon Names will be set as nicknamed, if they have different names than the english ones( e.g. a Bulbasaur called BISASAM will be checked as nicknamed, while Pikachu won't)
This applies to eggs as well.

**Possible Solutions:**
- One solution could be to use the language you have set in PKHeX to determine the language.( Should work for PK1toPK7 and PK2toPK7 conversions as is, without having to add a language info to these files)
- You could also ask for the language upon opening the save games(similarly to how it was done with Gen III). However PK1 and PK2 files would still default to english when imported.
- The third solution could be to imply the language by comparing the name of the Pokemon with the localized names, and selecting an appropriate language for it. This could lead to some Pokemon still defaulting as english language, or not the actual language( Some localizations use the same names as each other, usually the english ones)

**Comment by kwsch** [comment]
There's no way to detect gen1/2 languages for EN-DE-FR (as far as I know -- would be advantageous to have this but likely not possible).

PKHeX doesn't check for FR/DE, always assumes EN.
The dropdown detects current language, with default to lang=2 (english)

* PKHeX 1/2->7 uses the currently loaded save file language rather than the (unknown source) language. Bank has the luxury/limitation of only interfacing with installed games, thus it can know the language it's transferring from.
* Gen3 lang detection was improved to automatically detect the language (OT length can be inferred). I'd prefer not to have language selection prompts in favor of more hands-free loading of saves.
* PKHeX 

Likely just need to add language IDs and insert a language check in the `if Japanese 1 else 2` instances.

https://github.com/kwsch/PKHeX/blob/096f6bbd1873b847c857ea021c542fcf99510bcb/PKHeX.Core/PKM/PKX.cs#L234-L254

https://github.com/kwsch/PKHeX/blob/096f6bbd1873b847c857ea021c542fcf99510bcb/PKHeX.Core/PKM/PK1.cs#L103-L130
