### ISSUE TITLE
Pkm Drag and Drop renaming issues.

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#1543]
Having a little problem when I drag and drop some .pkm format pokemon into pkhex. When I do this into my gen 5 save the nickname part of the pokemon get's distorted and the nickname flag stays off flagging my pokemon as illegal. The OT also changes. They're all Japanese Characters. From what I've noticed each Japanese character corresponds to an english letter.

Latias = るグッジグヂ
Emilia = やゼジセジグ

As you can see the instances of "A" and "I" are the same on both. The "L" is different because one is capital and the other is not.

When I import the pkm into a gen 7 save the OT is changed but the name is not.

Does this have anything to do with trash bytes? I remember on Pokegen to make pokemon in gen 5 you needed to add \FFFF\0000\FFFF for OT/Nickname areas does pkhex take care of this automatically and legitimately? Also I was going to import these pokemon to my B/W game to then poketransfer them normally to my Sun/Moon. Would putting them directly on a gen 7 save make any difference? I just wanted to transfer them through poketransfer so I'm sure they have no issues with their filters etc and I cam across this OT/Nickname issue.

Lastly, an old Manaphy pkm with "Pokemon Ranger" as the egg location gets changed to "Fullmoon Island" for some reason.

Example .Pkm files
[Pkm Examples.zip](https://github.com/kwsch/PKHeX/files/1408910/Pkm.Examples.zip)

**Comment by kwsch** [comment]
This is due to pk4 and pk5 having the same structure size with minor differences.
The input pkm are not legal to begin with, as you cannot have a unicode-string for Nickname/OT for a past generation pkm without having transporter (or crown beast) as the met location or a version ID above the Gen4 games.

PKHeX does this "isPK4 or isPK5" detection as follows:
https://github.com/kwsch/PKHeX/blob/69cf1eaa9c22bc89cfd5a0fc249cc0dac8ebe473/PKHeX.Core/PKM/PKMConverter.cs#L53-L58

(0x80 is met location, 0x5F is version, 0x46 is PtHGSS met location, wiped on 4->5).

Manaphy has Met location values 40070 (met), 60 (eggmet); 60 = Fullmoon Island
https://github.com/kwsch/PKHeX/blob/69cf1eaa9c22bc89cfd5a0fc249cc0dac8ebe473/PKHeX.Core/Resources/text/en/text_hgss_00000_en.txt#L61

Not sure where the .pkm files were exported from, but they can't be a mix of gen4 and gen5 formats.

**Comment by ReZeroEmiria** [comment]
When you say the input pkm, do you mean the pkm files I've sent are not legal? or do you mean the format ".pkm" isn't legal?

Apologies for the lack of understand of some terms:
 - I've never heard of "crown beast".
- I don't understand what you mean by the "unicode-string..." part of the statement.

Are the pkm files a mix of gen 4/5? They were exported from Pokegen , the game save/target game is Black (2) / White (2) and in this case the Latios/Latias are from Gen III origin and Manaphy is from Gen IV. So like I asked before, about the trash bytes/escape sequence things and about the transferring? Would these pkm be legal if I just dragged them to a game and changed their OT/Nickname and locations to proper ones? or do I have to worry about other things?

Here's an example of it being put into a BW save on pkhex and SuMo save. (pk5 and pk7)
[pk5-pk7.zip](https://github.com/kwsch/PKHeX/files/1411897/pk5-pk7.zip)

One other question that just occurred to me is Pokemon being named in caps by default in gens 3-4 without nickname, what happens to these Pokemon's names when they are transferred to gen 5-7?

Also, I noticed that while working with Darkrai (Gen IV Member Card Platinum) Pkhex says that having the "Fateful Encounter" box checked is Invalid

While on Serebii: https://www.serebii.net/events/membercard.shtml

And Oak's Letter Shaymin is required to have the box checked, just thought that was weird.

**Comment by kwsch** [comment]
>When you say the input pkm, do you mean the pkm files I've sent are not legal? or do you mean the format ".pkm" isn't legal?

pkm data in the files is not legal (not referring to extension)

* Crown Beast is referring to the Gen2 roamer / celebi events in generation 4 that can trigger in-game events in generation 5.
* Each game has a font & available characters for text entry, and values that they get saved as. Generation 5 started using unicode, whereas generation 4 and below had unique encoding (ie not ASCII/Unicode).

The pkm files you've attached are from generation 5 but are being interpreted as generation 4, which causes them to be translated back to generation 5 when loaded by the program. This detection operates by scanning for legal values to make the determination as accurate as possible.

You can use PokeGen to inject the pkm files into a generation 5 save file, then load that save file in PKHeX to see the legality report.

Trash bytes are cleared on transfer from 5->6, and PKHeX doesn't care about trash bytes.

Generations prior to 5 have pkm names in all caps; everything since is in proper case.
https://github.com/kwsch/PKHeX/blob/a03ac10fc5a2c52e3264f6525f02be80a5972d40/PKHeX.Core/PKM/PKX.cs#L216-L232

Member Card Darkrai does not have a Fateful Encounter flag when captured.

**Comment by ReZeroEmiria** [comment]
Thank you for the explanations! Apologies for the mix-up on Darkrai, I just thought it was odd and serebii also says "Apparently had a fateful encounter at Lv. 50" is that just an error on them then?

**Comment by kwsch** [comment]
Yes, likely copy-pasting between pages.
