### ISSUE TITLE
Ultra Sun & Ultra Moon Issues

### ISSUE THREAD

**Issue by ngtunganh** [kwsch/PKHeX#1570]
I edit my save with lasted build then try import back with jskm and it happen
I tried to use .bak file to restore but no use

**Comment by sora10pls** [comment]
https://twitter.com/SciresM/status/928258908732383233
>corrupts save if you don't disable pokedex setting, though...

**Comment by sora10pls** [comment]
https://twitter.com/SciresM/status/928258908732383233
>corrupts save if you don't disable pokedex setting, though...

**Comment by sora10pls** [comment]
https://twitter.com/SciresM/status/928258908732383233
>corrupts save if you don't disable pokedex setting, though...

**Comment by ngtunganh** [comment]
so is there any way to fix it ?

**Comment by kwsch** [comment]
PKHeX still isn't advertised with working support for USUM.

The current progress was made public so that the contributors (those who submit pull requests with code changes) can begin testing certain features and finding what needs to be changed -- it'll be gradually fixed & correctly implemented in the coming days.

Leaving this issue open for now as I expect this to be a common question.

**Comment by ngtunganh** [comment]
I tried lasted build and it back to normal now
Thanks for your hard work

**Comment by sora10pls** [comment]
Assuming this'll be a general thread for USUM issues, not gonna bother creating a new one for this.

PKHeX [throws an exception](https://pastebin.com/SKVVeNGB) when viewing any Totem that isn't Raticate (CTRL right-click slot -> Legality). Set Zygarde Cells amount to 100 (as I showed you on IRC, works with Totem Stickers) in order to receive every Totem in-game.

[um_totem.zip](https://github.com/kwsch/PKHeX/files/1456522/um_totem.zip)

**Comment by kwsch** [comment]
Have yet to add the USUM evolution binary, which has weird handling for individual methods.
Need to get more info on those 3 new evolution methods first

**Comment by kade-robertson** [comment]
I imagine this is just something that hasn't been added yet, changing the start date of your save causes the save to fail the checks:

```
Invalid: 24 @ Region 6C000
SAV: 38/39
```
