### ISSUE TITLE
Select Generation to import

### ISSUE THREAD

**Issue by ajtudela** [kwsch/PKHeX#159]
It would be possible, for example, adding a button or something like that to select a generation?

If I import a pk5 pokemon in a gen5 format, without conversion to 6 and then save it in a pk5 format. In that case I could insert the pokemon in, for example, Pokémon White.

By default all PKM imports are converte to gen6

**Comment by evandixon** [comment]
If implemented, I think the easiest way to select which generation would be to have each supported generation as a filter in the Save dialog, so a user would use File -> Save PKM... -> choose a generation with "Save as type" -> Pick a name for the file -> Save.  It probably won't be that easy, since converting Pokémon between generations isn't the easiest thing out there, with a lot of factors to consider.

(Waits for Kaphotics's opinion on the feasibility of this.)

**Comment by kwsch** [comment]
Partially addressed in the following commit:
https://github.com/kwsch/PKHeX/commit/a7d188894304262441f038defecd7dd4c71053e3

When the program is loaded, a dummy gen6 save file is opened. Currently, there's no way to load a dummy gen5 save file.

When you load a pk5 to a gen6 game, the format is automatically converted, can't go back! So the only way to make and save pk5 files is to have a gen5 save file loaded.

Easiest solution is to do nothing and require the user to load a save file.
Another solution would be to implement something similar to PokeGen's "Target Game".

The Target Game solution is of course more code and would need another Option combobox added to allow the user to load dummy saves. But, is that really worth it?

**Comment by javierhimura** [comment]
What about to run the program with parameters? If someone run pkhex.exe it will load by default a dummy gen 6 file , but if someone want to run pkhex.exe with a dummy gen 5 save by default he just need to run "pkhex.exe - g 5", any user who want it can creat a link/bat

**Comment by evandixon** [comment]
Why not just load a real gen 5 save?  If you really want it to be a dummy save, you can pass in the filename of the save file to load as the first argument.

**Comment by suloku** [comment]
About save file dialog supporting multiple gens, I also have thought that it would be great if a pk file could be saved as it's generation or higher (I'm against "downgrading" though, due to data loss).

About dummy saves: is there really a reason to not include a real save into pkhex made only for the purpose of being a dummy save? You may always use an unused region of the save to tag it so pkhex always knows which one is the dummy save to disable feautures if needed.
For the purpose, it is only needed to play the game until boxes are fully working right?
Since pokemon

**Comment by kwsch** [comment]
Including empty save files would baloon the executable size; save files are easily obtainable online (like gamefaqs).

Exporting in a forward format (4->6) is unnecessary, as PKHeX can open past gen files and do the transporting required.
