### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by KekMcGee** [kwsch/PKHeX#1644]
Would it be possible to add the ability to unlock all music tracks for battles?

**Comment by kwsch** [comment]
Requires documentation to be done first (on the forums) prior to being possible to implement.

**Comment by sora10pls** [comment]
@KekMcGee probably related to event flags since tracks are unlocked after doing certain battles. Example:

- Necrozma, Version 1: Defeat Dusk Mane/Dawn Wings Necrozma
- Necrozma, Version 2: Defeat Ultra Necrozma
- My Friend Hau, Version 2: become Alola Champion
- Maxie & Archie: defeat Archie and Maxie in Team Rocket's Castle
- Johto Legend: catch Raikou, Entei, and Suicune


etc.

**Comment by KekMcGee** [comment]
@kwsch Alright
@sora10pls I've tried enabling certain flags, but they didn't unlock anything.
