### ISSUE TITLE
Pal Parked Pokemon Happiness

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#165]
Isn't the happiness of a Pal Parked Pokémon reset to 70?

**Comment by suloku** [comment]
I know this has been closed, but I looked at the commit and I questioned myself: are all pal parked pokemon set to 70 friendship? There are a few exception that have a different base happiness, i.e. dratini, zapdos, moltres, mewtwo, deoxys...
Not sure if this is already known or simply hasn't been tested.

**Comment by evandixon** [comment]
Re-opening issue because suloku appears to be correct.
http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_friendship

**Comment by evandixon** [comment]
Wait, I missed this when I first found that page:
"A Pokémon's friendship will also be set to 70 if it is traded, regardless of the base friendship for its species."

I don't know if that applies to Pal Park, but someone should double-check.

**Comment by suloku** [comment]
Sorry, I forgot my legit diamond save has gen 3 palparked pokemon, including legendaries. They all have friendship 70, but this might be because of pokemon box storage (apparently also sets friendship to 70), but I don't think pal parking respects current friendship.

Sorry for not checking before posting.
