### ISSUE TITLE
Wrong Met Location for some Gen IV events

### ISSUE THREAD

**Issue by exegg** [kwsch/PKHeX#166]
Some events like the shiny beast trio, have met location as Zoroark (1) instead of Pokémon Event when you drag the pcd/pgt to tabs. I've only tested these three so far, don't know if it replicates with other events.

Got the event files from Project Pokemon.
![a](https://cloud.githubusercontent.com/assets/19347211/17462104/07018fe0-5c70-11e6-8667-7c2cc9f4c830.png)

**Comment by kwsch** [comment]
Not a bug, when no save file is loaded a dummy ORAS save file is loaded.

Opening a past gen event file automatically transfers it to the save file's generation, which includes doing all the modifications to the resulting pkm file.

So instead of it being a 'gen4' pkm, it's really a gen4->6 pkm, where the crown location is specially modified in the gen4->5 transfer to the "Zoroark" triggering value.
