### ISSUE TITLE
PKHeX does not preserve quantities of 0 in item list

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#1670]
In S/M/US/UM, after you use up your last copy of an item, an entry for it remains in the item list (always at the end) with a quantity of 0. This doesn't show up in-game when you select the bag, but it is relevant in that if you proceed to collect another copy of the same item, the game knows that you've had it before, and does not mark it with the "NEW" flag.

In PKHeX, meanwhile, if you try to make any alteration to the item list (even if you stay away from any of the 0 slots), upon saving, the program will automatically change all items associated with quantities of 0 into (Null), thus removing that history. In fact, making any changes to the item list is a potential security risk, because a sophisticated enough save file parser can use that as a form of fingerprinting. For example, having an Arcanine anywhere in your party or PC, for which you are the OT and there is no handler data, but not having the Fire Stone appear in the item list in any quantity (not even 0), is proof that something is amiss.

**Comment by kwsch** [comment]
I've only seen this happening for the Roto powers in gen7; however, what you've said makes logical sense. I'm not sure I remember it pushing empty slots to the end... 

Handling this would be pretty easy ([just updating the SetBag method](https://github.com/kwsch/PKHeX/blob/8f8cf5bc9ad4a825ceb9adbb69898a2f800dbcb5/PKHeX.WinForms/Subforms/Save%20Editors/SAV_Inventory.cs#L192-L203)) to use the HasNew bool & move empty slots if applicable.

tagging @sora10pls

**Comment by kwsch** [comment]
Looks like some items go to the complete bottom of the list, while others stay at the bottom of the items.
![image](https://user-images.githubusercontent.com/6393368/33411993-b8a5a24e-d53d-11e7-96c1-111ca14109e4.png)

Not sure what causes it to drop some all the way to the bottom instead of the near-bottom, but I'll add something to not tamper with the 0 count items. Sorting may have to be updated if there's any rules found.
