### ISSUE TITLE
Actual PP showing instead of Total PP

### ISSUE THREAD

**Issue by egzonqj** [kwsch/PKHeX#1696]
Not sure if this is known or something that is working as intented, but when I watch a Pokemon's Attacks, the Current Moves' PP that are being shown are the actual ones, instead of their Total. 

This is a recently caught Terrakion (I'm using the latest release)
![image](https://user-images.githubusercontent.com/5099644/33684595-19ed4a84-dacf-11e7-8b14-74d6672215f7.png)

**Comment by sora10pls** [comment]
If it was in your Party, that'd be working as intended because before catching it, it's already consumed PP in all four of its Moves.

But, one thing I'd like to point out is that it's in his Box and has consumed PP. When deposited into a Box, a Pokemon is always fully healed; HP, status ailments, and PP. I don't think PKHeX does this automatically if moved from Party->PC Box...

**Comment by egzonqj** [comment]
Nop, it was not in my Party, it was just assigned to the Box slot manually (with the prompt that now the game gives after catching a Pokémon)

**Comment by sora10pls** [comment]
lmao so GF is dumb, sending to PC after catching and Party is full doesn't restore PP

Looks like that's just how the game handles PP in that scenario.
![image](https://user-images.githubusercontent.com/17801814/33688214-a017b5da-daa8-11e7-9b21-2576df0eb15a.png)

**Comment by egzonqj** [comment]
So it's the intented behavior then huh
