### ISSUE TITLE
Possible Addition: Adding @architdate's Auto Legality Mod

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#1704]
I don't know if this can be added in but @architdate Auto Legality Mod for PKHeX can be a great addition just for adding in Showndown Imports and making everything legal.

https://github.com/architdate/PKHeX-Auto-Legality-Mod

I saw that if you just added in a couple of stuff into PKHeX, it would save time into checking legality and make it easier to add in Pokemon. Can confirm it works with his coded added into your program.

**Comment by sora10pls** [comment]
#1294

Was brought up a few months ago with no response.

**Comment by ricksee** [comment]
@sora10pls Could we still leave it open for response? It really is a useful feature. I hope it is considered at least.

**Comment by kwsch** [comment]
I'm not interested in maintaining this; it works fine as a fork/augmentation of the default program with its limited scope.

- Only works if English is the current language
- Heavy reliance on GUI/string compares to make a file legal (slow, can't be cross-platform like PKHeX.Core)
- Bruteforce oriented fixes instead of search/property oriented (doesn't use any Legal/LegalityAnalysis api functions)
- Gets broken every time PKHeX adds new legality checks (future Shadow locks)
- Reuses RNG Reporter code (conflicting license)
- Doesn't handle every edge case (C/XD)

**Comment by architdate** [comment]
@kwsch that is a perfectly fair assessment! I didn't really even think that my mod was known enough for this to be an issue on the main repo. The auto-legality mod is just my hobby project. I'm nowhere as well versed in C# as kaphotics. However I do plan to improve my code. The GUI elements currently used are indeed bad practice code which does slow the computation down but that is limited ATM to just events and some error correction. (Something which I hope to eradicate completely in the coming weeks) The only reason this exists is for me to practice some c# code while viewing actual results. And maybe help the community in doing so. C/XD is also implemented currently (just need to update the readme regarding it) However the other issues are perfectly valid. Since my current correction is based on English strings it cannot make a legal file in any other language. The bruteforcing analysis is also correct (truthfully, I did the base pseudocode when I was too naive to even read c#) and every legality update (such as shadow locks) does force me to update my code everytime to make it legally compatible with the latest base PKHeX commit. The scope is limited as well, only implements egg based, static encounter based and M1/MColo/XD based Pokemon. (Covers 99.9% of all possible legal sets)

I will consider your comment above however as feedback and improve upon my code till it meets the standard of the base PKHeX code! Thanks for the feedback :]
