### ISSUE TITLE
[Bug] Event Pokemon, Incorrect origin game

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1727]
It seems that a lot of the events that i open (dragging wc7fulls into PKHeX) have the origin game of Ultra Sun with met location being "a lovely place". This is perfectly fine to do, however if an event is only for a specific game (Ultra Moon) for example, then PKHeX will throw a legality error since it still reads the origin game as Ultra Sun. So to fix this, the origin game should be fixed when wondercards are loaded.

An example of this would be the Trainer Ultra Moon Rockruff. You can try to just drag it into PKHeX and since both the US and UM events have different relearn moves, it will give you an error with the relearn move (Missing firefang which is the US Rockruff relearn move)

Event file example: https://github.com/projectpokemon/EventsGallery/blob/master/Released/Gen%207/Wondercards/ENG/1624%20UM%20-%20(Trainer)%20Rockruff%20(ENG).wc7full

To test just drag the file in PKHeX.

**Comment by kwsch** [comment]
Not a bug; the WC7(full) file does not provide a Game ID (Version), thus the WC7->PKM conversion uses the currently loaded save Game ID to generate the pkm.

https://github.com/kwsch/PKHeX/blob/a1f2f8708ac2a1b7ac139f7e77e7decd5b6d75be/PKHeX.Core/MysteryGifts/WC7.cs#L323

PKHeX does not do card receivability checks; only for these cards in specific is there manual flagging implemented.

https://github.com/kwsch/PKHeX/blob/a1f2f8708ac2a1b7ac139f7e77e7decd5b6d75be/PKHeX.Core/Legality/Encounters/EncounterGenerator.cs#L1420-L1427

No fix necessary on PKHeX's end in the current state; a complete list of game receiving compatibility for WC* hashes needs to be generated by the community prior to a more comprehensive implementation being possible.

**Comment by architdate** [comment]
@kwsch from my discussion with him we came to the conclusion that wc7s may not support game versions, but it seems that wc7full does it :D

**Comment by kwsch** [comment]
* Save files and actual usage does not need the full data (only saves WC* to sav; PKHeX does not store wc*full data, only the sav-compatible object).
* Not every 'full' record has been saved by the community (missing compatibility/distro text).
* Distribution text is a waste of storage space; the only extra benefit of the 'full' data is compatibility data (which is a single byte, not 0x200).
* Distribution compatibility values stored may be incorrect due to game availability (full flags set but no future game released during distribution window).

Hence why manual value comparison/conversions are needed:
* card hash (computed int) -> compatibility flags (enum) -- via hashset
* compatibility flags (enum) -> version[s] for picking at random
* compatibility flags (enum) & version -> receivable

**Comment by kamronbatman** [comment]
This is unfortunately true.  In Gen 7 there were some pokemon distributed to SM only but flagged for SMUSUM.

With that said, I will be converting all Gen 6 WC's to WCFulls to make life easier for everyone.  While there is no way to know if GF (or whoever made the events) didn't screw something up, it at least gives us more information.  Regardless though, a catalog will be needed.
