### ISSUE TITLE
Friend Safari 3rd Slot Unlock seems to be broken again.

### ISSUE THREAD

**Issue by Storm-Eagle20** [kwsch/PKHeX#1765]
I know you got an issue about 7 months ago, but it seems that even with the latest version of PKHeX I can't manage to unlock all slots. Trying to do so doesn't work, and I don't get any sort of confirmation that it does.

I'm using the 12-17-05 build and despite looking through the issues and seeing it was fixed previously, it seems to be broken again...

Can you consider fixing this?

**Comment by kwsch** [comment]
Hasn't been modified since its initial introduction.

https://github.com/kwsch/PKHeX/commit/b789478a251ce9c91fc1a231287f170ebd7ae933#diff-b88b8bed8cc5fad47a20a642474bd30bR4130

**Comment by Storm-Eagle20** [comment]
https://github.com/kwsch/PKHeX/commit/13d3e515f04338f79f0aa9f7b15364234cd14f39

This commit shows otherwise.

https://github.com/kwsch/PKHeX/issues/1241

It's been an issue before and you have fixed it, but it appears you have removed that piece of code, possibly on accident.

**Comment by Ammako** [comment]
[intro](https://github.com/kwsch/PKHeX/blob/b789478a251ce9c91fc1a231287f170ebd7ae933/PKHeX.WinForms/MainWindow/Main.cs#L4130)
[latest](https://github.com/kwsch/PKHeX/blob/master/PKHeX.WinForms/Controls/SAV%20Editor/SAVEditor.cs#L565)

The function for it hasn't changed (and you know that the one line you're referring to that has been added doesn't actually change the functionality), it has simply been moved into a different file at some point.

If there's an issue, it has to have been caused by something else in the code, in a different commit. You could always do something on your end to try and pinpoint which commit it stopped working at.

From the initial commit it was implemented in (b789478 on Apr 4, 2017), and until the current latest commit, pick the commit in the middle of that range and compile it. See if it works on that commit.
- If it works, you know that the problem started in a more recent commit, so pick the commit halfway between that one and the latest.
- If it doesn't work, you do the opposite, and pick the commit halfway between that one and the initial commit.

Rinse and repeat, eventually you'll figure out on which commit it no longer works, and it's likely that the changes from that commit would be the reason why it doesn't work.

Compiling is easy. Just install Visual Studio (it has free trial, so), open the .sln, set configuration to Release (dropdown list at the top), and build PKHeX.WinForms. It should automatically build PKHeX.Core to go with it, but if it doesn't I guess you can always manually compile it separately. Output window tells you where the compiled binaries end up.

**Comment by Kxcii** [comment]
I've been trying to get this function working myself and have run into the same problem. Whatever changed or didn't change, the function 'unlock 3rd slots' does not work.
