### ISSUE TITLE
can compile version release just with links information ?

### ISSUE THREAD

**Issue by netzulo** [kwsch/PKHeX#1773]
https://github.com/kwsch/PKHeX/issues/1767#issuecomment-359261895

Then, can please post links on github as release tags ? *just 1 min of time, please :)*

## Issue related #1767

Community need it 

## TODOs 

+ [ ] tag releases
+ [ ] binaries versions as release

**Comment by architdate** [comment]
GitHub releases exist for having a version control on the releases. The project pokemon forum handles the releases under one link to the latest release which can be found [here](https://projectpokemon.org/home/files/file/1-pkhex/) There is no point in having this link being in releases since every binary release will have the same link! If you want the latest commit I recommend building the executable on your own. Alternatively a better request would be to include the project pokemon pkhex download link in the readme since that would always be static. Kaphotics has already stated in #1767 that he is not interested in using GitHub releases.

**Comment by sora10pls** [comment]
\>go to GitHub repo
\>click URL
![image](https://user-images.githubusercontent.com/17801814/35421672-7d3208ae-0212-11e8-8279-e2592507a075.png)
\>click "Download Location Here"
![image](https://user-images.githubusercontent.com/17801814/35421688-931a426c-0212-11e8-8fab-06b97edc038c.png)
\>click "Download this file"
![image](https://user-images.githubusercontent.com/17801814/35421701-a1c3a10a-0212-11e8-99b3-4faa153ac7e1.png)
\>download the appropriate version
![image](https://user-images.githubusercontent.com/17801814/35421706-aef0b746-0212-11e8-8159-e3227e453a4b.png)

**Comment by kwsch** [comment]
Just use the version.txt revision history for release days.
GitHub is only used for posting the current code and a secondary issue reporting location.

**Comment by netzulo** [comment]
Thank you for information :) enough
