### ISSUE TITLE
gen 5 pokedex skin editor

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#1800]
Hey I just wanted to know if you were planning on adding the pokedex skin editor to pkhex since you got the c-gear editor up and running. I have only found a few fringe programs that allow the changing of the pokedex skin so allowing this on pkhex would be great. Thanks and loving the new features that have been implemented. Keep up the great work

**Comment by kwsch** [comment]
As usual for more niche features, the topic has to be documented well enough for implementation (needs visualization).

For C-Gear Skins I had done enough documentation back in 2012, but nobody has documented the structure of the pokedex skin variant.

Closing until the dex skin structure is documented on the forums.

**Comment by kuroppoi** [comment]
Hello, I'm not sure if this will ever be read, but Pokédex skins are very similar to C-Gear skins in terms of structure.
The main difference between the two is that Pokédex skins have `768` tiles as opposed to C-Gear skins, which have `255`.

Pokédex skins also seem to have enough space for `256` colors, even though, like C-Gear skins, only `16` of those colors may be used by the skin itself. I suspect that the other colors are reserved for the background, as some Pokédex skins only serve as overlays on top of the default Pokédex and do not take up the whole screen.

As for tile mapping data; there is none. Because Pokédex skins have `768` tiles, which is enough to fill the entire screen,
the tiles are simply applied in the same order they are laid out in the file.

Hence, the structure of the data should be as follows: (start is inclusive, end is exclusive)
`0x0000 - 0x6000` = Tile data
`0x6000 - 0x6020` = Color data
`0x6020 - 0x6200` = Background color data
