### ISSUE TITLE
Legality for Parnered Cap Pikachu

### ISSUE THREAD

**Issue by k20stitch** [kwsch/PKHeX#1817]
So i just redeemed my partnered hat pikachu (eng) and opened it in PKHeX and it comes up illegal, complaining about the OT base friendship.  It came with the OT Friendship of 74 but complains until I change it to 70.

**Comment by kwsch** [comment]
The current handler can never be the Original Trainer, thus the friendship for the OT can never increase from the default value.

Program is working as intended.

**Comment by k20stitch** [comment]
I’m talking about an unmodded monster here... I redeeemed the code, loaded the save file up, and it comes up illegal.

**Comment by k20stitch** [comment]
The OT (ash) has a friendship value of 74

**Comment by DeathAngel74** [comment]
The program is working as intended. The default friendship value is 70, not 74.
![capture](https://user-images.githubusercontent.com/29271009/35894586-55aa147a-0b68-11e8-9676-eada7225aa96.PNG)

**Comment by k20stitch** [comment]
Oh okay, I’ll just let Nintendo know that this unmodded event Pokémon has the wrong OT friendship lol. I’ll let them know the hackers told me so.

**Comment by wwwwwwzx** [comment]
GF forget to change the Current handler flag.  
As long as you don't trade out or upload to the bank, you can increase the friendship and affection with Ash...
(Viewed and dumped via PKMN-NTR)
![](https://imgur.com/4G3LSqp.png)
![](https://i.imgur.com/MGBcjAv.png)
[025-07 - 皮卡丘 - 603544C02681.pk7.zip](https://github.com/kwsch/PKHeX/files/1705555/025-07.-.-.603544C02681.pk7.zip)

**Comment by kwsch** [comment]
@kamronbatman The [simulated Pikachu gift](https://github.com/projectpokemon/EventsGallery/blob/b552376d6340e842e6428255e0a354cf06f7e1be/Released/Gen%207/Wondercards/ENG/0275%20SM%20-%20Ash%20Original%20Cap%20Pikachu%20%26%20Pikashunium%20Z%20(ENG).wc7full) PID type needs to be changed to allow shinies so that the encounter can match shinies.

Will add an exception for the OT Friendship/Affection/Handler check, only for this Pikachu.
