### ISSUE TITLE
Gen 3 Pokémon edit always make "unknown gba type" PID

### ISSUE THREAD

**Issue by JHorbach** [kwsch/PKHeX#183]
So, when I edit a Gen 3 save file, and reroll the PID when making a new pokemon(or edit someone), then transfer to Gen 4 and check with the legality checker, it always says "unknown gba type", instead of "Common GBA NDS Method 1". I don't know if it's a bug, just reporting.

**Comment by kwsch** [comment]
PKHeX does not do any PID-IV generation for randomized PIDs.

The games (and GameFreak/TPCi/Nintendo) do not care about PID-IV methods, so instead of restricting IVs the program just spits out a playable PID.

Users are still free to generate a PID themselves with any other program and paste in the PID&IVs :)
