### ISSUE TITLE
[Feature Request] Master Settings management window

### ISSUE THREAD

**Issue by architdate** [kwsch/PKHeX#1864]
A proper master control window for toggleable settings such as shiny sprites/ Unicode/ Legality Flagging as well as preferences such as Markings while importing PS! sets/gender priority etc would be greatly appreciated!!
Thanks in advance! and keep up the good work!!

P.S. this was also referenced as a possible addon [here](https://github.com/kwsch/PKHeX/issues/1862#issuecomment-372508300)

**Comment by kwsch** [comment]
Probably would be implemented as follows:

- [ ] `MasterSettings.cs` class which has get/set logic for each bool property.
- [ ] Specialized form that uses Reflection on the `MasterSettings.cs` class to generate Checkboxes (named after property).

That way, new settings can be easily added (one getter, one setter = ez) without reliance on the GUI.
Would have to reconfigure the WinForms settings to not save the old bool user settings, and instead save the new settings object (somehow).

**Comment by kwsch** [comment]
I probably want to rework form translation while I'm at it to a more simplified format. The current iteration translation files are hand made...

translation file: control.Name -> Text (using dictionary, translationdata)
- [ ] One dict for form title bar text
- [ ] One dict for control text
- [ ] Translating Forms use form.Name.
- [ ] Translating Controls first look for $"{form.Name}.{control.Name}", if a form-specific doesn't exist, use control.Name.

Benefits:
Failed form.Name lookup can add a new entry to form name dictionary
Failed control.Name lookup can add a new entry to control name dictionary
Can create new translation files (dump both dicts easily)

Should make it easier to maintain translations (since most new forms aren't even supported).
