### ISSUE TITLE
Pokemon Platinum Poketch Error

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#1877]
Currently the Miscellaneous Edits Poketch  "Give All" button removes the Poketech.
Thanks for all your work with PKHeX!
[POKEMON PL.zip](https://github.com/kwsch/PKHeX/files/1844028/POKEMON.PL.zip)

**Comment by kwsch** [comment]
What app did you set as the current app?

**Comment by greenDarkness** [comment]
Coin Toss.

**Comment by kwsch** [comment]
I was able to give all and load up just fine with the coin toss still showing up

![pic](https://user-images.githubusercontent.com/6393368/37860527-6557132e-2ee4-11e8-9ddf-80570c46238d.png)

**Comment by greenDarkness** [comment]
Hmm, that's really strange. After selecting "Give All" the Poketech was definitely gone on my end.

**Comment by greenDarkness** [comment]
I'm gonna close the issue, and try to reproduce it. If I do, I'll come back.
Thanks for all the help!

**Comment by huloro** [comment]
Sorry for bumping, same happened to me. I didn't do it intentionally actually, I was looking for ribbons segment, and I ended up on that segment. The mistake I did was mistaking the cancel button for save button, and the give all check was probably checked, then all the poketch was gone. I tried out all I can think of like checking and unchecking the boxes, trying out several AR codes, quite a shame I didn't get a recover copy of the first. Is there a way to get it back, have you, by any chance, end up with a solution? Currently on NocashGba. Thanks in advance.

**Comment by kwsch** [comment]
@huloro use the .bak file that is automatically created.

**Comment by huloro** [comment]
Okay kwsch, it seems this issue occurs when either you don't actually obtain the apps throughout the game or you lose it during the process of using PKHEX to have the all apps (this one is my case), and first of all, I should emphasize all I did is purely trial and error method. After I completed all, I used the program to have the all apps in PKHEX once again and of course double checked it is not unavailable, and yes it disappeared again. This time I recovered, and tried to collect them manually, yet I had already collected most of them. Then I suspected it might occur because of the legality since, as you know, some of the apps are given through Nintendo Events, strangely, they appeared. However, if you choose 23 apps only, it won't let you to have all of them. How did I get the picture? As being said, there were some of them I didn't collect, I only chose the ones I already collected and continued on collecting others manually and there, when I collected 24th one, one of the others disappeared from the Poketch, and after 25th another one. So then, I chose 23 and 24 of them again to confirm it, and yes only 23 of them allowed to not have an issue. Then I used PKGEN, and yes you can have all of them without any issue. Whether the issue is because of the first things I have stated or not is debatable, I am guessing it is related to PKHEX and as afore-mentioned, and could be related to legality too. I am not so sure as I do not have either enough experience or knowledge of both programming and coding. I am just a gamer apart from my proficiency. So, to conclude, I am sharing this just because some gamers like me may come across with this situation, and by entering the proper keywords on the search engines, they can find the solution, and as you have been informed, you may also solve this. Purpose is purely informing and helping, neither discredit your product or the team, and apart from this issue it is indeed a very useful and great program. Congrats. Hope it helps, thanks for reading.
