### ISSUE TITLE
Japanese display is not done in Gen 6 main window.

### ISSUE THREAD

**Issue by smileynation** [kwsch/PKHeX#1883]
Japanese display is not done in Gen 6 main window.
Pokebloks > ポロック
Poke Puffs > ポフレ

Main.B_OpenPokeBlocks=ポロック
Main.B_OpenPokePuffs=ポフレ

I marked up to lang_ja.txt, but it will not be reflected.

<img width="632" alt="2018-04-02 16 39 55" src="https://user-images.githubusercontent.com/32617637/38187973-d39eb3a2-3694-11e8-9073-0861034c181f.png">

**Comment by kwsch** [comment]
Translation text files are missing the control name references for those buttons.

The English text file was manually maintained to have all of the control names, but when PKHeX grew considerably, the list wasn't updated 100%.

Will probably need some special algorithm to get the control names of every single form with a text property so that the translation files can be more easily maintained with new additions.
