### ISSUE TITLE
Gen 7 TID/SID

### ISSUE THREAD

**Issue by ReignOfComputer** [kwsch/PKHeX#1923]
Hi, why change the way TID/SID is displayed in Gen 7? I think it makes it harder to "own" a created (from scratch) Pokemon now since the Gen 7 TID won't give the same actual TID and SID.

Also, isn't SID 5 digits?

(Also Alt+Click to clear Box is gone again)

**Comment by wwwwwwzx** [comment]
Old: 4 hex SID | 4 hex TID
![screen shot 2018-05-02 at 17 43 30](https://user-images.githubusercontent.com/14868500/39555736-595eacf6-4e30-11e8-998c-d5841b46b64c.png)
New: 4 decimal SID | 6 decimal TID
![screen shot 2018-05-02 at 17 39 08](https://user-images.githubusercontent.com/14868500/39555722-42e011cc-4e30-11e8-8b85-fc16c603bd29.png)
Note now new SID = WCID

**Comment by sora10pls** [comment]
Hovering over those textboxes in older builds would bring up a tooltip on these values anyway, in which the SID is 4 characters and the TID is 6. This honestly makes it easier to generate a Gen 7 PKM because you can enter the desired TID and then modify the SID afterwards; old builds would not let you do this without the Trainer Info editor’s generator.

Also regarding your issue on it being harder... If it’s 2018 and people don’t know that clicking the OT label changes the OT info to match the currently loaded save file, that’s on them (the shortcuts window exists for a reason).

**Comment by ReignOfComputer** [comment]
Okay, what if I want to make a VC Pokemon that needs 0 SID? Changing the SID field to 0 still throws the message "SID should be 0".

**Comment by sora10pls** [comment]
?
![image](https://user-images.githubusercontent.com/17801814/39560446-4b493348-4e6c-11e8-9976-2eb1af4a6d93.png)

**Comment by ReignOfComputer** [comment]
Oh, interesting. When I changed it to RBY that's what showed up for me. Changing it to Crystal first though, doesn't change the controls correctly.

**Comment by sora10pls** [comment]
I am also able to replicate that
@kwsch

**Comment by ReignOfComputer** [comment]
@kwsch still having the issue where the correct TID/SID controls don't refresh when changing between Gen 2 and 7. For example:

Gen 7 -> Gen 1: TID/SID
Gen 1 -> Gen 7: SID/Gen7TID

Gen 7 -> Gen 2: SID/Gen7TID
Gen 7 -> Gen 1 -> Gen 2: TID/SID
Gen 7 -> Gen 1 -> Gen 2 -> Gen 7: TID/SID
Gen 7 -> Gen 1 -> Gen 2 -> Gen 1 -> Gen 7: SID/Gen7TID

**Comment by sora10pls** [comment]
Easiest way to replicate is just by running the program and changing the default Zeraora's Origin Game to any Gen 1 or 2 game. Notice how the TID/SID controls aren't refreshed (as @ReignOfComputer mentioned) while it has the GB marker.
![image](https://user-images.githubusercontent.com/17801814/39629926-bf0dad4e-4f7b-11e8-9270-b7fc63085f92.png)
