### ISSUE TITLE
Smogon/Showdown inconsistencies with Necrozma Dawn Wings when importing

### ISSUE THREAD

**Issue by wrathsoffire76** [kwsch/PKHeX#1930]
So, when you look at a Smogon set for Necrozma Dawn Wings, the set gives you this

```
Necrozma-Dawn Wings @ Ultranecrozium Z
Ability: Prism Armor
EVs: 4 Atk / 252 SpA / 252 Spe
Naive Nature
- Moongeist Beam
- Power Gem
- Brick Break
- Photon Geyser
```

However, when you export it from Showdown, you get this:

```
Necrozma-Dawn-Wings @ Ultranecrozium Z  
Ability: Prism Armor  
EVs: 4 Atk / 252 SpA / 252 Spe  
Naive Nature  
- Moongeist Beam  
- Power Gem  
- Brick Break  
- Photon Geyser
```
Basically, there is a missing dash between the Dawn and Wings on Smogons side and PKHeX can't handle this.

**Comment by architdate** [comment]
For clarity, here is the set exported via the teambuilder: 
![image](https://user-images.githubusercontent.com/17220860/39678541-34c9c7b0-51c1-11e8-86c2-ace3f43a2459.png)
The fix for this was implemented in #1848 
While exporting via the [smogon webpage](https://www.smogon.com/dex/sm/pokemon/necrozma-dawn_wings/):
![image](https://user-images.githubusercontent.com/17220860/39678555-60a46066-51c1-11e8-86f8-bbca53b9a73e.png)
So I think we will have to modify the form check to include both forms "Dawn Wings" and "Dawn-Wings" in `ConvertFormFromShowdown` method in `ShowdownSet.cs`

**Comment by kwsch** [comment]
Could be generically handled by replacing spaces with dashes and vice versa.

**Comment by architdate** [comment]
>Could be easier to just have Smogon and Showdown agree on their formats...
Can't agree more :[
