### ISSUE TITLE
[Feature Request] Add Safeguard for Party Pokémon with Batch Editor

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#1948]
Currently, PKHeX allows for a user to modify their Party to have a full Party of Eggs, **if the Batch Editor is used**. The games do not allow you to do this, as you're required to have at least 1 other Pokémon in your Party that isn't an Egg.

Setting the slot works as intended bringing up the following alert:
https://github.com/kwsch/PKHeX/blob/335379bd2edab927f9537e40ea5be3cc017df5b6/PKHeX.Core/Resources/text/en/MessageStrings_en.txt#L89

If the Batch Editor is used for the following command:
```
.IsEgg=true
```
...PKHeX will not blacklist Party Pokémon. While you could do:
```
!Box=-1
.IsEgg=true
```
...I think that adding an extra safeguard with the Batch Editor is a good approach.

This shouldn't be allowed:
![image](https://user-images.githubusercontent.com/17801814/40129823-4868d114-5903-11e8-82a1-22e15de03880.png)

**Comment by kwsch** [comment]
I think this should be an intended lack of a feature; the Batch Editor allows more control of how the user can edit the data.

Not sure if the party data has slot numbers, but the user could include `!Slot=1` to exclude the first party slot if you're deleting the party or making them all eggs.

If you don't want to modify the party, you'd need to `!Box=-1` (iirc, since box is not set and is defaulted to -1; all box slots have a >0 value).

**Comment by sora10pls** [comment]
The following commands as you mentioned only modify Slot 1 of every Box; the entire Party is still modified:
```
!Slot=1
.IsEgg=true
```

I do think that adding another option toggle is the best case scenario, as trying to find out how to tell the Batch Editor what Party was (`Box=-1`) took me a while to figure out ;)
