### ISSUE TITLE
BW2 Glitch

### ISSUE THREAD

**Issue by KofiMatson123** [kwsch/PKHeX#2053]
Whenever Ive edited a new BW2 save file for some reason whenever I open my pc afterwards the "congratulations on becoming champion" prompt appears and some of the game isnt playable due to this. Could you help me. I havent edited any event flags. Could you help please?

**Comment by kwsch** [comment]
Please determine what the underlying issue is first.

* Restore backup prior to edits, confirm that the game behaves properly
* Edit the backup to reproduce the ingame misbehavior
* Find precisely what edits reproduce the ingame behavior (most minimal changes made)
* Upload a before/after of the save files so a bytewise diff can be determined & ingame behavior reproduced by other users.

Then we'll be able to determine if it's PKHeX and what the solution/fix would be.
