### ISSUE TITLE
Mouseover tooltip displays wrong Hidden Power type in SAV2

### ISSUE THREAD

**Issue by SadisticMystic** [kwsch/PKHeX#2055]
As you can see, the left pane shows that E79E corresponds to Electric, but the hover text is claiming Poison, as though it were trying to apply the 3-7 Hidden Power formula to a 6/14/7/14/14/9 spread. Even before I peeked into the raw values on this save, I knew that Electric was definitely the right type.
![maghp](https://user-images.githubusercontent.com/12500361/42619018-53f64d0c-85a6-11e8-89e5-eb25000a9319.png)

**Comment by kwsch** [comment]
Hover details use ShowdownSet for generating the text via `GetText()`, which calls the following:

https://github.com/kwsch/PKHeX/blob/d20706dd706e277c5c73ec359b35fbbfcf4b6c04/PKHeX.Core/Editing/ShowdownSet.cs#L223-L232

Would need to update `HiddenPower.cs` to accept a generation-format int, and branch to a gen1/2 hidden power type calc instead.

Additionally, I think importing a gen1/2 hidden power set doesn't work correctly. May have to set a "hidden power import format" static int so that the text->ShowdownSet uses the correct correlation.

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/PKHeX/commit/ea5a981f4a9de413af9494624de8d01f4199427a :)
