### ISSUE TITLE
Basculin flags as illegal

### ISSUE THREAD

**Issue by XxPhoenix1996xX** [kwsch/PKHeX#2058]
Not sure what's going on but this Basculing flags as illegal, then cheking it's legallity report flags as legal. The PKM is legit.
![1](https://user-images.githubusercontent.com/40975656/42731381-01bc46be-87da-11e8-91d5-f59ab580c925.png)
[Basculin - Pokemon - Black Version.zip](https://github.com/kwsch/PKHeX/files/2195527/Basculin.-.Pokemon.-.Black.Version.zip)

**Comment by kwsch** [comment]
Hold control before right clicking the slot, it'll allow you to check legality without loading to tabs.
(loading to tabs and checking legality will cause the pkm editor to resave the pkm with misc fixes)

```
Invalid: Ability is not valid for species/form.
===

Valid Move 1: Learned by Level-up.
Valid Move 2: Learned by Level-up.
Valid Move 3: Learned by Level-up.
Valid Move 4: Learned by Level-up.

Valid: Valid Wild Encounter at location.
Valid: Nickname matches species name.
Valid: Current level is not below met level.
Valid: All ribbons accounted for.
Valid: Correct ball for encounter type.
Valid: Form is Valid.
Valid: Gender matches PID.
Valid: Encounter Type matches encounter.
===

Encounter Type: Wild Encounter Surf (Basculin)
Location: Dragonspiral Tower
PID Type: None
```

**Comment by kwsch** [comment]
The Basculin-Blue has the ability `Reckless`, which is only obtainable by the Basculin-Red forme.

**Comment by SnorlaxMonster** [comment]
Reviving this old issue because it appears to still be a problem in 2026.

> The Basculin-Blue has the ability Reckless, which is only obtainable by the Basculin-Red forme.

Blue-Striped Basculin's Abilities are a mess in Gen 5.
* In Pokémon Black and White, Blue-Striped Basculin has Reckless as its Ability (instead of Rock Head). However, there is an in-game trade Blue-Striped Basculin in White that has Rock Head.
* In Pokémon Black 2 and White 2, wild Blue-Striped Basculin have Rock Head, but bred Blue-Striped Basculin have Reckless.
* When transferred to Pokémon Bank, any Blue-Striped Basculin with Reckless have their Ability changed to Rock Head.

PKHeX seems to be just treating Rock Head as Blue-Striped Basculin's ability throughout all of Gen 5, so any Blue-Striped Basculin with Reckless is incorrectly considered illegal.
