### ISSUE TITLE
[Bug] Legality flagging Event Pokémon 

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#2067]
If a save file is opened with file association towards PKHeX, any Event Pokémon, regardless of its legality, will be flagged as illegal. Checking its legality straight from the Box slot, or even after Viewing the PKM will show that it is indeed legal.

Pic attached proves that I'm checking the full legality report from the Box slot rather than after Viewing, to ensure PKHeX doesn't do any quick fixes for legality purposes.

This is another working directory related bug (see Issue #1943), as this does not happen when a save file is opened via File -> Open or drag/drop.

![image](https://user-images.githubusercontent.com/17801814/43047849-c6277132-8dab-11e8-80c4-a7cc939774a9.png)

**Comment by kwsch** [comment]
Race condition issue due to the MGDB not being completely loaded before a save file is loaded & parsed. Having a mgdb folder with tons of files inverts the startup finishing order, causing MGDB-Init-Time >>> Form-Init-Time.

**Mitigations:**
- Delay form from continuing via Main.cs if not initialized when loading the first file
- Delay form form from continuing via mgdb-plugin if not initialized when loading the first file
- Remove duplicate files already present in the internal database

Best resolved by the plugin/user; /mgdb/ is intended to be a limited amount files rather than a complete copy. I'll work with @architdate on a solution for the mgdb-plugin since that's the aggressor here :)
