### ISSUE TITLE
G1G2  Not Japanese --> Japanese

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2074]
![12345](https://user-images.githubusercontent.com/39662364/43123392-998dfa04-8f56-11e8-852d-063fff0afe78.png)
↓
↓
↓
![123456](https://user-images.githubusercontent.com/39662364/43123416-adac233a-8f56-11e8-98ab-3a95152b3b90.png)

That’s right

But ...

![1234567](https://user-images.githubusercontent.com/39662364/43123471-ddac01a4-8f56-11e8-9926-b918d93d7885.png)
↓
↓
↓
![12345678](https://user-images.githubusercontent.com/39662364/43123508-f2c2f520-8f56-11e8-9eed-36ef1bfd4750.png)

Why not error? (fix it - the following error will not happen)

Then

![123456789](https://user-images.githubusercontent.com/39662364/43123577-2f22c2fc-8f57-11e8-809a-36a20306cd46.png)

And ...

![1234567890](https://user-images.githubusercontent.com/39662364/43123609-49f730b8-8f57-11e8-84f7-3ba2c2fdfd36.png)

(Before trade)
![0](https://user-images.githubusercontent.com/39662364/43123678-8c861ebc-8f57-11e8-8517-61189d97d3ed.png)

**Comment by kwsch** [comment]
```
ipk1 = international pk1
jpk1 = japanese pk1
```
Due to string buffer length differences, `ipk1.Data.Length > jpk1.Data.Length`. By moving bulba ipk1 -> japanese save, the written data overflows into the next slot, 'corrupting' the data. The `Species` property is one of the first properties in the jpk1 structure, thus the overflow modified it to another species.

Just need to update the sanity checks for non-PKMEditor IO I guess...
