### ISSUE TITLE
Hyper Training getting stripped

### ISSUE THREAD

**Issue by Lusamine** [kwsch/PKHeX#2090]
Certain Pokemon appear to be losing their Hyper Training flags when exported as a pk7 or dropped into the left tabs.  For example:

This is a gen 3 Clefable showing the HT vanishing by dragging.
![ht issue](https://user-images.githubusercontent.com/30205550/44064906-5403e4a8-9f2d-11e8-8f1e-fd66723a75b3.gif)

Exported files of the HT'd Clefable have no HT when re-imported.  However, those same files do show up with HT when loaded into Porybox:
https://www.porybox.com/#/pokemon/b028c60f8f10a084e03ddea951eb172f

I have a separate save file with a Landorus that is similarly affected.  It also seems to lose some extra bytes and gain a blue star marking when dragged into the tab.
![lando](https://user-images.githubusercontent.com/30205550/44064889-36bbfed0-9f2d-11e8-8d57-635d3f123623.gif)

I can share the save files if needed but prefer not to upload them publicly.

**Comment by kwsch** [comment]
This is due to PKHeX checking if it is possible to interpret the dragged file as a pk6 (not trusting the specified file extension) and then converting the valid-pk6 to a pk7.

https://github.com/kwsch/PKHeX/blob/61013b8f1878cfb267f5ffe3ffda841be1db8fd0/PKHeX.Core/PKM/PK7.cs#L353

https://github.com/kwsch/PKHeX/blob/61013b8f1878cfb267f5ffe3ffda841be1db8fd0/PKHeX.Core/PKM/PK6.cs#L328

PK6 / PK7 Differentiation

https://github.com/kwsch/PKHeX/blob/61013b8f1878cfb267f5ffe3ffda841be1db8fd0/PKHeX.Core/PKM/Util/PKMConverter.cs#L123-L178

Might have to look into ways to better differentiate for ambiguous cases.
