### ISSUE TITLE
suggestion on sorting by legality

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2125]
Hey I wanted to know if it would be possible to change the sort by legality filter to first sort by pokedex number and form, then by legality, that way when you sort by legality, all of the pokemon stay in the same position but the illegal pokemon all get moved to the end of your pc. Currently they just sort randomly (as far as I can tell) and then the illegal pokemon are moved to the end. Thanks again

**Comment by kwsch** [comment]
Sorting isn't random, it's based on how they are originally sorted.

Sort by dex, then sort by legality to get the desired results.

**Comment by NinFanBoyFTW** [comment]
But that isnt how its sorted whenever I do it, I already have all my pokemon in pokedex order. I sorted it again just to be safe and then sorted by legality, and it changed the order of most of the pokemon in the pc when only 3 pokemon were illegal.

**Comment by kwsch** [comment]
Not able to replicate behavior with other similar advanced sorting options:
![image](https://user-images.githubusercontent.com/6393368/45731336-e44e8700-bb8b-11e8-8430-b570df55819c.png)

Interesting how this one misbehaves when it should just be sorting based on the boolean 'valid', and shouldn't reset the order.

The ordering isn't random, it's consistently {something}; reason why I don't know.

**Comment by kwsch** [comment]
`FinalSortBy` sorts by AltForm, then Gender, then Nicknamed at the end. The 'resets' are due to different form/gender/nickname boundaries.

Several solutions exist:
- Add sort by species in the final sort
- Add a sort by species for boolean custom sorts
- Add a call to the previous sort method before the final sort
- Remove final sorting for bool sorts to preserve the original order
- Add a fancy sorting-order-builder (no thanks)

Will think about it for a while ;)

**Comment by NinFanBoyFTW** [comment]
I'm sure you don't need my input but having it preserve the original sorting sounds the best. There are tons of people with saves where they just want to have the illegal Pokemon go to the back and leave their custom sorting alone. Plus like you said on the first comment, if someone wants to sort by species they can just do that first.
