### ISSUE TITLE
Not sure if this is an issue, but I have a question

### ISSUE THREAD

**Issue by StarProgamGamer** [kwsch/PKHeX#2207]
Is it possible to make PKHeX run from pk7/usum in the current versions on startup?

**Comment by kwsch** [comment]
If a save file is not detected on startup, it loads a default blank save file (which is hardcoded to GP & pb7).

https://github.com/kwsch/PKHeX/blob/fc65a65fd95c890164bcddbe48550ec8b29c3672/PKHeX.WinForms/Controls/SAV%20Editor/SAVEditor.cs#L70-L72

https://github.com/kwsch/PKHeX/blob/fc65a65fd95c890164bcddbe48550ec8b29c3672/PKHeX.WinForms/Controls/PKM%20Editor/PKMEditor.cs#L16-L19

PKHeX has always been set up so that the most recently released game is the default save file. There are multiple places that provide downloads for blank/complete save files for supported games. If a different default save is wanted:

* change the above lines to load the desired save version & pkm format
* load a save file on startup (ctrl-F)
* spoof a permanent autodetect folder on one of your hard drives with the desired save file

Having a persistent save file setting would require a bit of reconfiguration as things aren't set up nicely for that.

Related:
https://github.com/kwsch/PKHeX/issues/2180
https://github.com/kwsch/PKHeX/issues/486
