### ISSUE TITLE
Help again

### ISSUE THREAD

**Issue by StarProgamGamer** [kwsch/PKHeX#2209]
Originally https://github.com/kwsch/PKHeX/issues/2208
It isn't about wonder trade, it's about the legality of the pokemon in general. And if that's not the place it's coded in PKMN-NTR do you know where it is?

**Comment by kwsch** [comment]
PKMN-NTR uses PKHeX.Core.dll as a code reference to provide legality checking and pkm operations. PKHeX.Core has been updated numerous times in the past few months, so it is assumed that the copy in PKMN-NTR is outdated. Take the latest dll from PKHeX's download and use it in the other program. If there are errors, then they'd have to be fixed in PKMN-NTR.

Please keep issue discussion for other tools in their appropriate repositories :)
