### ISSUE TITLE
RBY Inventory Editor Bug

### ISSUE THREAD

**Issue by Wanderer1391** [kwsch/PKHeX#2266]
Selecting Save in the Inventory Editor of a Gen 1 Save regardless of whether anything was edited or not will set the count of all items to 1.

**Comment by kwsch** [comment]
Traced back to a commit 2y ago, which gradually migrated into a 'sanity check' for counts:
https://github.com/kwsch/PKHeX/commit/9e24a3a26ca4149e4c270e6619b1c126cb39b09c

```csharp
if (197 >= item && item <= 201)
    c = 1;
```

See the problem here?
Rewritten:
```csharp
if (item <= 197 && item <= 201)
```
The comparison of 197 should be flipped the other way around (197 <= x <= 201); it currently forces everything below 202 to be 1, and doesn't modify TM counts.
