### ISSUE TITLE
PKHeX not setting gen7->gen7 friendship correctly

### ISSUE THREAD

**Issue by pokelector** [kwsch/PKHeX#2269]
PKHeX is having friendship transfer issues. 

These are Gen7->Gen7 transfers from 1 gen 7 file to another in PKHeX.

Scenario 1
File A: A Mimikyu I bred. Had friendship 120. Let's call that the OT Friendship.
File B: Transferred File A's Mimikyu. I expected the CT (Current Trainer)'s friendship to be 70 (base value of Mimikyu, because in a Link Trade the friendship is reset to base value). The OT friendship was still transferred correctly. Normally in a Link Trade it would end up CT/OT 70/120, but instead with PKHeX it became 0/120. 

Scenario 2
File A: An Alolan Vulpix I bred. Had friendship 120 Let's call that the OT Friendship.
File B: Transferred File A's Vulpix, evolved, and gave friendship, so now it has 204 friendship. CT/OT 204/120. Transferring back to File A changes back to 120/120 as expected. 
File C: Transferred File A's Vulpix to File B and then to File C. CT/OT friendship was still 204/120. Even though File B gained friendship, transferring to File C should've reset it to base again since File C was not the OT.

It seems that PKHeX is not following the link trade laws for friendship in PKHeX. I am knowing that PKHeX transferring in the same gen is meant to synthesize a link trade, and this is not how it is meant to be done. Unless I'm missing something?

**Comment by kwsch** [comment]
PKHeX ignores trade-friendship update values in favor of retaining current friendship values. 

Things that use the current handler friendship value:
* Moves like Return and Frustration
* PB7 calculated CP
* Misc in-game interactions

PKHeX selectively updates `HT_Friendship` assuming the not-OT handler details changed AND the **HT_Name** changed. This is to try and preserve user entered values.
https://github.com/kwsch/PKHeX/blob/52dd2d67018f5d2ed282f3e9161ce73d00bdcc5c/PKHeX.Core/PKM/PK7.cs#L484-L488

The main PKM editor sets the HT_Name property if you entered in data for that:
https://github.com/kwsch/PKHeX/blob/cb98c83bd2bd47f90f6fd4c3c95c4149aa20647a/PKHeX.WinForms/Controls/PKM%20Editor/LoadSave.cs#L328-L332

Since you have entered in data, when the PKM is set to the save file, the HT_Name matched the destination savefile, thus the HT_Friendship was not updated.

Summary:
HT_Friendship only refreshes to BaseFriendship (not 70) if the HT_Name changes. This is to preserve any user-edit values from being overwritten automatically.

**Comment by pokelector** [comment]
So this is techincally correct? I feel this is messing with the legality of the Pokemon, since it's not doing what the game does.

**Comment by pokelector** [comment]
My two different files have same HT_name, different IDs. 

Take scenario 2. Can you explain?

**Comment by kwsch** [comment]
> Scenario 2
> File A: An Alolan Vulpix I bred. Had friendship 120 Let's call that the OT Friendship.
> File B: Transferred File A's Vulpix, evolved, and gave friendship, so now it has 204 friendship. CT/OT 204/120. Transferring back to File A changes back to 120/120 as expected.
> File C: Transferred File A's Vulpix to File B and then to File C. CT/OT friendship was still 204/120. Even though File B gained friendship, transferring to File C should've reset it to base again since File C was not the OT.

1. 120 friendship hatched, OT=120, HT=0. Traded to B, gets reset to 70 (base friendship) since it gets a new HT name.
2. Evolved, now has OT=120, HT=204. Trading to A still yields OT=120, HT=204, since no trainer data changed.
3. Trading to File C has the same HT name, so PKHeX elects to not reset the HT friendship. End result: OT=120, HT=204.

**Comment by pokelector** [comment]
I understand. Thanks for replying.

**Comment by kwsch** [comment]
Correct; however, depending on who is the current handler (OT vs HT), only one value of the two is shown in the GUI.

**Comment by pokelector** [comment]
What I mean is, in my scenario File 2 has same HT name. 

So is it only OT friendship and HT friendship for ALL HTs that arent OT? Meaning HT friendship is the same for all HTs except for OT?

**Comment by kwsch** [comment]
Pokémon 'remember' their original trainer's friendship/affection/memories, as well as remember things for their last handler trainer.

The OT details are separate from the HT details.

HT->a new HT does not modify OT details. Only HT details.

**Comment by pokelector** [comment]
What I mean is
HT to new HT doesnt modify in my case. Is that because of the same name?

**Comment by kwsch** [comment]
Correct. As previously stated, pkhex chooses to not reset the data if the name is the same.
