### ISSUE TITLE
Kirk's Shuckle invalid HGSS

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#2290]
![image](https://user-images.githubusercontent.com/12572974/56911338-b9f66d80-6a7a-11e9-9f05-a889e6e092ea.png)

**Comment by kwsch** [comment]
Theres two different Shuckie's, as far as I know.
https://projectpokemon.org/home/files/file/3048-kirks-shuckie/

Please compare what you have to the site gallery copies.

**Comment by Ninjistix** [comment]
[213 - Shuckie - DFD2000214D7.zip](https://github.com/kwsch/PKHeX/files/3129935/213.-.Shuckie.-.DFD2000214D7.zip)
this is the one I received, not sure if its because i'm playing on an emulator.

**Comment by CanoeHope** [comment]
I'm siding with the OP on this and saying that I also have the exact same Relaxed Shuckle obtained on my SS back in 2010, played on the DS itself. I've also just tested it playing SS on an emulator, and it resulted in the same one.

I think that guy did something wrong like used a modified ROM or improper emulation, because even Serebii says it's Relaxed Nature, too: https://www.serebii.net/heartgoldsoulsilver/gift.shtml

[213 - Shuckie - CACD000214D7.zip](https://github.com/kwsch/PKHeX/files/3132770/213.-.Shuckie.-.CACD000214D7.zip)
