### ISSUE TITLE
G5 --> G6 Trade Ability

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2326]
![image](https://user-images.githubusercontent.com/39662364/59545303-25bf6780-8f4f-11e9-80a5-1f437228fde2.png)
in G5 sav,this Kakuna's AbilityNumber is 2
but
load in G6 sav
![image](https://user-images.githubusercontent.com/39662364/59545347-96668400-8f4f-11e9-8766-89475717d67c.png)

so,
if Ability1 = Ability2
AbilityNumber must be 1?

**Comment by kwsch** [comment]
In gen3-5, the "Ability Number" is just cosmetic.

When transferred to Gen6, it determines what ability number it is; since they are the same abilities, its search yields the first ability, resulting in (1).

https://github.com/kwsch/PKHeX/blob/14138121a9a34b1a74f8d4e484ac68152386ef35/PKHeX.Core/PKM/PK5.cs#L329-L341
