### ISSUE TITLE
Invalid Met information in Gens 3/4

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#233]
These are the save files of a few randomizers I did a long while ago.

1. Pokemon caught in "Great Marsh" from Platinum shows "Geosenge Town" from X/Y
2. Pokemon obtained as starter in HG/SS shows "Laverre Gate" from X/Y
3. Pokemon caught in "Union Cave" from HG/SS shows "Route 104" from R/S/E (or maybe even OR/AS)
4. ~~Egg hatched in Emerald was Level 5 in game, but PKHeX claims the Met Level is 0~~ an explanation was provided by @javierhimura 

Not sure if the issue persists in Gen 5, but I can check and comment back here if I manage to find another save file of mine.

![screenshot_1](https://cloud.githubusercontent.com/assets/17801814/18257409/40002d46-7391-11e6-8f95-eb71b11a6bcf.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/17801814/18257408/3ffcdbf0-7391-11e6-9d68-912d9534c061.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/17801814/18257410/400035ca-7391-11e6-884a-b673636907c2.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/17801814/18257411/4001700c-7391-11e6-8c9f-211cc3d15723.png)

**Comment by javierhimura** [comment]
In gen 3 any pokemon hatched from an egg have meet level as 0, that is how the game knows the pokemon was obtained from an egg and not captured at level 5, because in gen 3 there is no exclusive data for eggs pokemon to determine it was an egg (egg location and egg hatched data does not exits until gen 4). Is correct to show meet level 0

**Comment by sora10pls** [comment]
Did not know that, thanks! Although the other three bugs still stand
