### ISSUE TITLE
Reproducible Encounter Database crash

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#2336]
Depending on the ID numbers on the loaded save file, attempting to generate forced shiny encounters through the Encounter Database crashes PKHeX very quickly.

For some reason, it crashes when IDs with TSV of 0605 are on the save file (that I know of, chances are it crashes for more different numbers, but I can't feasibly try them all.) If I change the IDs to anything else then it works, but then it's pointless, because it won't be shiny for the ID numbers that I want it to be shiny for.

https://gfycat.com/uniformanimateddogwoodclubgall

Applies to Dratini, Gible, and Haxorus. Doesn't apply to Red Gyarados, I assume because its method of generation is different from Gen. V 'mons.

(Speaking of Haxorus, it can definitely have Mold Breaker as its ability, and not just Rivalry, but the ones from the Encounter Database always have Rivalry.)

**Comment by kwsch** [comment]
Infinite loop on Gen5 shiny mystery gifts, fun.
Brief inspection looks like it picks a nature to give the mon and requires PID%25 to match the nature.

Since PID determines shininess and the example shiny value TID/SID doesn't yield valid PIDs with that nature, it gets stuck. Probably need to revise something so that it doesn't do the silly %25 check.
