### ISSUE TITLE
Encounter type detection issue

### ISSUE THREAD

**Issue by Ammako** [kwsch/PKHeX#2389]
![image](https://i.imgur.com/waqbKlF.png)

Left is dc10c05, right is 734aa33.

[015 - Beedrill - 2F3A638FD1B9.zip](https://github.com/kwsch/PKHeX/files/3632139/015.-.Beedrill.-.2F3A638FD1B9.zip)

**Comment by fattard** [comment]
Sorry to comment a closed issue, but it's not fully fixed yet, @kwsch .
My AlphaSapphire save file has most boxed mons marked as invalid due to Encounter detection. All of them were legally caught in-game.
![image](https://user-images.githubusercontent.com/1159052/65296476-f7978800-db3a-11e9-92a3-300df71845e3.png)
![image](https://user-images.githubusercontent.com/1159052/65296543-2f063480-db3b-11e9-9516-d19071c80ee4.png)

I tested both Sep 19 release and the latest commit https://github.com/kwsch/PKHeX/commit/7e70d836649c903189072be215684c5697cda6c2

Please, use attached file as test, but you can check the issue with any save you have for ORAS.
[263 - Zigzagoon - 2746E8288E7E.zip](https://github.com/kwsch/PKHeX/files/3634060/263.-.Zigzagoon.-.2746E8288E7E.zip)

I tested other version saves, but it seems only Gen6 ORAS saves were affected, XY saves are good.
Demo games (both ORAS Demo and SM Demo) are also showing invalid issues too, but it might be a completely unrelated problem.

**Comment by kwsch** [comment]
ORASDemo/SMDemo encounters aren't supported for legality checking; not really worth :)
