### ISSUE TITLE
G3 Milotic Beauty

### ISSUE THREAD

**Issue by iiippppk** [kwsch/PKHeX#2394]
![image](https://user-images.githubusercontent.com/39662364/65747445-05996a00-e134-11e9-93de-3e0f4ce3a3da.png)
My Sapphire Milotic (Wild)
Evolved in G5 (Prism Scale)
![image](https://user-images.githubusercontent.com/39662364/65747583-62952000-e134-11e9-9dc9-9d48874a79fa.png)
Beauty is 0

now, in G6 Games
Increase the value of Beauty
Invalid?

![image](https://user-images.githubusercontent.com/39662364/65747783-eb13c080-e134-11e9-8123-62df72ac9f4d.png)
![image](https://user-images.githubusercontent.com/39662364/65747843-14cce780-e135-11e9-8082-14d2554d304f.png)

[350 - Milobellus - 2CFF3D0BA012.zip](https://github.com/kwsch/PKHeX/files/3661224/350.-.Milobellus.-.2CFF3D0BA012.zip)

**Comment by kwsch** [comment]
Nice find, this is due to the evolution chain verifier returning the first possible evolution chain rather than the most permissible.

1. evolve beauty (level up)
2. evolve prism scale (trade)

I'll have to see if there are any evolution chains where [lower index evolution method] requires levelup while later ones do not. Hopefully just Feebas/Milotic :) :)

**Comment by kwsch** [comment]
List of evolution tables that have an evolution with levelup before another without levelup:
```
Evolves1	
Evolves2	Slowpoke
Evolves3	Slowpoke
Evolves4	Slowpoke, Eevee, Kirlia,       , Snorunt
Evolves5	Slowpoke, Eevee, Kirlia, Feebas, Snorunt
Evolves6	Slowpoke, Eevee, Kirlia, Feebas,
Evolves7	Slowpoke, Eevee, Kirlia, Feebas, Snorunt
Evolves7b	                 Kirlia, Feebas, Snorunt
```

Of the above, only Feebas is of concern, because the other cases evolve to different species.

So we only have to worry about Feebas... I'll think of something:

* swap the two entries after init, 
* swap the two entries in the resource file
* rewrite the logic to do deferrals (just for this single species, NOPE)

**Comment by kwsch** [comment]
Byte sequence after swapped (method, arg, species, form_lvl): 
```
06 00 19 02 5E 01 FF 00 
10 00 AA 00 5E 01 FF 00
```

(similar for the 8byte sequence for gen6+)
