### ISSUE TITLE
[LGPE] Sorting "met date" in game

### ISSUE THREAD

**Issue by steph9009** [kwsch/PKHeX#2400]
Every Pokémon injected (created, not modified) is shown even **before*** the first met Pokémon (starter), even if met date is occuring later than it (e.g.: in LGP, Pika is shown after injected Mewtwo/Mew/Chansey and every injected static Pokémons/NPC link trades).

*This happens only if sorting them in-game, while on PkHeX sorted Mons which have same met date seem to be shown random and Mons which have following met date are correctly shown after the starter.

Sorting met date in game:
![2019101114315900-94CAAF6C83EE682D358EB6183EEF7D28](https://user-images.githubusercontent.com/33696098/66651669-e9b5be00-ec33-11e9-9211-c58370176387.jpg)
(Every Mons before Pikachu is injected from PkHeX)

Same met date on PkHeX:
![image](https://user-images.githubusercontent.com/33696098/66651566-a5c2b900-ec33-11e9-8f90-9c913435a257.png)
(Every Mons which has same met date is ordered in random Box Slot)

**Comment by kwsch** [comment]
The game likely stores metadata outside of the box in order to sort without decrypting the pkm data. Since injected data isn't added to that record, it likely has a default value (0) causing it to be first. It's likely a 64bit timestamp, which allows more accurate sorting.

PKHeX sorts by met date, and doesn't sort things further.
