### ISSUE TITLE
You can't trade Pokémon because there is a problem with your Pokémon.

### ISSUE THREAD

**Issue by BetaLeaf** [kwsch/PKHeX#2528]
**Describe the problem**
When trading this pokemon, the game says there is a problem with it and cannot be traded. PKHeX says it is legal. Using latest release.

**To Reproduce**
[880 - Dracozolt - 587E4CD66CB7.zip](https://github.com/kwsch/PKHeX/files/3894360/880.-.Dracozolt.-.587E4CD66CB7.zip)

**Expected behavior**
Pokemon should trade.

**Screenshots**
![20191126_180716](https://user-images.githubusercontent.com/7028351/69680037-b9a56b80-1077-11ea-826a-4041212661c6.jpg)

**Comment by deadair3210** [comment]
Why does it say dracozolt but show a bonsly in the screenshot

**Comment by Bappsack** [comment]
@deadair3210  because the Trade Partner wanted to trade him a Bonsly.

maybe the Zap Plate isn't released yet? try to trade it without Zap Plate.

**Comment by kwsch** [comment]
https://www.serebii.net/swordshield/items.shtml

Zap Plate is not listed.

https://github.com/kwsch/PKHeX/blob/9cb56be3dde07e7521121f5d17bba8af31f08e87/PKHeX.Core/Legality/Tables/Tables8.cs#L377-L387

Hasn't been filled out yet ;)

**Comment by Bappsack** [comment]
https://github.com/kwsch/PKHeX/pull/2529

**Comment by JuicyBerger** [comment]
I was also having the same problem. PKHEX was showing that the pokemon was Legal and good to go. I intended to trade a level 90 Gengar with no held items, but in game it would say "You can't trade Pokémon because there is a problem with your Pokémon." 
I Then changed the Level of the Gengar to Level 80 and mysteriously the trade went through!
**Perhaps changing the level to 80 might fix your issue as well.** 
I Discovered this within Pokemon Brilliant Diamond.
