### ISSUE TITLE
Pokemon Feelings Offset by 1.

### ISSUE THREAD

**Issue by crzyc** [kwsch/PKHeX#2549]
When viewing pokemon memories in PKHeX, I get this:
<img width="579" alt="error1" src="https://user-images.githubusercontent.com/18177787/69916759-11075b00-142d-11ea-993b-25caa1cc8939.PNG">

However, in-game, the feeling is this: 
![20191201_112454](https://user-images.githubusercontent.com/18177787/69916831-a30f6380-142d-11ea-89ee-612dc6573f65.jpg)

This applies to everyone in my party.

How to replicate:
1) Set feelings in PKHeX.
2) Check Sw/Sh's memory reader.
3) Confirm Feelings.

**Comment by SilverCam** [comment]
So, I'm having a slight issue regarding the memories also. It seems as though the memories are being overwritten when being Link Traded, despite me changing them in the editor. Is this intended or a bug? 

Example: I trade my Eternatus to Switch2 and upload it to PKHex, edit the memories to say "Eternatus became good friends with the  in a Box, practiced moves with it, and talked about the day that Eternatus would be praised by Cam. The Pokémon remembers that it was happy."

When trading that Pokemon back to Switch1, that memory auto changes back to "Eternatus became Cam's friend when it came through Link Trade in a Pokemon Center. The Pokemon remembers that it got lighthearted." It'll say that for both instances, the OT, and the previous owner(Switch2).

Is there a way to make the memory stick so that it will say what I want it to? When trading back to Switch1, that is. Not sure if it is a bug or not. I'm not changing the Trainer ID or SID, and the Pokemon is identified as mine still(Switch1).

**Comment by kwsch** [comment]
@SilverCam PKHeX doesn't change memories. We're aware of the game bug where it applies to the wrong trainer memory spot.

**Comment by SilverCam** [comment]
@kwsch Ah, okay. So the memory edit won't work with what I'm trying to accomplish? Or will it work in a future update(PkHeX)?
