### ISSUE TITLE
Corviknight from North Lake Miloch showing as illegal

### ISSUE THREAD

**Issue by slp32** [kwsch/PKHeX#2633]
**Describe the problem**
This Corviknight is showing up as illegal, which was caught at North Lake Miloch in the wild area.
[823 - Corviknight - 8CD6A8C081F5.zip](https://github.com/kwsch/PKHeX/files/4055387/823.-.Corviknight.-.8CD6A8C081F5.zip)

**Comment by kwsch** [comment]
There's a multitude of encounters for Corviknight, and I can't determine which of them is the one you encountered since the original level was bumped up to 60.

https://github.com/kwsch/PKHeX/blob/726947eaf536f58088fd26a14c482bf58b27d3ae/PKHeX.Core/Legality/Encounters/Data/Encounters8.cs#L160

https://github.com/kwsch/PKHeX/blob/726947eaf536f58088fd26a14c482bf58b27d3ae/PKHeX.Core/Legality/Encounters/Data/Encounters8.cs#L216

https://github.com/kwsch/PKHeX/blob/726947eaf536f58088fd26a14c482bf58b27d3ae/PKHeX.Core/Legality/Encounters/Data/Encounters8.cs#L224

https://github.com/kwsch/PKHeX/blob/726947eaf536f58088fd26a14c482bf58b27d3ae/PKHeX.Core/Legality/Encounters/Data/Encounters8.cs#L293

**Comment by slp32** [comment]
@kwsch Here is another Pokemon being shown as illegal. Rhydon with the location `near the Giant’s Seat (in a Wild Area)`.
[112 - Rhydon - 546518F59ED6.zip](https://github.com/kwsch/PKHeX/files/4110906/112.-.Rhydon.-.546518F59ED6.zip)

**Comment by kwsch** [comment]
@slp32 same situation as others, there's too many Rhydon encounters to be able to identify which one this is, since the level was bumped up to 60.

**Comment by slp32** [comment]
Sorry about that. I currently have no pre-Eternatus save files, so I'll have to play through the game again to check the encounter.
