### ISSUE TITLE
Add proper SwSh language setting and Battle Tower victories

### ISSUE THREAD

**Issue by CanoeHope** [kwsch/PKHeX#2639]
I personally didn't care about this, but the language in PKHeX currently only reads and doesn't write. So I decided to examine and edit it so it could properly work for the next release for those who would want it. :)

I even found my actual victories that get displayed for each Battle Tower format at the tower itself.

**Block Key 0BFDEBA1**

0x00 = Language ID

**Block Key 436CAF2B and 6226F5AD**

0x00 = Battle Tower Singles victories

**Block Key 5F74FCEE and 0D477836**

0x00 = Battle Tower Doubles victories

**Comment by kwsch** [comment]
I suspect that the two blocks for Battle Tower (pair) are instead Current Streak / Best Streak, similar to past games.

Sad how it's a separate block for arbitrary value storage. Feels like we're back in Gen3.

**Comment by CanoeHope** [comment]
I tested that the numbers in Blocks 436CAF2B and 0D477836 cap at 9,999,999, and the other 2 appear to at 65535. Just thought I'd point that out.

**Comment by kwsch** [comment]
With the previous two commits, I've increased the verbosity related to viewing block information.
https://github.com/kwsch/PKHeX/commit/a590d3713bf5ef65b0edbc01fe21fea928871f40
https://github.com/kwsch/PKHeX/commit/c1428107f96710d6ff2aef31b0e51a64120a458e

The two 9,999,999 blocks are listed as uint blocks (4 bytes), the other two are ushort (2 bytes). Maybe instead of Best/Current, it's just Streak/Total Wins? Otherwise, idk why one is allowed to go above `2^16-1` :)

**Comment by CanoeHope** [comment]
I'm assuming 6226F5AD and 5F74FCEE are blocks you share with others or used when accessing Battle Stadium, because I just lost a battle then won the next and it didn't change, 0 out, or anything like that. And yeah, 436CAF2B and 0D477836 are the ones that hold the amount of victories; The game displays a glitchy number if you go above 9,999,999 btw.

Thought I'd also mention that Rally score caps at 99,999 in game while the latest PKHeX commits allow inputting 999,999.
