### ISSUE TITLE
Charmander family gives incorrect legality report for "Dragon Rage"

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#2673]
**Describe the problem**
These lines are generated by the report for a Charmeleon in generation 3 with Dragon Rage: 
![image](https://user-images.githubusercontent.com/29823718/73598075-8cef5380-4501-11ea-817b-2582ff50e5fa.png)

The report assumes that the Charmeleon was hatched from an egg, although it's not clearly communicated to the user that this is its assumption. This threw me off because I didn't know where to start looking. Dragon Rage is not an egg move (Charmeleon learns it at level 48, which this one is below), but upon removing Dragon Rage, the Charmeleon is considered legal.

**To Reproduce**
Here is the Charmander family in question:
[Save Files.zip](https://github.com/kwsch/PKHeX/files/4143167/Save.Files.zip)

They are all based on the same Charmander, except the Charmeleon has Dragon Rage which is not yet possible at its level. Giving and removing Dragon Rage will give the confusing report.

**Expected behavior**
1: The report should not believe the Charmeleon came from an egg because Dragon Rage is not an egg move for this family in generation 3.
2: In the case of having egg moves on a starter, the type mismatch is correct. However, it should be more clear that it is illegal because of the move in question. For example, my Bulbasaur family has the same report on the Venusaur because the Venusaur has Magical Leaf which is an egg move. I would not have guessed to look in the moves from this report.

**Comment by kwsch** [comment]
The encounter generator does fuzzy checks against different encounters, for formats when there isn't enough data available to know conclusively the type of encounter.

The generator first yielded the static encounter (starter). Since the move Dragon Rage was not obtainable (current level was too low), the generator had to continue onwards looking for another possible match.

The generator then yielded an egg encounter. Since levelup moves can be passed via inheritance, this results in a valid moveset. Even if it wasn't a valid moveset, the generator wouldn't find any other encounters.

The generator then checks the remaining details, using the Egg encounter as a match. For the chosen match encounter, it notices the PID type does not match what is expected for the egg type, then flags it. It also notices the met level isn't what is expected, so it flags it too.

===

The Charmeleon is illegal, regardless of what encounter it is matched to. The legality checks are primarily focused on movesets, not non-battle stats. The legality check is working as intended, flagging an invalid Pokémon. The legality check's goal is to check legality (pass/fail), not find the closest encounter for an invalid Pokémon.

**Comment by Kermalis** [comment]
Thanks for clearing it up, I was under the impression that moves could not be passed down that way.
