### ISSUE TITLE
Adding Battle Frontier Data for Gen 3 Emerald, Gen IV

### ISSUE THREAD

**Issue by ricksee** [kwsch/PKHeX#271]
Is it possible to add a Battle  Frontier tag for Pokemon Emerald + Gen 4 Platinum, HS, and Soul Silver.

**Comment by kwsch** [comment]
It's always possible to edit various features and records, however... it's not possible to implement something without it being thoroughly documented first.

Closed, documentation required. Even if documentation were available, it's not a high-attention / high-use feature, hence why these small scale editors are best suited for Pull Requests instead of Feature Requests.
