### ISSUE TITLE
Pokétch incorrectly unlocking in early gen 4 saves

### ISSUE THREAD

**Issue by Glazelf** [kwsch/PKHeX#2715]
**Is your feature request related to a problem? Please describe.**
In Diamond, Pearl and Platinum, if you edit your save before obtaining the Pokétch, PKHeX incorrectly flags the first Pokétch app as obtained, causing your save to now have the Pokétch. After you obtain it, it seems to correctly load the apps you have unlocked. If you manually unflag all Pokétch apps, the Pokétch will once again dissapear.

**Describe the solution you'd like**
Make it so that PKHeX correctly reads that you don't have the Pokétch yet and doesn't automatically give it to you.

**Additional context**
![Screenshot_118](https://user-images.githubusercontent.com/35176230/74603662-30219a80-50b6-11ea-8558-1dcbd4e836d8.png)

**Comment by kwsch** [comment]
Works fine on latest commits.

The game initializes the poketch when you start the game so that you have the Digital Watch app, but the poketch is disabled via another flag.

https://github.com/kwsch/PKHeX/blob/eb01591861b704477b7b0937d5c5116c8c78d980/PKHeX.Core/Saves/SAV4Sinnoh.cs#L59-L111

I checked with a blank save, and the "Enabled" boolean (not exposed for editing) is not changed when manipulating that form. A [commit back in October](https://github.com/kwsch/PKHeX/commit/a792e58d49e9f712534c3852cc6b2bbf21369baa) had fixed the poketch logic, so double check that you're running the latest.
