### ISSUE TITLE
Pre-Evolution Moves appear as an Unexpected Relearn Move

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#279]
I'm not sure if this is the case for all Pre-Evolution moves; but in the Azumarill line, Pre-Evolution moves such as Sing and Encore are marked as unexpected. 
![help](https://cloud.githubusercontent.com/assets/15519892/18616694/5d4f9e52-7d8e-11e6-976c-b2581a248bb5.jpg)

**Comment by kwsch** [comment]
Marill is one of those tricky ones :)

Azurill's exclusive egg moves are not compatible with Marill's exclusive egg moves.

Aqua Jet is not in Azurill's egg move or learnset, thus PKHeX assumes it was bred without incense directly to Marill. Encore is not in Marill's egg moves, it's in Azurill's. But we know it wasn't ever Azurill because it has Aqua Jet.

**Comment by greenDarkness** [comment]
So basically you can't have both Encore and Aqua Jet? 
Thanks for the explanation by the way. Sorry about the false alarm haha.

**Comment by kwsch** [comment]
Correct :)
