### ISSUE TITLE
Gen 8 legality issues

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2798]
Hey I was just checking my gen 8 save files and I noticed a bunch of things that I wasn't sure about legality wise.

1. all of the pokemon home gifts are still showing up as illegal for me
[Pokemon Home.zip](https://github.com/kwsch/PKHeX/files/4388758/Pokemon.Home.zip)

2. I now havce a bunch of pokemon coming up with a yellow caution symbol (which I assume is fishy legality) but none of these pokemon have been modified, so I guess i'm just wondering if this is a legality issue with PKHeX, or if there is at least a way to turn off these specific yellow caution symbols (I didnt find anything specifically for these in the options). I'll add a few examples here. Again, these pokemon have not been edited at all. 
[Legality question.zip](https://github.com/kwsch/PKHeX/files/4388791/Legality.question.zip)

Thanks again

**Comment by ReignOfComputer** [comment]
1. Not added yet.

2. Migrated move not available in SWSH. It's legal, no worries. You'll get a message in the game when trying to use it IIRC.

**Comment by sora10pls** [comment]
To clarify on your first point, note that the Events Gallery had bad simulated wonder cards which have since been updated (Met Location and Nature locks, to be exact).

The program *does* have them added, but the current wonder cards present in the program are outdated. The next release will properly handle them:
![image](https://user-images.githubusercontent.com/17801814/77678395-798fc000-6f67-11ea-9719-52901dfcaec5.png)
You can put the WC8s from the Events Gallery into your local mgdb until then.

**Comment by sora10pls** [comment]
To clarify on your first point, note that the Events Gallery had bad simulated wonder cards which have since been updated (Met Location and Nature locks, to be exact).

The program *does* have them added, but the current wonder cards present in the program are outdated. The next release will properly handle them:
![image](https://user-images.githubusercontent.com/17801814/77678586-c5db0000-6f67-11ea-8899-32aaf1c13e58.png)
You can put the WC8s from the Events Gallery into your local mgdb until then.
