### ISSUE TITLE
(Request) Bring PokeGen's AR code maker to PKHeX 

### ISSUE THREAD

**Issue by thunderkai** [kwsch/PKHeX#280]
Just as the title states, the only use PokeGen has over PKHeX is AR codes for gen 4 and 5 games and custom C Skins for gen 5, can you bring those features to PKHeX too? :)

**Comment by kwsch** [comment]
C-Gear skins is already implemented but isn't yet ready for release (few glitches to sort out).

AR, GameShark, Gecko (if Colosseum is added), etc. A lot of unnecessary research when save editing is sufficient. If users cannot edit the save file, they can always use the specific tools to make the AR codes. The implementation of code generators (and more importantly, offsets to write to) is not open source, so it'd be a significant time investment.

If anyone wants code generation support, it's best left for a Pull Request with an implementation rather than a request-issue :)

**Comment by thunderkai** [comment]
Ah thank you :)
Just thought you can just port the PokeGen's code generator to PKHeX

**Comment by kwsch** [comment]
PokeGen isn't open source, unfortunately.
