### ISSUE TITLE
Adding player's Nickname for XY

### ISSUE THREAD

**Issue by intocake** [kwsch/PKHeX#283]
How about adding an option to change the nickname your friends/rivals refer to you as in the story. I dug around through PKhex and didn't see an option for that.

**Comment by kwsch** [comment]
Fortunately gen 5 & 6 use Unicode strings so it'd be trivial to find and manually hex edit.

I dislike having unique implementations for every game (makes it more difficult to reuse/maintain code); I haven't yet gotten around to implementing a reflection-heavy UI for trainer editing.

Planned, but not priority since not many people are asking about it ;)

**Comment by intocake** [comment]
Thanks for the answer. I opened it up in a hex editor and found it. So I can just change it that way. Thanks for the help tho.

**Comment by Mrtops** [comment]
On the latest version this feature is available in Pokemon X and Y.

**Comment by kwsch** [comment]
@Mrtops the issue is referring to the nickname, not the name.
http://pokemondb.net/pokebase/164202/is-there-a-way-to-change-your-characters-nickname-pokemon-x-y
