### ISSUE TITLE
PKHeX Sword/Shield Skin Tone Bug

### ISSUE THREAD

**Issue by AlcremieSurprise** [kwsch/PKHeX#2847]
**Describe the bug**
Changing trainer's skin tone results in the character changing to their default or other skin default forms. Followed this [forum post](https://projectpokemon.org/home/forums/topic/56129-changing-skin-tone-with-pkhex/) on what to do in the first place!

**To Reproduce**
1. Open Sword/Shield save file in PKHeX
2. Go to the SAV tab and open Block Data
3. Go to *Object MyStatus in the **Block Key** search bar
4. (**This is changing skin tone from tan to white**) Enter **15683315162178948477** in the "Skin" section to change trainer skin tone
5. (**This is changing skin tone from tan to white**) Enter **66653365124950412** in the "MomSkin" section to change the mother's skin tone
6. Exit the Block Data, Export SAV file, and then Import the SAV on the Switch.

**Expected behavior**
I expected to be able to have a different skin tone and be able to change my clothing/accessories like I was able to before making any save edits.

**Screenshots**
Do not have screenshots, but I do have a video (in case my wording is off or I didn't explain something right!)

https://youtu.be/iYUxuVcd7Kw

In this video, I first go to my League Card to show the original state of my trainer.

I then, finally walk around the overworld to show that I indeed did the following edits to change my character's skin tone (again, following this [forum post](https://projectpokemon.org/home/forums/topic/56129-changing-skin-tone-with-pkhex/)).

Finally, I went to the dressing room to show that I had been wearing different clothes from the default trainer (and different hair/eyes as well)

**I should have been wearing the custom clothes upon starting the game up again (or at least be able to change them again since I reverted back to the default clothing)!**

**Additional context**
Nope, just hoping to look for answers/possible fix. Thank you!

**Comment by kwsch** [comment]
Changing to default is the game rejecting the trainer appearance data.

* Model hash is entered incorrectly (no model found)
* Model hash is not compatible with other model pieces (incompatible)
* Another model hash did not match (fail validate)

Keep in mind that a lot of values are documented & exposed for editing, but they aren't really well documented / known how exactly to edit. Changing models is always screwy as you have to change a lot of things, and people don't really change it enough to know what has to be changed to get it to work.

If you document more details on what has to be changed (eg another block / hash that needs to be labled), I can add it in; otherwise, I am not really interested in investigating why the game doesn't like cosmetic changes.

**Comment by CanoeHope** [comment]
@AlcremieSurprise 
Go to a salon in-game and change your lip color to anything after you made a change. It worked when I did it.

This doesn't need to be done when doing a male character. :)

**Comment by AlcremieSurprise** [comment]
> @AlcremieSurprise
> Go to a salon in-game and change your lip color to anything after you made a skin change in PKHeX. It worked when I did it.
> 
> This doesn't need to be done when doing a male character. :)

@CanoeHope
I'm a bit late to the reply, but thank you for the advice! Worked like a charm!
