### ISSUE TITLE
Ribbon Legality: Master Rank for Zacian, Zamazenta, Eternatus, & other Ineligible Pokemon

### ISSUE THREAD

**Issue by arnotskywalker** [kwsch/PKHeX#2858]
**Description of Problem**
Currently, the 3 legendary pokemon of Galar are marked as "legal" when they have the Master Rank Ribbon. This should not be the case, as each one of them has been barred from ranked play since SWSH's release.

Via the Discord, I have also been informed Mythical pokemon (ex. Pokeball Plus Origin Mew with Galar Mark) as well as others ineligible for ranked battles (ex2 caught outside Galar) are marked legal even with this ribbon.

**Reproduce**
This can be easily reproduced by adding the "Master Rank" ribbon to an ineligible Pokemon (all pokemon caught outside Galar + these 3 legendary pokemon)

**Expected behavior**
Pokemon ineligible to partake in ranked battles should be marked with an X / "illegal" when they have the "Master Rank" ribbon. This would include: all mythical pokemon, pokemon without the galar symbol, and legendaries that have been barred from ranked play since the release of SWSH.

**Screenshot**
![image](https://user-images.githubusercontent.com/66898161/84586313-6feb5b00-ade6-11ea-8035-f7b9527e2eb6.png)

**Comment by Atrius97** [comment]
It should be noted this also applies to any Pokemon that has been banned from Ranked battles since November 15th 2019, not just the 3 Galar Legendaries obtainable in the base game.

For example: Pokeball Plus Origin Mew (SWSH version, not LGPE version), which is legally a Gen 8 origin Pokemon (has Galar Origin Mark), but is also banned from Ranked.
