### ISSUE TITLE
"Bug" with new Pokemon SWSH release

### ISSUE THREAD

**Issue by B1gM1k3** [kwsch/PKHeX#2867]
Probably need an update.

Message "input file is too large" when importing save file in app.

Thanks guys :-)

**Comment by CanoeHope** [comment]
Please wait for the next release.

**Comment by ReignOfComputer** [comment]
Problem lies between keyboard and chair.

**Comment by Arek75** [comment]
While I don't think the author is particularly keen on seeing issues like this (have a look at closed issues - this isn't the fist time this has been reported), the fact that neither the current pkhex release nor (afaik) the current source version supports Pokemon Sword/Shield 1.2.0 saves is, in fact, an issue.

That said, maybe the author wouldn't close these issues if they actually had a good description - something like "When loading save from Pokemon SWSH 1.2.0: Input file too large" - this describes the problem exactly, and is easy to see/find when someone pulls up open issues so that they don't just make yet another issue regarding this problem.

--Arek75

**Comment by architdate** [comment]
It doesnt support it because the author is still working on it. An eta has already been posted on twitter regarding this too https://twitter.com/Kaphotics/status/1274015821145276416
