### ISSUE TITLE
Issue with Poketransfer location

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#2888]
Hey, I was looking at some of my save files, and I noticed that across all generations (past gen 4) if the first pokemon that you view after loading a save, is a pokemon with the location of poketransfer, it ends up showing up as (None) instead and causes the pokemon to be considered illegal. If you reload that pokemon again, it goes back to normal. I don't know if this applied to any other locations yet. Thanks again.

**Comment by kwsch** [comment]
This is a GUI (WinForms) quirk I haven't seen recently, and have no idea how to solve correctly. The program doesn't load the combobox items until it is drawn for the first time, so it waits until you click on the tab or something. Then something prevents the met location from loading to the list. I dunno.

Not really interested in solving it now since it's a rare quirk. Closing, but I won't forget that this exists ;)
