### ISSUE TITLE
Special ball Shedinja

### ISSUE THREAD

**Issue by CesarDominguezO** [kwsch/PKHeX#2914]
**Describe the problem**
Hello, there's currently an issue where if you make a Shedinja that's transfered from Gen 3 in a pokeball other than a regular one, hex will send a "Can't have ball for encounter type" legality error.

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.
[shedinja.zip](https://github.com/kwsch/PKHeX/files/4851454/shedinja.zip)

**Expected behavior**
Be able to have Shedinja in a ball other than a regular (and available in gen 3).

**Screenshots**

**Additional context**
In gen 3, when evolving Shedinja copies the ball Nincada is originally in, which makes it possible to have one in a special ball from this generation.

**Comment by sora10pls** [comment]
Relevant check here: https://github.com/kwsch/PKHeX/blob/808ca8f30782154e1469c828a1a129048fe94b39/PKHeX.Core/Legality/Verifiers/BallVerifier.cs#L39-L47
Reason: PKHeX is reading this encounter as from an Egg, and since Ball inheritance wasn't introduced until Generation 6, Pokémon hatched from Eggs in prior games should always be in Poké Balls. I'm guessing this was evolved from a wild Nincada in a Net Ball, and since the met info changes to Poké Transfer + level of transfer, it messes up determining the encounter type.
