### ISSUE TITLE
Option to directly export a Pokemon to a different generation format

### ISSUE THREAD

**Issue by SNBeast** [kwsch/PKHeX#2928]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

The slight annoyance is that there is no ability to export to a different format, requiring exporting the Pokemon from the original save, then importing it into a blank save and exporting it again.

**Describe the solution you'd like**

My desired solution is that when right-clicking a Pokemon's icon in the top-right, there be options to "Save as Gen _ Pokemon" for available transfer generations.

**Describe alternatives you've considered**

Another possible implementation is, in the save dialog, adding the transferable pk*/ek* options.

**Additional context**

This would be useful for those using another save manager (like PKSM) that can import PK* files, but, like PKSM, don't support certain generations.

**Comment by kwsch** [comment]
Would require too much visual clutter in the UI, in my opinion. Gen3 is particularly nasty; you'd have the following options:

* pk3
* ck3
* xk3
* pk4
* bk4
* pk5
* pk6
* pk7
* pk8

9 options... and what about exporting as encrypted? + 6 more formats, for a total of 15 choices. Would then need to add logic to check if X format is convertable to Y (PKHeX currently tries blindly to convert each step, no metadata), and toggle visibility/enabled states. Then the controls would have to be translated.

I'll recommend the following alternatives, since I'm not interested in the above work needed:
* Bulk: Dump to folder, change blank save to target format-gen, then import folder, and dump again.
* Individual: Drag & Drop to another PKHeX window with the target blank save format, then drag & drop to folder.

**Comment by kwsch** [comment]
Another possible alternative would be to implement an "export mode" toggle which auto-transfers any save-as PKM files to the selected format, if capable. But I'm not sure this is a high-use feature that'd be worth adding -- there's a lot of stale features that nobody has used in months (some editors have bugs surface a year after the bug was introduced).

**Comment by SNBeast** [comment]
Well, since this issue was motivated by lack of GB support in PKSM, what of only Gens I and II supporting this, with only options for exporting to I, II, and VII?

If that's too specific and still faces the translation issue, that's understood.

**Comment by kwsch** [comment]
Might be easier to get PKSM to support importing Gen1/2 pkm files @piepie62 ;)
