### ISSUE TITLE
Gen 1: Save modified in constructor before Verify Checksums

### ISSUE THREAD

**Issue by evandixon** [kwsch/PKHeX#294]
I was recently PM'd about the "Verify Checksums" button still not working, even after commit c8f14fbd3d336f5c1fe68135d69c5d43b530ea48.  Looking further into it, the "Verify Checksums" feature appears to work correctly.  The problem, however, is that the save is altered before the button is pressed.

I don't know the specifics of what's going on, but the constructor of SAV1 appears to copy data from `Data` to temporary arrays, then back to `Data`.  Saving then reopening the file makes "Verify Checksums" work properly, but because a significant amount of data has been changed, it's possible that there's some long-term side effects.

I've asked the user who PM'd me if it would be OK to share the unmodified save file here.  I'll post it here if the user says OK.

**Comment by kwsch** [comment]
Although the other (SAV3-6) save class objects retain the ability to be validated at any time, the Main form of PKHeX checks to see if the save is edited before checking the checksum validity. Since the SAV1 object is modified when loading, it by default is edited and should not be checked.

Since the SAV1 data is edited when loading, it may be best to just evaluate the Checksum Validity when the data is first loaded (ie, right at the beginning of the constructor) and store it in a private readonly property. The 'ChecksumsValid' property would return the stored evaluation.

**Comment by evandixon** [comment]
Long term, it would be best to figure out what exactly is changing, and make PKHeX rebuild the original data 1:1.  Short term, I believe that would be an acceptable fix.

**Comment by evandixon** [comment]
Long term, it would be best to figure out what exactly is changing, and make PKHeX rebuild the original data 1:1.  Short term, I believe that would be an acceptable fix.

**Comment by SciresM** [comment]
So I'm looking into this.

PKHeX doesn't modify any data in the checksummed region in the constructor -- it appends an additional 0x8000 bytes to the end of Data, then copies stuff to/from it, but that shouldn't impact checksum validity. If you can provide me with the save file that triggers the bug, I can fix this properly, though.
