### ISSUE TITLE
Re-ordering boxes breaks some boxes

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#2961]
**Describe the bug**
I'm not sure if this is just for SWSH and if it's just for Urshifu, but when I move boxes with Urshifu Single-Strike around, everything after it remains in the old box's index and the slot in the new box's index that contained Urshifu Single-Strike is now colored red. This hasn't happened to me with any other species I've moved, and it's consistent with the same box I'm moving.

**To Reproduce**
1. Download the box data I provided in the zip
2. Import it into a SWSH save file
3. Go to "Box Layout" in the "SAV" tab
4. Re-order the imported box using one of the buttons
5. The old index has everything after Urshifu Single-Strike (in this case, only Urshifu Rapid-Strike remains) and in the new index Urshifu Single-Strike is deleted and colored red (and everything after it was not copied)

![image](https://user-images.githubusercontent.com/29823718/89693950-1d0dbb80-d8de-11ea-8a8a-df63b5a5774b.png)
![image](https://user-images.githubusercontent.com/29823718/89693940-12532680-d8de-11ea-8a5f-9c78aad262f1.png)

[Box - Legends (S).zip](https://github.com/kwsch/PKHeX/files/5044106/Box.-.Legends.S.zip)

**Comment by kwsch** [comment]
Offending lines: (`MoveBox`, `SwapBox`, `CompressStorage`)
https://github.com/kwsch/PKHeX/blob/d8fe197a3a463b628849d611106309561d220892/PKHeX.Core/Saves/SaveFile.cs#L661
https://github.com/kwsch/PKHeX/blob/d8fe197a3a463b628849d611106309561d220892/PKHeX.Core/Saves/SaveFile.cs#L706
https://github.com/kwsch/PKHeX/blob/d8fe197a3a463b628849d611106309561d220892/PKHeX.Core/Saves/SaveFile.cs#L924

All 3 are using `SIZE_STORED` which is 0x148 bytes (no party data) rather than `SIZE_PARTY` which is 0x158 bytes.

LGPE saves override `SIZE_STORED` to be equivalent to `SIZE_PARTY`, but since SWSH has some spots stored without party data (looking at you, fused storage slots), they're different (0x148 & 0x158, as listed above).

Probably need to add a new virtual member that indicates the size of a Box Slot, and update all appropriate usages of `SIZE_STORED` to instead use that when appropriate. Can probably make `SIZE_STORED` protected when this new property is added.

**Comment by Kermalis** [comment]
So 16 bytes per Pokémon are being lost? What exactly is at those last 16 bytes? I'm just curious if I've ruined these Pokémon since I don't have backups of them.

**Comment by kwsch** [comment]
You can swap the boxes back which would undo whatever changes.

The program just swaps two 30*0x148 byte segments, rather than two 30*0x158 byte segments.
