### ISSUE TITLE
Marks are unobtainable on certain pokemon 

### ISSUE THREAD

**Issue by Skadiv** [kwsch/PKHeX#3001]
**Describe the problem**
The following pokemon originated in SWSH are incorrectly classified as legal when marked:
- Fossils
- Raid den mons
- NPC trade mons
- Legends 
- Egg hatches

Additionally, pokemon originated in HOME have this same issue.

**To Reproduce**
Edit any of the pokemon listed above by adding a mark, they will remain legal. The following pokemon have all been edited to have an Angry Mark:
[Illegal marks.zip](https://github.com/kwsch/PKHeX/files/5280500/Illegal.marks.zip)

**Expected behavior**
A legality alert for each indicating that marks in those cases are not possible.

**Comment by kwsch** [comment]
There aren't any legality checks provided for Marks beyond the current `count<=1` and other minor restrictions, [handled here](https://github.com/kwsch/PKHeX/blob/fbf7a3658a040e61a1b11d6dbb880c5d9192a0fb/PKHeX.Core/Legality/Verifiers/MarkVerifier.cs).

PKHeX tries not to flag things that it shouldn't; there are likely edge cases that may be identified as static encounters (den) when they are really just wild encounters. I'm a little concerned about these cases -- they'd require extra handling so that any possible matched encounter then depends on if the Pokémon has a mark, then it can't be a Raid Encounter; but if there's no other encounter, should we let it be recognized as a raid encounter and warn instead? Lots of logic required for some cosmetic flagging.

I'm not really interested in fleshing this out with code myself, but am open to anyone submitting a pull request that handles things generally + edge case consideration.
