### ISSUE TITLE
Checking for tracker duplicates

### ISSUE THREAD

**Issue by albertodev01** [kwsch/PKHeX#3143]
**Is your feature request related to a problem? Please describe.**

Sometimes, when creating clones in SWSH, someone could forget to set to zero the **HOME Tracker** value which may be a bad thing actually.

**Describe the solution you'd like**

Would it be possible creating a checker that controls whether there are 2 (or more) pokémon in the boxes with the same tracker?

**Comment by Lusamine** [comment]
It hasn't been necessary to zero out a HOME tracker since April 2020.  HOME no longer deletes Pokémon with duplicate trackers; in fact, the duplicates are assigned a new one.  Additionally, all Pokémon are assigned a new tracker regardless of duplicates the moment they are put into a new HOME, which makes the whole thing rather moot.
