### ISSUE TITLE
Farfetch'd are always "nicknamed" in gen 3

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3185]
This isn't really a big deal or a bug, just some weird behavior. Any farfetch'd will have the nickname checkmark even though the name is default:
![image](https://user-images.githubusercontent.com/29823718/113706490-bcbd5c80-96ac-11eb-85e9-b550eb244b35.png)

If you take off the check, paste the Pokémon to the boxes, and reload it to the window, it's checked again.

The "nickname" can potentially mess with in-game systems that check for nicknames existing, I'm not sure though, feel free to close if it's not a big enough deal to fix

**Comment by suloku** [comment]
I think it is not a bug, I'm pretty sure the game detecta nicknamed pokemon using the remaining "trash bytes" in the 11 char name. Farfetch'd uses 10 chars + the terminator (0x50), so the game (and pkhex) will always handle it as nicknamed.
Please someone correct me if I'm wrong.

Also, this leads to pokémon becoming and unbecoming nicknamed when transfering into and out to pokemon stadium games because stadium games always copy pokémon name only until it finds a terminator.

**Comment by kwsch** [comment]
`FARFETCH'D` vs `FARFETCH’D`
