### ISSUE TITLE
changing a Pokémon to a shiny changes the SID and TID 

### ISSUE THREAD

**Issue by YoshivsJoshi** [kwsch/PKHeX#3192]
Hello, after the new update I can't change my Pokémon to shiny without it changing the SID and PID, I've clicked shiny and held "alt" but it still changes the PID and SID and then just regularly clicking it flags it as illegal, I'd like to keep my original trainer ID and SID, thank you I've attached the files, thank you very much

[Grimmsnarl files.zip](https://github.com/kwsch/PKHeX/files/6290335/Grimmsnarl.files.zip)

**Comment by Lusamine** [comment]
Not sure what your issue is.

If I click shiny on the regular Grimmsnarl without holding anything, it changes PID only and TID/SID don't change at all.  Becoming illegal is expected because you're violating gen 8 Overworld PIDIV checks.  Refer to [this issue](https://github.com/kwsch/PKHeX/issues/3170#issuecomment-791132898) about the same thing.

If I click shiny on the regular Grimmsnarl while holding "alt", it changes SID only.  This doesn't violate the PIDIV checks so it stays legal.

Both of these cases are working as intended.

**Comment by YoshivsJoshi** [comment]
I’m clicking shiny on the regular non shiny Grimmsnarl and it changes to shiny and then says encounter type PID mismatch but the Pokémon can be found shiny in the over world so unsure what I’m doing wrong

**Comment by Lusamine** [comment]
> 
> 
> I’m clicking shiny on the regular non shiny Grimmsnarl and it changes to shiny and then says encounter type PID mismatch but the Pokémon can be found shiny in the over world so unsure what I’m doing wrong

You are making bad hacks that are detectable by the program as bad hacks.  Again, refer to the link about why this is correctly illegal. If you aren't able to solve PIDIV problems, create the Pokemon from an encounter that doesn't require that check, such as eggs.
