### ISSUE TITLE
Pokemon from Max Raid are flagged as ilegal

### ISSUE THREAD

**Issue by CarlosRamirezGriego** [kwsch/PKHeX#3214]
**Describe the problem**
I hosted some Raids and the Pokemon I caught from that Raid are flagged as ilegal. "Invalid: Unbale to match an encounter from origin game"

**To Reproduce**
1. Host a Raid using the parameters in the "additional context" section
2. Capture the Pokemon from the Raid
3. Export the Save
4. Inspect the Pokemon

**Expected behavior**
 The Pokemon is legal since it was captured in game in a legal raid

**Screenshots**
![bug1](https://user-images.githubusercontent.com/32551875/121254880-a32cc280-c85f-11eb-9901-d27c304add34.PNG)
![bug2](https://user-images.githubusercontent.com/32551875/121254903-a922a380-c85f-11eb-871e-7d599e8d7ab0.PNG)
[pk8.zip](https://github.com/kwsch/PKHeX/files/6619517/pk8.zip)

**Additional context**
Den Location: Crown Tundra
Den #: 18
Den Type: RED
Stars and Index: 1 / 60
Seed: 335FD130ADC70398
Games: Sword and Shield

The same happened to Ivysaur from the recent event

**Comment by sora10pls** [comment]
Gible: Is only available as a 3-Star Raid in that location because the 1- and 2-Star Raids are inaccessible by the time you obtain the Rotom Bike’s Water Mode upgrade. Working as intended.

Ivysaur - Distribution raid data needs to be added when it’s released. A stable release of PKHeX released on May 21st can’t know of the existence of a distribution raid that released on June 3rd.
