### ISSUE TITLE
Gen 7 Trainer ID, SID, Gender and Name matches Gen 2 game. Pokemon transported through bank get flagged as Invalid.

### ISSUE THREAD

**Issue by randomdice101** [kwsch/PKHeX#3238]
**Is your feature request related to a problem? Please describe.**
When I migrated my pokemon team from crystal through poketranspoter and bank into pokemon moon and looked at the save with pkhex, the whole team gets flagged as invalid. 

**Describe the solution you'd like**
The flag should be changed to fishy or at least a toggle in the settings to change it should be added since although very rare this is achievable using RNG or non hacking means.

**Additional context**
![Feature Request1](https://user-images.githubusercontent.com/4016932/128605419-c8862c0a-22d0-4058-afef-519c435467b6.png)
![Feature Request2](https://user-images.githubusercontent.com/4016932/128605018-04d11139-cd3f-41eb-ba1d-55717e8d8123.png)

**Comment by Atrius97** [comment]
While having the OT information match cross-generation is astronomically unlikely without the use of RNG abuse, it's technically legal.

I don't think PKHeX should flag it as "Fishy" or "Valid" by default, as in the vast majority of cases it would correctly identify incorrect OT info, it definitely should remain "Invalid" by default, but I don't see the issue with adding a new toggle to settings to allow PKHeX to treat it otherwise.

**Comment by Lusamine** [comment]
This would require you to luck out on both games since the gen7 game needs a 0 SID.  If it's only achievable through RNG abuse, it's better to flag it since the vast majority are hacked.

Similar flags occur for eggs with PID correlation, and gen7 past gen mons with nickname that is too long, transferred mons with unexpected OT friendship values, and probably multiple other cases.
