### ISSUE TITLE
In pokémon Liquid crystal roomhack from firered this application don't work after exporting the file and replacing it for original  is everything good but when you turn on game it will say "the save file is corrupted the previous save file will be loaded"

### ISSUE THREAD

**Issue by DamOne57884** [kwsch/PKHeX#3247]
In pokémon Liquid crystal roomhack from firered this application don't work after exporting the file and replacing it for original is everything good but when you turn on game it will say "the save file is corrupted the previous save file will be loaded"

**Comment by Lusamine** [comment]
PKHeX is not intended to work for ROM hacks. If save files are compatible and load into the program, such as in HaX mode, then you're lucky.  Note that any unintended side effects in-game are beyond the scope of PKHeX as we will only support officially released games.

**Comment by FrostKnight** [comment]
Why do you know only support officially released games out of curiosity? 

I was wondering if this was the case, but I thought I should ask why.

**Comment by ReignOfComputer** [comment]
How would you expect the developers to support every ROM hack out there? The amount of variance would be incredible to account for.

**Comment by Lusamine** [comment]
> Why do you know only support officially released games out of curiosity?
> 
> I was wondering if this was the case, but I thought I should ask why.

Many romhacks make unofficial changes to the save data structure, which is why they don't work. It's an immense amount of work to support everyone's romhack on top of the official games, so this is left to the romhack developer.

In the future, I would suggesting using [Discussions](https://github.com/kwsch/PKHeX/discussions) to ask questions like this rather than reviving 3 year old topics. Issues are for problems with how the program works.

**Comment by FrostKnight** [comment]
This looked like the best place to post, topic wise, so that's why I commented here. Sorry... feel free to fully lock if you'd like.

Yeah, that actually makes sense as to why you don't support hacks. It's just a shame that there isn't a way to detect the settings of the rom is all.
