### ISSUE TITLE
The battle tower ribbon is marked illegal

### ISSUE THREAD

**Issue by liketolike** [kwsch/PKHeX#3307]
![1](https://user-images.githubusercontent.com/88918365/142837667-1e6cddd3-ff94-4085-be5a-229fb54b1462.png)
![2](https://user-images.githubusercontent.com/88918365/142837703-7c2da7c8-7540-4459-8fcc-f6b924b05d43.png)

^^

**Comment by Synthlight** [comment]
Not just battle tower, but the daily/cosmetic ones too.
`Invalid: Invalid Ribbons: Alert, Shock, Downcast, Careless, Relax, Snooze, Smile, Gorgeous, Royal, Gorgeous Royal`

This part specifically, can be fixed with this diff:
```
diff --git a/PKHeX.Core/Legality/Verifiers/Ribbons/RibbonVerifier.cs b/PKHeX.Core/Legality/Verifiers/Ribbons/RibbonVerifier.cs
index e3152097a..4dcf5e414 100644
--- a/PKHeX.Core/Legality/Verifiers/Ribbons/RibbonVerifier.cs
+++ b/PKHeX.Core/Legality/Verifiers/Ribbons/RibbonVerifier.cs
@@ -214,8 +214,8 @@ private static IEnumerable<RibbonResult> GetInvalidRibbons4Any(PKM pkm, IReadOnl
 
             bool gen34 = gen is 3 or 4;
             bool not6 = pkm.Format < 6 || gen is > 6 or < 3;
-            bool noDaily = !gen34 && not6;
-            bool noCosmetic = !gen34 && (not6 || (pkm.XY && pkm.IsUntraded));
+            bool noDaily = !gen34 && not6 && !pkm.BDSP;
+            bool noCosmetic = !gen34 && (not6 || (pkm.XY && pkm.IsUntraded)) && !pkm.BDSP;
 
             if (noDaily)
             {
```
Though I'm not sure if this is the *intended* way, and I'm not sure where the battle tower ones fit in there, so only a partial fix.

**Comment by soopercool101** [comment]
Contest mastery ribbons are also affected by this
