### ISSUE TITLE
Gen 1 Tooltip mismatch info

### ISSUE THREAD

**Issue by Ninjistix** [kwsch/PKHeX#3372]
**Describe the bug**
the tooltip that you get when you hover over Pokémon in Gen 1 that shows their information is invalid for some Pokémon.

**To Reproduce**
1. Open gen 1 save
2. Hover over X Pokémon to see their tooltip
3. See errors

**Expected behavior**
Some Pokémon show the correct tooltip information and some of them are wrong.

**Screenshots**
[Correct Tooltip]
![image](https://user-images.githubusercontent.com/12572974/149607840-32175df0-84f9-43a8-897a-7dcce1841e67.png)
![image](https://user-images.githubusercontent.com/12572974/149607913-acf5cedd-0771-4c06-8399-c1d28fb6479d.png)

[Invalid Tooltip]
![image](https://user-images.githubusercontent.com/12572974/149607890-37e3951c-e0ee-4dab-ac17-7f3cc4552469.png)
![image](https://user-images.githubusercontent.com/12572974/149607939-cda4ac12-7abf-4b4e-852f-8dee62d633c9.png)
![image](https://user-images.githubusercontent.com/12572974/149608015-1aec292e-13be-42da-80cb-e12c68393ac1.png)

**Additional context**
There's several Pokémon that display the correct game origin or catch location, but there's even more that display either a Gen2 or other game location.

Edit: note sure if this applies to other Games/Generations as I haven't rechecked them in awhile

**Comment by kwsch** [comment]
Since Gen1 does not store met location, the program matches whatever is valid first. 

It might not have been where you actually obtained it, but it's where you could have obtained it (in the context of the current data). If there's 100 different encounters that it could be, how would it know which was the actual one you encountered it with since they're all the same result? Hence, PKHeX just chooses whatever is satisfactory first.
