### ISSUE TITLE
Unable to load properly dumped Sword save

### ISSUE THREAD

**Issue by seylerius** [kwsch/PKHeX#3373]
**Describe the bug**
Using PKHex 220101, I am unable to load a Pokémon Sword save. The error produced is `Input file too large`. I have dumped saves from both my v1.3.2 gamecard, as well as a v1.0.0 ROM I acquired for comparison purposes. I have tested extracting saves using both Checkpoint and JKSV. Error persists in all combinations. My Switch is running Atmosphere CFW, v13.2.0, on emuMMC.

**To Reproduce**
1. Open Pokémon Sword, v1.0.0 or v1.3.2
2. Play until you have exited the Slumbering Weald, then save.
3. Close the game and open Checkpoint.
4. Back up the save and copy it to your computer.
5. Open the save in PKHex.
6. Receive `Input file too large` error.

**Expected behavior**
Instead, the party of one Pokémon, your starter, should be displayed.

**Comment by Lusamine** [comment]
All of my Sword saves from base game up to CT load properly in development build PKHeX and in the latest stable PKHeX. Your save file is likely not a proper save file.

**Comment by Atrius97** [comment]
As a note, sometimes the savefile can be exported properly, but damaged during transfer/exporting it.

Try taking the SD card out of your Switch and moving the file manually via SD card reader instead of FTP or Hekate file transfer

When exporting from PKHeX, make sure to save the file to a location on your computer, and then copy that file to your SD card. Don't try to directly export a savefile to your SD card from PKHeX.
