### ISSUE TITLE
Gen 5 Gender Editing Sprite Bug

### ISSUE THREAD

**Issue by Dani88alv** [kwsch/PKHeX#3432]
**Describe the bug**
When editing player's gender in a Gen 5 save file, the trainer class sprite used in the Union Room is from the old gender.

**To Reproduce**
1. Edit gender in Trainer Info
2. Enter the Union Room from a Pokémon Center
3. Your trainer class sprite should be the old gender

**Additional context**
The trainer class sprite can be chosen in the Trainer Card.

**Comment by kwsch** [comment]
Right; the save file usually stores values in separate spots and a single value edit usually isn't enough to completely change how the game expresses it.

Needs to be documented the other values that are nice to have changed, like the trainer class sprite, so that those can also be visible for editing.
