### ISSUE TITLE
PLA checking Pokédex editing consistency

### ISSUE THREAD

**Issue by NotaInutilis** [kwsch/PKHeX#3459]
When editing the Pokédex in PLA, it is possible to have number caught at night > total number caught, number defeated with X type move > total number defeated, or number of alpha caught > number of heavy specimen caught for example.

The editing window already turns red when number of tasks < number of tasks reported. It would be great to add the same highlighting when these numbers conflict to check the "legality" of the Pokédex.

**Comment by Atrius97** [comment]
The Pokédex in Legends Arceus is complex, there's a reason it also doesn't have an "autocomplete" option like prior games.

Someone would have to sit down and manually cross reference all the task relationships, (Number Caught and Caught at Night, Number Defeated and Defeated with X type super effective move, etc.) for all Pokédex entries before this could be implemented.

**Comment by kwsch** [comment]
1. lots of work required to document the inter-relationship of values
2. follow up enhancements like "has sufficient play time happened to reach these values"
3. prior games have no legality checks for unavailable Shiny forms

Not worth considering at this time due to it not being much of a benefit, especially if there's no "complete dex" algorithm yet added. Plugins and pull requests are other options, I'm just not interested in doing this.
