### ISSUE TITLE
RNG Manipulated Trophy Garden Shiny Showing Illegal

### ISSUE THREAD

**Issue by jjaldridge2009** [kwsch/PKHeX#3464]
**Describe the problem**

A Trophy Garden Porygon I RNG-manipulated shiny using Honey, is showing illegal in PkHex due to "unable to match encounter from origin game."

**To Reproduce**
Porygon Z is attached.
[Gamma Goose - 0420F85F4AF6.zip](https://github.com/kwsch/PKHeX/files/8257741/Gamma.Goose.-.0420F85F4AF6.zip)

**Expected behavior**
Porygon was caught through normal means. Had Backlot set to Porygon + Eevee for a long time, and never talked to him again.

**Screenshots**
![image](https://user-images.githubusercontent.com/16225603/158485776-4bf6fc8f-cd5e-462b-87b9-cf48baa088da.png)

**Additional context**
While doing the RNG, I noted that the correct encounter slots for the garden Pokemon were 6 and 7... just like Diamond and Pearl. But the levels I was seeing were not matching in Admiral Fish's PokeFinder.

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/158486685-5a8d396a-0130-4125-a362-a8adde75d4fb.png)
How did you evolve Porygon-Z without trading it?

This is flagging because traded Pokemon need evidence of being traded.  You cannot simply edit the species.  Please do not submit edited data as bugs.
![image](https://user-images.githubusercontent.com/30205550/158486818-43805b6e-09e8-43bd-b0f1-b1cc3e21c15f.png)

**Comment by jjaldridge2009** [comment]
I did trade to evolve it!

However it was traded with a save file that shared the same OT\TID\SID.

Does it not set the trade flag in this case?

**Comment by Lusamine** [comment]
Trading with yourself is not considered to have left your save file.

**Comment by jjaldridge2009** [comment]
My mistake, sorry for the false report.
