### ISSUE TITLE
SWSH Overworld8RNG can not verify star shiny pokemon

### ISSUE THREAD

**Issue by g0dw5** [kwsch/PKHeX#3504]
**Describe the problem**
I wrote a program to find overworld pokemon with specified IVs. When I make a shiny one, I found square is legal but star is not legal. I wonder are the last parameter of GetShinyPID in Overworld8RNG.cs:49 and Overworld8RNG.cs:134 missed non-zero values?

**To Reproduce**
[shiny altaria.zip](https://github.com/kwsch/PKHeX/files/8778881/shiny.altaria.zip)
334 ★ - Altaria - 4AFD6D3D2350 - Square.pk8 is legal
334 ★ - Altaria - 4AFD6D3D2350 - Star.pk8 is not legal
PSV in tooltips of PID is equal to TSV in toolstips of SID in both file.

**Expected behavior**
I can get a legal star shiny pokemon using Overworld8RNG

**Comment by Lusamine** [comment]
You can't just randomly set them to star.  The PID rolled the first time by the seed must be shiny for the TID/SID combination rather than forcing it shiny to a xor0.

The behaviour is if the original PID is shiny, then do nothing to the PID (which allows 1-15 star), and if not shiny, force shiny.  Most of your overworld seeds are going to be nonshiny and forced to shiny.

https://projectpokemon.org/home/tutorials/save-editing/using-pkhex/pid-mismatch-origin-game-swsh-r114/
You can use this to look for star shinies, but only certain seeds will be star for a specific trainer.

**Comment by g0dw5** [comment]
I found the bug here (https://twitter.com/SciresM/status/1197039032112304128), sorry for the wrong bug.

**Comment by Lusamine** [comment]
Neither the issue or your link is a bug.  What you did was use an overworld seed that is not shiny for your TID/SID.  Therefore it cannot be anything but the forced shiny state which requires xor0.

Use the guide I linked to find a shiny seed for your TID/SID, or change your TID/SID to be shiny for that seed.

**Comment by g0dw5** [comment]
Thanks for your noticing. I still think it's maybe a bug that the rarity of star shiny is larger than square shiny. I think I know how RNG works(the bounds of ec, pid, ivs and height/weight. My code is here https://github.com/g0dw5/BDSPRoaming. It can calculate shiny pokemons for Overworld or BDSP Roaming in less than 1 minute. Looking forward to your review, thx.

**Comment by Lusamine** [comment]
> Thanks for your noticing. My code is here https://github.com/g0dw5/BDSPRoaming. It can calculate shiny pokemons(with specified IVs) for SWSH Overworld or BDSP Roaming in less than 1 minute, for overused IVs like 6v,5v0A, it can calculate in less than 10 seconds. Looking forward to your review, thx.

Please do not open issues in PKHeX to discuss what you think it's a bug in the game or for a review of your own program.  This is not place.  I will not be reviewing it.
