### ISSUE TITLE
Roaming8bRNG doesn't respect "Shiny.AlwaysSquare"

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3561]
I'm making a personal plugin, and I'm using `Roaming8bRNG.ApplyDetails()` on a Mesprit in BDSP. It seems to ignore `Shiny.AlwaysSquare`, even though the code doesn't seem like it should be ignoring it, so I'm not sure what's wrong.

I mostly get Star shiny Mesprit from this call, but occasionally get a Square shiny one. For now I have to modify SID to force square shininess, but this method should probably be fixed since the same thing happens when you pull Mesprit (or Cresselia) from the Encounter Database.

**Comment by Kermalis** [comment]
I believe the culprit is here:
![image](https://user-images.githubusercontent.com/29823718/182725483-a9f9b579-d686-49b1-a1d6-d522ff1118c1.png)

pk.PID is not updated before ShinyXor is checked

I'm not sure though. If I lock the call to `ApplyDetails` in a `do while(pk.ShinyXor != 0)` it never exits. I'm probably too tired for this right now.

Also, I want to say thank you for PKHeX, your dedication is just amazing

**Comment by kwsch** [comment]
Thanks, closed by https://github.com/kwsch/PKHeX/commit/d1dad7b8eb0b067c56afc8e304c63e19942c1b12 as you described above.

Might need to give it a higher loop count since the algorithm is essentially bruteforcing results until it finds something satisfactory. I'm sure there'd be a way to only iterate for shiny PID seeds that satisfy the shiny type (described in the commit message), but that's more effort than I want to expend now ;)
