### ISSUE TITLE
Sometimes when batch editing gen 3 Pokémon PIDs, an error is thrown for "G5MGShiny" being the detected PID type

### ISSUE THREAD

**Issue by Kermalis** [kwsch/PKHeX#3611]
It's very rare, given that batch editing 400 Pokémon only generates around 0-2 Pokémon like this (species doesn't affect it). But I have an example below:

![image](https://user-images.githubusercontent.com/29823718/196852913-f59fe432-840e-41b1-9403-b8f7f1dc1015.png)

From my understanding, if these PIDs are being generated correctly, they should be valid in the gen 3-4 context, even if they look like ones generated for Genesect in BW2. Since they're random, I think they should be legal but I'm not sure on the technicalities in this situation. Maybe the gen 5 PID type is taking priority over the random egg one, or maybe the way I'm generating them fails after a few loops and it forgets what to do, I'm not sure.

I'm generating them using the standard `EntityPID.GetRandomPID()` method with the correct version argument, so I think these PIDs are actually random and thus being incorrectly flagged

Here's another example from the next batch edit I did:
![image](https://user-images.githubusercontent.com/29823718/196853411-cab81737-225d-43c0-b37e-04ab45b0d416.png)
![image](https://user-images.githubusercontent.com/29823718/196853433-c1747760-1d1e-4296-8b92-e19f2069579f.png)

**Comment by kwsch** [comment]
1. The PIDIV detection algorithm stops on the first matching algorithm
2. Weak PID+trainer methods can still be legal on pure-random PID encounters.

It is my preference to flag them as illegal, as it is statistically much more likely that the shiny was generated rather than randomly encountered.

As mentioned in the other issue re: generating/mutating new things, it is better to just use the encounter generator API to obtain something legal. Mutating from an existing entity requires much more spaghetti cases compared to the encounter->PKM route.

**Comment by Kermalis** [comment]
I'm now trying to use the encounters (since it makes sense now that you mention it), but the gen 3 encounters don't seem to respect the criteria much, even for basic egg encounters with few restrictions. Shininess and ability are ignored, while gender and nature seem to be respected. Of course I don't expect all criteria to be met for non-egg encounters, but eggs I definitely expect to be a bit more rigid here. I'll think about what to do for next time since this is a bit more involved than I expected
