### ISSUE TITLE
Linux Support (for the future)

### ISSUE THREAD

**Issue by XVicarious** [kwsch/PKHeX#3623]
With the transition of the project to NET6.0, this will leave Linux support completely dead. In fact, it also leaves Mac support completely dead. This is a one step forward, two steps back move.

**Describe the solution you'd like**
Use a cross-platform UI library. There are several options. MAUI doesn't have Linux support, but it supports other platforms and the community is trying to cook up its own ports. There is also Uno and AvaloniaUI. Both of these support Linux (and Mac).
This could also be a chance to simplify and streamline the UI, which could use a facelift (the abysmal "Settings", windows that open and can't be resized even though they're cutting things off, etc), though maybe this is just because I'm using Mono on Linux.

**Describe alternatives you've considered**
I've been told as a Linux user that I'd have to "use a VM". I have virtually nothing else that I need a VM for, or a Windows installation. Frankly this is a ridiculous alternative. For years Linux users have been able to use this application on their own terms. I've seen an amazing shift for Linux support over the entire industry over the last 10 years, personally I think it is a mistake to completely take Linux out of the equation. Though of course I might be biased as I ONLY use Linux. It would just be a shame to lose access to this great application.

**Comment by kwsch** [comment]
It's nothing against Linux/Mac environments, moreso that there's many quality of life improvements in future .NET versions that it doesn't make sense holding on to a framework that is >7 years old. The PKHeX.WinForms program was initially developed in 2014, and updated to net46 a couple years later so the project could use the latest features (like `Array.Empty<T>()`) and performance gains. Now that we're nearing 2023, there's a ton of cool things that I want to use if the target runtime is changed.

Mono (the compatibility layer that allows running WinForms apps on non-windows systems) is not updating to support the new runtimes.

===

There are pros & cons for changing the runtime:

**Pro:**
* Can use higher performing APIs
* New runtime features, new C# language features
* High DPI support

**Cons:**
* No mono support (for Mac/Linux)

There are pros & cons for changing the GUI library:

**Pro:**
* Can be cross platform
* Learn new GUI library paradigms

**Cons:**
* No "drop-in" solution to migrate with minimal effort.
* Nobody is actively contributing to the program's UI development besides me.
* Current GUI code is tightly coupled to WinForms APIs, making it difficult to port.

===

PKHeX.Core is available on NuGet, yet nobody has made a feature-filled attempt using another GUI framework. If future versions of this repo use a new runtime, others can still make their own GUI editor implementation.

This program is free, and the Linux/Mac userbase is extremely small in comparison to the windows userbase. **I don't want to be handcuffed to an old framework when I can learn & use new toys available in net6+**. It's just too much work to rewrite the GUI into another framework. PKHeX.Mobile was an exploration into other GUI frameworks (mobile focused), but nobody else was interested in expanding on my initial work. If someone leads the effort, then I don't mind collaborating and merging a suitable replacement for future maintenance. It's just not worth my time when there's so many other things to do.

The next program update will still target net46, but will shortly upgrade to net7. Others can fork and maintain a net46 branch with future DLC updates, otherwise users must use a VM running Windows.

**Comment by halian** [comment]
Please consider reöpening this issue, as Linux is now able to build programs based on .NET 7 (such as [E-Sh4rk/PokeGlitzer](https://www.github.com/E-Sh4rk/PokeGlitzer)).

**Comment by ReignOfComputer** [comment]
WinForms is still Windows only.

As an open source project, anyone is welcome to attempt to port the existing functionality in PKHeX.WinForms to MAUI for a cross-platform .NET 7/8 experience.

**Comment by kwsch** [comment]
There are ways to run .NET 6+ WinForms apps on Linux, same as before. PKHeX doesn't use any Windows libraries besides regular WinForms.

See below for how others have managed to run the PKHeX WinForms app on Linux:
https://projectpokemon.org/home/forums/topic/62968-pkhex-on-linux/

PKHeX's GUI is not simple, and rewriting to a different GUI platform like Avalonia / web is a different beast, as mentioned in prior comments.

**Comment by FrostKnight** [comment]
Would love to see this work with wine-staging or wine-development.

This looks interesting to me.

As a thought, making it based on python would also be interesting. But in any case, does it currently work with mono or wine? Just curious

**Comment by Lusamine** [comment]
> Would love to see this work with wine-staging or wine-development.
> 
> This looks interesting to me.
> 
> As a thought, making it based on python would also be interesting. But in any case, does it currently work with mono or wine? Just curious

I would suggesting using one of the Linux-related discussions for this rather than an old, closed issue from 2022.
Here's a search for topics about "linux": https://github.com/kwsch/PKHeX/discussions?discussions_q=is%3Aopen+linux
This one has some discussion about different methods people have tried: https://github.com/kwsch/PKHeX/discussions/4147

**Comment by kwsch** [comment]
Wine was updated to support the latest .NET versions anyway.
