### ISSUE TITLE
Introduction of the Polish language

### ISSUE THREAD

**Issue by Makxspa** [kwsch/PKHeX#3687]
Hi, PKHeX doesn't have Polish language so I want to do/help do the translation. I already found the language file so I'm just waiting for your decision if you agree. _Have a nice day._

**Comment by kwsch** [comment]
The program can only be localized to languages supported by the games. Since the games cannot be played in Polish, what localization of species names/etc should be used?

The GUI localization files can be put next to the exe and you can manually override a localization if you so choose by editing it.
