### ISSUE TITLE
Randomize Met Date between the games release date and current date

### ISSUE THREAD

**Issue by PiousVenom** [kwsch/PKHeX#3718]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just quality of life request.

**Describe the solution you'd like**
In the Batch Editor, I'd like a way to randomize the `Met Date` of pokemon to be between the games release date and the current date. 

If the pokemon was an egg, then the `Egg Met Date` would be randomized first, and the `Met Date` would be between the `Egg Met Date` and current date.

**Describe alternatives you've considered**
I know that I can follow [this discussion](https://github.com/kwsch/PKHeX/discussions/3680) to do this, but there's a couple issues with this.

1. For `Met_Day`, you're limited to doing 1-28, as not all months have the same amount of days
2. Could generate a date that is before the games release date

**Additional context**

**Comment by kwsch** [comment]
Batch editor scripts are fine for this purpose.

Randomize one value within the date range, then correct outliers (if month is xyz -> reroll date in smaller range), then use the property copy syntax to copy to the egg date since that is a more plausible value than having (obscenely) delayed hatches.
