### ISSUE TITLE
Make it possible to change "Enrollment Date"

### ISSUE THREAD

**Issue by lipe-dev** [kwsch/PKHeX#3800]
**Is your feature request related to a problem? Please describe.**
My enrollment date is set to some stupid date from Jan 2022 🤣 

**Describe the solution you'd like**
I would like to change it to the day I actually started playing. I believe this should be a date input in the Trainer Info area.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
None

**Additional context**
This is the in game screen: 
![image](https://user-images.githubusercontent.com/8506849/219989209-b0262d1d-c89e-46ed-9793-224e43e33f6a.png)

**Comment by Lusamine** [comment]
Enrollment Date is currently labeled and editable via the block editor.
It's not a simple month/date/year input.

Here is an example of how it works:
![image](https://user-images.githubusercontent.com/30205550/219997322-e4de38b9-85e8-44c8-94ee-ef6a7ac47ac6.png)

This save has a start date of 11/18/2022.
The block has a value of `0x0048A07A`.

When this is converted to binary, the value is `010010001010000001111010`.
This can be split up into 3 parts that are 6, 6, and 12 bits long: `010010` `001010` `000001111010`.
These correspond to the date, month, and year.
`0b010010` = 18 which is the date.
`0b001010` = 10, add 1 to get a month value of 11.
`000001111010` = 122, which is number of years past 1900, so 122 + 1900 = 2022.

To set a specific date, you would do this in reverse.
If you wanted 3/14/2019, each component would be:
Date of 14 = `0b001110`
Month should be 2 (since you add 1) = `0b000010`
Year should be 119 (since you add 1900) = `0b000001110111`

String it all together: `001110000010000001110111`
Convert it to hex: `0x00382077`
Swap the endianness of it and this is what you would change that block to: `77 20 38 00`
(Export the block, edit it in HxD, import it back.)
![image](https://user-images.githubusercontent.com/30205550/219999303-f347e642-7da4-49ef-93bf-e8d60e17d12b.png)
