### ISSUE TITLE
Forcibly changing id of pokemon to default latest handler

### ISSUE THREAD

**Issue by carol-braddock** [kwsch/PKHeX#3804]
**Describe the problem**
When setting an OT for a pokemon, PKHex claims the current handler value is invalid, and defaults it to PKHex. I do not have a save file open, but on the previous version, this worked without issue. I have the auto legality plugin, with it enabled to force scarlet as the save file, as well as a trainers folder with correctly formatted pokemon in it.
**To Reproduce**
1. generate pokemon from blank save
2. change default blank trainer ID to custom ID
3. save and reload the pokemon
4. id is changed to current handler PKHex

**Expected behavior**
The pokemon should have my OT listed as the highlighted OT value, as opposed to forcibly changing itself to PKHex.

**Screenshots**
![image](https://user-images.githubusercontent.com/65787531/220534938-d4b82237-2c47-4ad6-81b1-0bc75ff5c5a4.png)

![image](https://user-images.githubusercontent.com/65787531/220528737-5358d933-06f7-4f34-ad29-52303954cc2e.png)

**Comment by Lusamine** [comment]
A blank save has the default OT: PKHeX. Since your Pokémon has OT: Carol, the only way it could be in a save with OT: PKHeX is if it were traded, so it corrects the HT to PKHeX. If you loaded a save with OT: Carol and the same TID/SID, it would recognize the Pokémon as belonging to the save and not adjust the HT.

This behavior hasn't changed but likely you lost your settings configuration when you updated to NET 7.

If you don't like the automatic HT correction, change the setting in SlotWrite to not SetUpdatePKM.
![image](https://user-images.githubusercontent.com/30205550/220535813-531e4f5d-b101-429e-9999-4543771a23bb.png)

If you don't want it to check whether it's valid for your Pokémon to be in the current save (blank or real), then disable the check in Legality settings.
![image](https://user-images.githubusercontent.com/30205550/220536213-4e56fcdd-9235-403e-b1a1-61276eefae2c.png)
