### ISSUE TITLE
[GEN 2] Leer Charmander reported as illegal

### ISSUE THREAD

**Issue by Lorenzooone** [kwsch/PKHeX#3830]
**Describe the problem**
At level 15, Charmander can learn Leer in the gen 1 games. You can then trade it to the gen 2 games. PKHex reports a transferred Charmander having Leer as having illegal moves.

**To Reproduce**
[POKEMONR_Charmander.zip](https://github.com/kwsch/PKHeX/files/10912479/POKEMONR_Charmander.zip)
Attached, the Charmander before the trade, marked as legal in Pokémon Red. Once it is traded to Pokémon Gold, it's marked as illegal. Also attached, the save file of Gold after the transfer.
A quick way to do this is to start a new RGB save file, and get Charmander to level 15, then trade it to one of GSC.

**Expected behavior**
Charmander should not be marked as illegal.

**Screenshots**
![before](https://user-images.githubusercontent.com/7537905/223511440-7b8ce2f4-ab6f-49b9-81b2-bd60db96ca75.PNG)
![after](https://user-images.githubusercontent.com/7537905/223511445-934d767d-2225-4ed1-95a7-ea2717a26feb.PNG)

**Additional context**

**Comment by Lusamine** [comment]
This is known and falls under the evotree problem where different Pokémon have different criteria to learn moves, evolve, etc across games.

Related:
https://github.com/kwsch/PKHeX/issues/3829#issuecomment-1458371283
https://github.com/kwsch/PKHeX/pull/3359

Will eventually be fixed, just not soon, because of requiring a fairly large change. You can read the previous closed pull request to see issues that need to be handled.
