### ISSUE TITLE
Can't compile, on latest commit with Ubuntu 16.10

### ISSUE THREAD

**Issue by phoen1x74** [kwsch/PKHeX#387]
I'm using MonoDeveloper, and when I open PKHeX.csproj, I get 31 errors when compiling.

**Comment by kwsch** [comment]
Need to provide more detail than that to get any help.

**Comment by evandixon** [comment]
My build server reports the latest commit works with Mono.  (Mono 4.5 on Windows)
http://teamcity.skyeditor.org/viewLog.html?buildId=3180&tab=buildResultsDiv&buildTypeId=PKHeX_PKHeXPrivate_PKHeXCiLinux

Make sure you're using either the Debug or Release build configurations.  The others are not supported on Mono.

**Comment by Melon-Bread** [comment]
Builds fine here Arch Linux x64.

**Comment by anatolyivanov** [comment]
I was struggling with similar issue for two days straight. And the question is: how are you installing MonoDevelop?

Aptitude version (as described in README.md) is outdated, I wasn't able to get build to work for me as well. However, there is now a flatpak package with the most recent version which works perfectly. Installation instructions could be found here:
http://www.monodevelop.com/download/linux/

My written English sucks, so perhaps @kwsch or @evandixon can update the README with flatpak mention instead of apt?

However, you'll still have troubles running the executable in Linux environment without doing some wine tweaking - there are graphical glitches present etc at least for me. I found this free workaround to be the most efficient - Visual Studio prebuilt quickstart VMs. While taking quite a bit of time to download, otherwise, this seems most perfect solution for me to build and run PKHeX.
URL to download VMs is: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by phoen1x74** [comment]
@Melon-Bread mind just sending me the compiled version? Not at my comp right now but I can just try @anatolyivanov solution.

**Comment by GreatWizard** [comment]
It works on Ubuntu 16.xx if you install through the official documentation with flatpack: http://www.monodevelop.com/download/linux/

Before, I had the same build problems (31 errors) with the version of monodevelop from the ubuntu repository.

**Comment by GreatWizard** [comment]
An update of the README will be great! https://github.com/kwsch/PKHeX#gnulinux :)

**Comment by phoen1x74** [comment]
@anatolyivanov Your english is fine, and your solution worked. The program worked pretty much perfect in the flatpak version; thanks.
