### ISSUE TITLE
About Rayquaza move:V-create Legality

### ISSUE THREAD

**Issue by ppllouf** [kwsch/PKHeX#3889]
The source version of this gift Rayquazas is black and white, not black 2 and white 2

**Comment by Lusamine** [comment]
Mystery gifts do not enforce region/gameversion/language legality because the community has not documented that in a way that PKHeX can use for every mystery gift.  This isn't a new bug; it's just that that nobody has put the work into it for thorough checking.

A few mystery gifts are hard coded, but the majority are not.

Refer to: https://github.com/kwsch/PKHeX/issues/275#issuecomment-340240111
