### ISSUE TITLE
Unable to match encounter with a fully legal save when passing a PK9 file from legend arceus to Scarlet and Violet

### ISSUE THREAD

**Issue by KyrnYarl** [kwsch/PKHeX#3917]
**Describe the problem**
The legality check on Legend Arceus show many pokemons as illegal because of their encounter, in a fully legit save when you pass them in a scarlet and violet instance

**To Reproduce**
Slide an evolved pokemon (Samurott-H, Lilligant-H, Deciduye-H, Typhlosion-H or Ursaluna from a Legend Arceus PXHex instance to a Scarlet/Violet instance 

**Expected behavior**
Some pokemons like Basculegion or Sneasler seems to work as intended but not the ones listed above, I specify that my Legend Arceus save isn't modified. The intended outcome should be that the pokemon obtained legitimately should be clear of an encounter mismatch, it only does this once the pokemon is fully evolved. 

**Screenshots**

**Additional context**
Sorry if my english isn't perfect, i'm doing my best.

[0503-01 - Liya - FB4A33F3297F.zip](https://github.com/kwsch/PKHeX/files/11767452/0503-01.-.Liya.-.FB4A33F3297F.zip)
![Capture d’écran (25)](https://github.com/kwsch/PKHeX/assets/136790897/41e94d88-70a9-4a30-b957-dc7b2bf22271)

**Comment by ReignOfComputer** [comment]
As written in the latest changelog:

>  - Added: HOME 3.0.0 initial support. Legality analysis is still under research. Thanks @Lusamine & @sora10pls !
>  - - Lacks full support for cross-game transfers involving evolutions and moves. Please be patient, there's a lot of things to handle!

Known issue, work in progress.

**Comment by KyrnYarl** [comment]
Oh I saw that but didn't understood it that way, sorry.

Love what yall do, keep up! Your work is really appreciated !

**Comment by kwsch** [comment]
Works fine as of the latest evotree branch's commits. Keep in mind the evotree branch is still a work in progress. 
![image](https://github.com/kwsch/PKHeX/assets/6393368/47f950e7-8dcd-4032-a4b7-b660bdb3b6fe)

Older versions of PKHeX operated under the assumption that evolutions for a given game are a superset of all prior and adjacent games; this assumption worked fine until Generation 8, which had to be hackily adjusted to get acceptable results. With all signs pointing to future games having eventual crossover to Gen8+, the revision/gain/loss of evolution methods requires less naïve algorithms to reverse a Pokémon's evolution history, and to double check that the forward evolution path can result in the current state. So instead of a single-shot algorithm with the current format's evolution data, we have to traverse all games it has potentially passed through, which requires a hefty rewrite of the evolution API.

Whenever evotree is merged, this issue will be closed; for now, I'll leave it open so that people can understand why things are currently flagging.

**Comment by kwsch** [comment]
Closed by #3936
