### ISSUE TITLE
Transferring Mewtwo from Gen1 to Gen7 randomizes it's IVs and zeroes it's EVs

### ISSUE THREAD

**Issue by HidekoHaruna** [kwsch/PKHeX#3922]
**Describe the bug**
I'm trying to transfer my Mewtwo I caught in Blue to Ultra Moon. It has all the stats needed to be a shiny, yet using PKHeX to transfer it to my UM savefile causes everything to get randomized/zeroed and consequently makes the Mewtwo non-shiny in UM.

**To Reproduce**
1. Download the attached pk1 file with the Mewtwo (or any pk1 file, actually)
[mewtwopk1.zip](https://github.com/kwsch/PKHeX/files/11856950/mewtwopk1.zip)
2. Put it in PKHeX while a Gen7 savefile is opened
3. Compare the stats

**Expected behavior**
For it to have the same stats as it did in Blue.

**Screenshots**
With the Blue save opened:
![bandicam 2023-06-24 14-24-16-450](https://github.com/kwsch/PKHeX/assets/50747725/553860ca-24d8-4dd0-835a-66e9cfe17298)

After putting the pk1 in my UM save:
![bandicam 2023-06-24 14-24-20-160](https://github.com/kwsch/PKHeX/assets/50747725/465d6d34-6896-4439-b5a9-30580b59bf72)

**Additional context**
I played Blue on Pizza Boy emulator and I'm now playing Ultra Moon on Citra, if it matters any.
Btw, the Mewtwo (like all my other pokemon, even the ones I caught in UM) is flagged as invalid due to the error "Invalid: Geolocation: Country is not in 3DS region" but it doesn't seem to affect the pokemon in any way.

Edit: I'm aware that I can just edit this stuff but keep in mind that I have 38 other pokemon which face the exact same issue and can't bother to edit all of them. Also idk if this randomization thing would also happen with transferring through bank or if this is actually a PKHeX bug.

**Comment by sora10pls** [comment]
Your Mewtwo does not have a Shiny IV spread, otherwise it would be displayed as Shiny in your Gen 1 save file.
Virtual Console transfers via Pokémon Bank ignore your Gen 1 IVs, and reroll them to be random with 3 guaranteed flawless (5 if Mew or Celebi).

Everything presented in this issue is working as intended. If you are unsure how transfer mechanics work, I advise you test them using your 3DS and see how the data is converted to newer formats.
