### ISSUE TITLE
Batch Editor Issues

### ISSUE THREAD

**Issue by ReZeroEmiria** [kwsch/PKHeX#3934]
I've been attempting to run some scripts on batch editor testing out the new operators and came across some issues

=Box=32
≤Slot=16
.Gender=1

For example, this script should change all pokemon of slot 16 or greater to female but it only changes slot 16

I've tried using

!Box=4
=Species=25
.PID=$rand
.EncryptionConstant=$rand

A script to reroll the PID and EC of all Pikachu in my boxes NOT in box 4 but it applied it to JUST box 4

Other times I've tried running

=Species=25
.PID=$rand
.EncryptionConstant=$rand
.Egg_Month=7
.Met_Month=7
.Egg_Day=4
.Met_Day=4
.Met_Year=23
.Egg_Year=23

and sometimes it would tell me I don't have instructions written? Other times it will execute the script and not change the Egg_Day

If I run the PID and EC roll at the end of the instructions seems to let it run fine?

I use the Batch editor often and this is the first I've seen these sorts of bugs. Firs time using the new hex since the tabs stopped being on the top. Hope you can replicate these results.

Edit: Is there a keyword or something that can be used to .MetDate and .EggMetDate to set the date to "today" like how you can click on the calendar in the Met Date Field of the Met tab?

**Comment by teward** [comment]
Tested current release version with similar to first command set:

```text
=Box=1
≤Slot=16
.PID=$shiny
.Gender=1
```

... on a box of encounter-DB generated regular male Riolus in the boxes, and replicated what is described in the bug here - it only affected one single slot - slot 16 - and ignored the rest.  Any attempts to change this (slot <, etc.) failed, same with `!Slot=16` in bulk which affected *everything* in the box.

Will take some pokes on this part on the devel builds later today or tomorrow to see if the issue persists in the devel/nightly builds (July 4th here in the USA so my availability is limited today).
