### ISSUE TITLE
Add portuguese language

### ISSUE THREAD

**Issue by dragao2elastico** [kwsch/PKHeX#3938]
Please add Portuguese language to the software!

**Comment by sora10pls** [comment]
PKHeX used to contain a Portuguese localization; it was removed due to a lack of support.

In order for PKHeX to support other languages, native speakers need to be willing to contribute and translate strings available in the program to their respective languages.

**Comment by dragao2elastico** [comment]
so could i contribute with the translation?

**Comment by kwsch** [comment]
Portuguese isn't an official game language, so there's no official strings for PKHeX to pull from. The old Portuguese translation was removed 5 years ago, and nobody has inquired since. If you're already playing the games, you're going to have to pick one of the available official translations when playing.

PKHeX supports providing a local `lang_{xx}.txt` next to the executable to override the GUI's configured translation for a given language, so the most you can do is that. I don't think it's a good idea to add sideloading for every resource.

You're free to maintain a fork where you can replace every translation resource of a "dead" language with whatever you want. That would probably be the easiest solution for your case.
