### ISSUE TITLE
Event pokemon being flagged for the moves they were distributed with

### ISSUE THREAD

**Issue by carol-braddock** [kwsch/PKHeX#3973]
**Describe the problem**
Dahara City Arceus (Card # 0081 - アルセウス プレゼント) is unable to legally have the moves Blast Burn and Hydro Cannon, even though they were on the pokemon during distribution.
https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_region_serial_code_event_Pok%C3%A9mon_distributions_(Generation_VI)#Dahara_City_Arceus
**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.
[shiny dahara city arceus.zip](https://github.com/kwsch/PKHeX/files/12488342/shiny.dahara.city.arceus.zip)

**Expected behavior**
legality should not flag a distribution event pokemon that knows moves from the event it would otherwise not be able to learn
**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/65787531/472bd768-a3c3-4f31-9d64-73f03d2a89ac)
![image](https://github.com/kwsch/PKHeX/assets/65787531/115fcba7-4586-4566-bc1c-d174737e6119)

**Additional context**
This also affects other pokemon, such as all Generation VIII Pikachu in a cap, due to the distribution having them come with electroweb

**Comment by sora10pls** [comment]
Judging by your screenshots (please provide full window screenshots next time), these Pokémon were went to SV, which resets moves upon transfer via HOME. As such, these event moves would have been stripped away, and could not be remembered in the target game (because they are not a part of its learnset in the target game).
