### ISSUE TITLE
Latest-recorded RTC value for PokéPelago timekeeping

### ISSUE THREAD

**Issue by zetaPRIME** [kwsch/PKHeX#402]
Some way of modifying the recorded time would be nice, if you can find where the value is stored; if you time-travel backwards, even with raw RTC setting, time is effectively frozen until it catches up to where it was before.

**Comment by kwsch** [comment]
Pretty sure that's console specific, not game specific.

**Comment by kwsch** [comment]
Looks like this may be a savegame value due to some NTR codes bypassing the RTC limit. Maybe.

Savegame related feature requests that require research/documentation to be done should be created as threads in the Save Editing Help forum, not as an issue with PKHeX.

It's trivial to add editing of certain values, just have to know what needs to be edited before it can be implemented.
