### ISSUE TITLE
Incorrect file size for SV save 4401609 bytes

### ISSUE THREAD

**Issue by Raava21** [kwsch/PKHeX#4028]
**Describe the bug**
When trying to open my save in PKHex I get the attached error regarding file size. This only started happening with saves after I went online for the hisui decidueye event. Says the size is 4401609 bytes

**To Reproduce**
Open PKHex, try to open my save file

**Expected behavior**
The programme would open as normal

**Screenshots**
Added ![Screenshot 2023-10-06 114848](https://github.com/kwsch/PKHeX/assets/147154064/bc410ea4-7b1b-4c39-a37d-afa4e0853b57)

**Comment by Lusamine** [comment]
4401609 = 0x4329C9 which is way out of the range of valid save files.
https://github.com/kwsch/PKHeX/blob/8b2b858e69e3064d4236e42e98bd29e0b12de493/PKHeX.Core/Saves/Util/SaveUtil.cs#L54-L65

Since it's much smaller, your save is probably getting truncated by the file transfer.

Check how you are transferring the file (try moving directly from the SD card instead of with FTP). This is unlikely to be an issue with PKHeX.
