### ISSUE TITLE
OR Ninjask + Shedinja legality issue

### ISSUE THREAD

**Issue by BrianMendoza** [kwsch/PKHeX#4048]
**Describe the problem**

A Ninjask + Shedinja pair, evolved from a Nincada that was caught in Omega Ruby digital version, returns the following error when using the `Verify all PKMs` button:

```
Invalid: PID sharing for 3DS-onward origin detected.
[main @ [03] (BOX 3)-21: 0291 - Ninjask - 4D7BF2A81AD1.pk6]
[main @ [03] (BOX 3)-22: 0292 - Shedinja - 45A4F2A81AD1.pk6]

Invalid: EC sharing for 3DS-onward origin detected.
[main @ [03] (BOX 3)-21: 0291 - Ninjask - 4D7BF2A81AD1.pk6]
[main @ [03] (BOX 3)-22: 0292 - Shedinja - 45A4F2A81AD1.pk6]
```

**To Reproduce**
[Ninjask and Shedinja OR.zip](https://github.com/kwsch/PKHeX/files/13209632/Ninjask.and.Shedinja.OR.zip)

**Expected behavior**
Ninjask and Shedinja to not be marked as invalid given they were generated in-game.

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/3393507/aa84eebc-3ba7-425e-8a9a-3cd5ea8fa53b)

**Additional context**

If of help, they were both moved from Omega Ruby to Alpha Sapphire via Pokemon Bank with no issue.

PKHeX version 20231011 used.

**Comment by Atrius97** [comment]
Verify ALL PKMs option is intended to cross check the savefile for instances like that which aren't natural clones, it's up to the user to determine whether PID/EC other immutable values are supposed to be shared.

It doesn't specifically exclude instances that "could be natural clones" because they also could just as easily not be, it just notes all instances found.

**Comment by Lusamine** [comment]
As Atrius said, verify all isn't supposed to be a robust check, because there are way too many edge cases to verify. For example, raids in SWSH and SV also share EC, and can share PID if nonshiny, so if two people caught the same mon and traded into the same save, this would also be flagged.

The human is expected to evaluate the messages themselves to decide if they are of concern.
