### ISSUE TITLE
SaveFile data logic from SAV_Misc4 should be moved to PkHeX.Core

### ISSUE THREAD

**Issue by RainingChain** [kwsch/PKHeX#4128]
Ideally, SavEditor should only contain UI logic.
Complexity of accessing and modifying .sav data buffer should be in PkHeX.Core.

For example,  the complexity to determine the Battle Frontier Print value should be in PkHeX.Core.
`Prints[i] = 1 + Math.Sign((ReadUInt16LittleEndian(SAV.General[(ofsPrints + (i << 1))..]) >> 1) - 1);`
should become
`Prints[i] = SAV.GetBattleFrontierPrint(BattleFrontier4.Tower);`

**Comment by RainingChain** [comment]
@kwsch The goal was to move the Battle Frontier Print logic into PkHeX.Core. This is needed for PkHeX plugins to get/set Battle Frontier Print values.  Your commit didn't do it unfortunately.

**Comment by kwsch** [comment]
There was nothing special to extract from the existing code. All it did was get a Work u16 and ignore the low but.

The revised logic reimplements how it fetches by using the abstractions for GetWork, rather than manually indexing into the raw sav.

If you want to fetch the prints for Pt/HGSS, do the exact same as the revised logic. Just one line of code to GetWork/SetWork with the game specific work ID. Having special methods that wrap that is unnecessary.
