### ISSUE TITLE
Change square shiny icon

### ISSUE THREAD

**Issue by Sarutopi21** [kwsch/PKHeX#4131]
im asking if possible to change the icon for square shinies so that is visibly different than the star shiny icon.
This only for inside the boxes because next to the shiny button is already different.

**Comment by Lusamine** [comment]
It's intended to be that way in SV and other non-gen8 games because there is no difference between shiny animations. When it was different before in boxes SV, people got very confused why it showed up that way.

It's different in SWSH and the other gen 8 games because of how the animation is different in SWSH.
