### ISSUE TITLE
Sylveon, Umbreon and Espeon with Mightiest Marks Marked as non legal

### ISSUE THREAD

**Issue by Faskomilo** [kwsch/PKHeX#4143]
**Describe the problem**
When trying to clone a Sylveon, Umbreon and/or Espeon with the Mightiest Mark, evolved from a non genned event Eevee with the Mightiest Mark, it gives three errors at least with Sylveon: "Invalid Move 2: Invalid Move. Invalid: Unable to match an encounter from origin game. Invalid: Invalid Ribbons: Mightiest Mark". 

**To Reproduce**
Please provide a PKM file or adequate information so that we may quickly replicate the parsing behavior on our end.

**Expected behavior**
Pokemon should be legal

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/56936945/8f4621a8-1a6f-4038-83cb-859ec868b4fc)

**Additional context**

**Comment by kwsch** [comment]
Root cause: S/V is the first game that allows using rare candies on level 100's to trigger a level-up evolution. Same as the wild-capturable level 100 Magikarp being able to evolve into Gyarados, this behavior isn't currently checked by PKHeX's logic.

Need to think about how to cleanly implement the edge cases for game-specific evolution quirks.
