### ISSUE TITLE
Batch Editor: Restore Markings support via individual properties

### ISSUE THREAD

**Issue by carlos-hernandez** [kwsch/PKHeX#4156]
In previous versions of PKHex we were able to edit Pokémon markings in batch editor using the following properties:

- MarkCircle
- MarkDiamond
- MarkHeart
- MarkSquare
- MarkStar
- MarkTriangle

As an example, to set a blue circle mark to all Pokémons with a perfect HP IV I was able to do it by running this in the batch editor:

```
=IV_HP=31
.MarkCircle=1
```

To set a red triangle mark to all Pokémons with a hyper trained attack stat I could run:
```
=HT_ATK=true
.MarkTriangle=2
```

However, in recent versions of PKHex those properties were removed and there's no reference in the source code for them in the `master` branch. Instead, we can use the `MarkValue` to set those marks via a decimal value for the combined marks:

<img width="455" alt="image" src="https://github.com/kwsch/PKHeX/assets/7292184/824e57dd-07e7-4062-b5cf-b00de2e5381d">

Using the `MarkValue` alone to mark all Pokémons with their marks based on perfect IVs or hyper trained stats become harder since there are hundreds of combinations to run in the batch editor to set the values in the way we want (6! = 720 just to set the correct marks based on perfect IVs).

The last version I tested with this functionality was in early 2021, so not sure in which version those properties were removed in favor of the `MarkValue` one.

---

**Proposed solution**

There are two options to set all the marking flags depending on how the users want to organize them:

1. Support suggestions for the `MarkValue` property: `.MarkValue = $suggest`. This will automatically set the marking flags to the correct one according to the community conventions (blue for a perfect IV stat or red for a hyper trained one)
2. Restore back the support to set individual marks

**References**
- https://projectpokemon.org/home/forums/topic/62871-which-code-can-batch-remove-pokemon-markings/

**Comment by kwsch** [comment]
Everyone has a different convention. 
1. [PKHeX](https://github.com/kwsch/PKHeX/blob/671c3564eea252d10313957a8e8dd6033755a946/PKHeX.Core/Editing/Applicators/MarkingApplicator.cs#L61)'s markings applied on import will treat 31 & 1 as blue, and 30 & 0 as red. 
2. [AutoLegalityMod](https://github.com/architdate/PKHeX-Plugins/blob/a7745f46826955545b3cf39d1dbce2d8b414ae8f/PKHeX.Core.AutoMod/AutoMod/Legalization/SimpleEdits.cs#L149) applies 31 as blue, and 1 and 0 as red.
3. Your described method is different (above two do not identify Hyper Trained).

The MarkValue byte/ushort is different for Generation 3, in that there are only 4 marks instead of 6, and aren't in the same order. Generation 7+ introduced the dual-color marks.

Ideally, 3 interfaces are created and implemented to each PK* type appropriate:
1. byte-Value, boolean Marks (4 total)
2. byte-Value, boolean Marks (6 total); extend first interface.
3. ushort-Value, byte-Enum Marks (6 total).

The existing `MarkValue` should then be removed in favor of the above implementation, and any uses (like `MarkingApplicator`) should be updated.

**Comment by carlos-hernandez** [comment]
@kwsch I couldn't agree more, everyone has a different convention. My intention with this issue is to have a way in PKHeX to apply our preferred one by setting individual marks as desired, considering the differences between generations.

**Comment by kwsch** [comment]
Revised behavior now works:

```
=IV_HP=31
.MarkingCircle=1
```
```
=IV_HP=0
.MarkingCircle=Pink
```
```
=IV_HP=31
.MarkingCircle=true
```
Boolean, integer, or Enum name work :)
Note, it refers to them as `Marking*`, not `Mark*` like before. Thank Legends: Arceus for necessitating this terminology differentiation!
