### ISSUE TITLE
Editing Pokémon that originate from GO in Scarlet/Violet causes them to no longer be depositable in Home (Error 10015)

### ISSUE THREAD

**Issue by Gameskiller01** [kwsch/PKHeX#4185]
**Describe the bug**
If you transfer a Pokémon from GO into Home, then withdraw it into Scarlet/Violet (have only tested Scarlet personally but assume Violet will be the same), edit it, and attempt to deposit it back in Home, it will give an error 10015 (despite PKHeX still marking the Pokémon as legal, of course).

**To Reproduce**
1. Transfer a Pokémon from GO to Home
2. Withdraw that Pokémon from Home into Scarlet/Violet
3. Edit that Pokémon using PKHeX on the Scarlet/Violet save file
4. Attempt to deposit the edited Pokémon back into Home

**Expected behavior**
The Pokémon should be able to be deposited back into Home no problem.

**Screenshots**
![GF-oC7NbsAAbpfw](https://github.com/kwsch/PKHeX/assets/49107979/245fef32-375e-4c68-81eb-71fda3201da9)

**Additional context**
In the above example, the only thing I had changed was the met date on the Gimmighoul & Fennekin, changing it from 09/02/2024 for both to 27/02/2023 for Gimmighoul and 02/12/2020 for Fennekin. Nothing else was changed at all. They were also the only Pokémon I was attempting to deposit. I also tried depositing both individually, and both gave the same error. Depositing a Meltan caught in GO and transfered the same way, but edited in a Shield save file, worked perfectly fine just moments before (worth noting though that this Meltan had originally been caught and transfered to Home at some point in 2022/2023, just in case that changes anything). Previously at some point in 2023 I had been able to transfer a Gimmighoul into Home, edit its met date in Scarlet, then deposit it back into Home without a problem, but when taking that exact same Gimmighoul, editing its met level in Scarlet, then attempting to deposit it back into Home earlier this month I once again got error 10015.

**Comment by sora10pls** [comment]
Not a bug with PKHeX, nor can this ever be fixed. Refer to my comment here: https://github.com/kwsch/PKHeX/issues/3945#issuecomment-1652680114

Since Ver. 3.2.1, HOME now yields error code 10015 for invalid HOME data.

**Comment by Gameskiller01** [comment]
Thanks, good to know. Do we know the reason why editing a Pokémon in Shield works fine, but editing one in Scarlet does not?

**Comment by sora10pls** [comment]
When a Pokémon first enters HOME from a prior game (this includes GO), the "default" data that is applied is SWSH-based, likely as a fallback for any species not available in any other games. Since HOME technically has record of it being in SWSH, despite never being in SWSH, this makes editing in those games the one exception.

**Comment by Gameskiller01** [comment]
Thanks. Could this be circumvented by simply removing the Home tracker in Scarlet and allowing it to generate a new one once they are deposited back into Home, or would Home see the origin game of GO and expect it to already have a tracker, thus flagging it as illegal if it doesn't?

**Comment by sora10pls** [comment]
Using your own example, a Gimmighoul caught in GO and moved to HOME could never _not_ have a tracker. Removing the tracker in an attempt to have the server assign you a new one would just have you running in circles.

The solution would be to restore the original PK9 from before any editing was done to it, since HOME has record of the Gimmighoul with its original tracker and the met date 2/9/2024. The moment you do ANY EDITING, HOME will flag it and give you that error code.
