### ISSUE TITLE
Editing SV Pokedex in PKHeX erases all Pokedex data in game

### ISSUE THREAD

**Issue by hcook95** [kwsch/PKHeX#4203]
**Describe the bug**
I noticed that for some reason I didn't have my starter in my Pokedex, so I went into PKHeX to add Sprigatito. The first thing I noticed in the PKHeX Pokedex editor is it was sometimes inconsistent with what I had in the game. For example, it said I didn't have any of the Ghastly line caught, while the in-game Pokedex showed that I did. 

Anyways, ignoring that, I tried adding the caught seen, obtained, heard of, Male, and English flags to Sprigatito. When I exported the save and opened the game up, it showed my Pokedex as completely empty.

**To Reproduce**
1.  Go to 'Sav'-->'Pokedex'
2. Go to a Pokemon without a Pokedex entry (in my case it was Sprigato).
3. Add the 'Normal' Flag for 'Seen', 'Obtained', and 'Heard Of'. Then check the Male and the English flags.
5. Click 'Save'
6. Export Save
7. Open save and check Pokedex.

**Expected behavior**
I expected Sprigatito to be added to my Pokedex

**Screenshots**
![15892351_20240306110746_1](https://github.com/kwsch/PKHeX/assets/38864544/0c76cc78-7619-4c38-8b6e-f2400feb7264)

**Additional context**
Scarlet 3.0.0, emulated in Y*zu.
Pkhex release: 24/01/12

**Comment by Lusamine** [comment]
What version of the game did you start your save on?

**Comment by hcook95** [comment]
3.0.0

**Comment by kwsch** [comment]
Running on downgraded patches will cause the behavior you are experiencing; the Pokedex was initially stored in one save block, but with the first DLC it was reformatted into a second block.

Downgrading from a DLC patch to a pre-DLC patch will cause the game to look at the old Pokedex block, which is never revised due to the new Pokedex block being the active block for DLC save files.

PKHeX does not support this scenario of downgrading patches and reversing the migration of blocks, as there is no reasonable scenario to do so. Play on your console with updated patches.

**Comment by hcook95** [comment]
I see that somehow the DLC got removed from Scarlet. Reinstalling the DLC seemed to fix the problem. Thanks for the help!
