### ISSUE TITLE
Save Checksums S&M

### ISSUE THREAD

**Issue by LokiGrants** [kwsch/PKHeX#422]
Save Checksums for S&M are always saying that cannot be checked as soon as it's opened on PKHEX.

**Comment by evandixon** [comment]
Does it say "Your platform does not support the required cryptography components. In order to be able to save your changes, you must either upgrade to a newer version of Windows or disable FIPS compliance mode."?  If so, this means you're using Windows XP and have FIPS compliance mode enabled.  A workaround might be to apply [this](http://stackoverflow.com/questions/1293905/sha256cryptoserviceprovider-and-related-possible-to-use-on-winxp/3341727#3341727) registry edit.

If that works, we may need to add this to an FAQ page somewhere.
