### ISSUE TITLE
Koraidon/Miraidon 

### ISSUE THREAD

**Issue by bdawg1989** [kwsch/PKHeX#4260]
**Describe the problem**
A simple `trade Koraidon` or `trade Miraidon` with latest commits on PKHeX.Core with sysbot is invalid now for some reason.  Assume it has something to do with refactor of Legality settings?

**Comment by Lusamine** [comment]
There are two Koraidon, and one cannot be traded. If your file has the Met Location of "Poco Path", this one is impossible to trade, as it is your bike. If it has the met location of "Area Zero", then upload it for us to look at.

**Comment by bdawg1989** [comment]
Sorry, I thought it was limited to just those two, but all basic trades return invalid now for some reason.  I'll have to dig deeper and find out what exactly is going on and i'll reply back.

**Comment by Lusamine** [comment]
When reporting errors, it helps to read the error first. You can click on the red triangle to see what the error is.
Since you haven't provided the error, all I can do is guess at what the error is.

My guess is that your legality checking settings are checking the handling trainer.

![image](https://github.com/kwsch/PKHeX/assets/30205550/7aed1da4-677e-4056-bc5d-e493195c0b01)

I'm closing this; if you have a specific error that you think is incorrect, please provide the file and I will re-open it.
