### ISSUE TITLE
Level 15 Meowth Met on Route 24 in LGPE marked as Illegal

### ISSUE THREAD

**Issue by DarkKrimson** [kwsch/PKHeX#4269]
**Describe the problem**
Level 15 Meowth met on Route 24 in LGPE are being marked as Illegal. 

**To Reproduce**
Go to Route 25. Apply a Lure. Wait for a Meowth to spawn and let it walk to the left of the grass into Route 24. Encounter it and catch it. The Meowth will be Level 15 but with a met location of Route 24.

**Expected behavior**
PKHeX should not mark this encounter as illegal.

Route 24 and Route 25 rules should be the same for both with the exception of Poliwag, Magikarp & Poliwhirl as the body of water they can spawn from are not bordering Route 24's boundaries. 

Theoretically, other Pokemon that spawn from Route 25's only patch of grass could also travel to Route 24 and be marked illegal as well.

**Screenshots**

![Capture](https://github.com/kwsch/PKHeX/assets/36968517/0a4ddcee-afbf-4460-bf76-216e19227404)

**Additional context**
Meowth encounter levels between 7-12 on Route 24
Meowth encounter levels between 9-14 on Route 25
With a Lure applied, Level 15 is possible on both Route 25 and Route 24.

**Comment by sora10pls** [comment]
Crossovers are not accounted for yet, needs more research. Not all species will cross route boundaries depending on the location of the grass and their species walking behaviour.

**Comment by Lusamine** [comment]
It's been known for a while that LGPE crossovers exist, but most reports are a few isolated Pokémon. What we need for this to be implemented is a more complete list of what is and is not possible to crossover.

I have a [spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vTtdRo73vwMYLzcCeyhcAh9XEnqlfb1pqk2mUwqD8qDNZWH-Pj7NVfoX0QAhTYG_kypbUYoTNd3s3S0/pubhtml) I started a few years ago with known crossovers (including this Meowth).

Unfortunately, not a lot of people want to research LGPE, especially since you can't do anything except leave the game idle and wait for a Pokémon to cross over a boundary. If anyone wants to contribute, it would allow this to be implemented.

**Comment by DarkKrimson** [comment]
> It's been known for a while that LGPE crossovers exist, but most reports are a few isolated Pokémon. What we need for this to be implemented is a more complete list of what is and is not possible to crossover.
> 
> I have a [spreadsheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vTtdRo73vwMYLzcCeyhcAh9XEnqlfb1pqk2mUwqD8qDNZWH-Pj7NVfoX0QAhTYG_kypbUYoTNd3s3S0/pubhtml) I started a few years ago with known crossovers (including this Meowth).
> 
> Unfortunately, not a lot of people want to research LGPE, especially since you can't do anything except leave the game idle and wait for a Pokémon to cross over a boundary. If anyone wants to contribute, it would allow this to be implemented.

Thanks for sharing this. I'll try to contribute what I can.
