### ISSUE TITLE
Gen 1 (Green / Midori Japanese) Pokemon in Boxes don't show up

### ISSUE THREAD

**Issue by grnqrtr** [kwsch/PKHeX#4274]
**Describe the bug**
Pokemon in boxes don't show up in PKHex. Only the pokemon in 'Party' show up, but boxes are empty.

**To Reproduce**
1. Load .sav file.
2. Click on 'Box' tab.
3. All boxes are blank, but shouldn't be.

**Expected behavior**
The pokemon in boxes from save file should load and show in PKHex.

**Screenshots**
![Party shows as expected](https://github.com/kwsch/PKHeX/assets/16716573/48ee8586-e2d3-4917-aa8d-b6103d23dc37)
![But boxed pokemon don't show up](https://github.com/kwsch/PKHeX/assets/16716573/40dd7476-effd-402e-99a9-4db786a6c962)

**Additional context**
Here is a zip of the sav file I'm trying to load:
[Pocket Monsters - Midori (Japan) (Rev 1) (SGB Enhanced).zip](https://github.com/kwsch/PKHeX/files/15351861/Pocket.Monsters.-.Midori.Japan.Rev.1.SGB.Enhanced.zip)

**Comment by kwsch** [comment]
Works fine on the latest commits, so I assume whatever lingering issue was fixed in the changes since the last release.

![image](https://github.com/kwsch/PKHeX/assets/6393368/e535c3b2-9cbf-4510-bf24-e59e2f9e86a0)

You can try with the latest commit build here: https://projectpokemon.org/home/files/file/2445-pkhex-development-build/

**Comment by grnqrtr** [comment]
Just wanted to confirm that it does in fact work fine in the latest commit build that you linked. Thank you!
