### ISSUE TITLE
Weezing-Galar

### ISSUE THREAD

**Issue by bdawg1989** [kwsch/PKHeX#4304]
**Describe the problem**
I ran a `convert 9 Weezing-Galar` on sysbot and downloaded the pk9 file it returned, which when I opened in PKHeX it said it was legal as well.  How can you get a Galarian Weezing in Scarlet/Violet through a picnic?

**To Reproduce**
Here is the pk9 
[0110-01_-_Weezing_-_00005EF4ACF8.zip](https://github.com/user-attachments/files/15894585/0110-01_-_Weezing_-_00005EF4ACF8.zip)

**Screenshots**
![image](https://github.com/kwsch/PKHeX/assets/80122551/62e444de-a4c5-44e1-bf6a-aa0cd2b36143)

**Comment by Lusamine** [comment]
You can transfer it to SWSH to evolve it and then transfer it back.
I'm guessing you have the setting to check HOME tracker off, which is why it's showing as legal. It's correctly illegal for me.

![image](https://github.com/kwsch/PKHeX/assets/30205550/441abf47-d868-44dc-b816-2319a418d2fc)

![image](https://github.com/kwsch/PKHeX/assets/30205550/9bd6f9e1-f7e2-4296-895a-6af61d2de0a9)
