### ISSUE TITLE
2008 World Championships Lucario is corrupted when imported

### ISSUE THREAD

**Issue by ibob247** [kwsch/PKHeX#4323]
153 DP - Worlds 2008 Lucario (ENG).wc4 is corrupted if it is imported via the Mystery Gift editor and received by the NPC in green at the Pokemart.  It appears as a red square and the PKM that's generated cannot be imported. 

I'm not sure if this is an issue with PKHeX the PKM or the two different emulators I used to receive the mystery gift.

The wonder card does behave correctly when it is dragged and dropped directly into the party or a box.

![Lucario error 1](https://github.com/user-attachments/assets/0fb1eb3c-bcda-4c11-92c4-e3eae18e63c8)

![Lucario error 2](https://github.com/user-attachments/assets/af52f182-498d-4834-9a06-afed60b8285c)

![Lucario error 3](https://github.com/user-attachments/assets/adbea5a8-8c3c-4388-8ad4-dd2330c9af29)

![Lucario error 4](https://github.com/user-attachments/assets/62ae320d-8b52-422c-be27-17d5cb4271b4)

**Comment by kwsch** [comment]
I vaguely recall this is because the gift file (pgt) has a bit set in the Sanity (0x4) offset of the PKM data, which signifies the data is decrypted. PKHeX will never set this data, as it is only used temporarily during the game while playing.

WC4 files are not raw dumps for the game. Not an issue with PKHeX; cc @PP-theSLAYER re: pporg event gallery
