### ISSUE TITLE
GO Shiny Zamazenta/Zacian 

### ISSUE THREAD

**Issue by ladyluminous1** [kwsch/PKHeX#4365]
**Describe the problem**
I transferred the new Zacian from Go to Home, opened it in PKHeX, and it shows Illegal.  Is it possible to fix?

**Additional context**

Here is the pk8 file.

[Zacian ■--Modest-Intrepid Sword-25.27.23.27.23.18-2024-GO.zip](https://github.com/user-attachments/files/17262812/Zacian.--Modest-Intrepid.Sword-25.27.23.27.23.18-2024-GO.zip)

thx!

**Comment by Lusamine** [comment]
GO legality is managed by PGET. The pkl is updated with each new release. It is expected behavior that a program released before a new event does not know about the new event. 

You can either update your program with the pkl yourself if you need it legal now, or wait until the next release.

https://github.com/projectpokemon/PoGoEncTool
