### ISSUE TITLE
PKHeX for Analogue Pocket?

### ISSUE THREAD

**Issue by CodebyCR** [kwsch/PKHeX#4366]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when if I need to start my PC only to modify a save file.

**Describe the solution you'd like**
A very nice solution were to the availibility to modify the save file directly on my `Analogue Pocket`.
I think many Pokémon enthusiast play on the Analogue Pocket and the Analogue Pocket cores save the progress directly in a .sav file. This would be fit very well in the ecosystem.
A modified subset version of pkhex for the Analoge Pocket which can modify .sav files of the first three Pokémon Generations souves this gap.

**Describe alternatives you've considered**
I'm unsure whether there any real alternatives maybe use a online sav file modifier and your phone conneced to the Analogue Pocket, but this is also a unfinish souluion in my opinion.

**Comment by Lusamine** [comment]
PKHeX is a PC program. [PKHeX.Mobile](https://github.com/kwsch/PKHeX.Mobile) was attempted a long time ago but since very few wanted to contribute to it, so it's largely fell out of use.

The program is open source. You or anyone else is welcome to try making it run on anything you like. Having to maintain the program for even more niche systems is not a goal of this repo.

**Comment by kwsch** [comment]
PKHeX is a Windows Forms application, which means it was written as a PC program for the GUI.

If you want something that runs on specialized hardware (like a game console), which has an entirely different graphics API, then you need a different application/codebase.
