### ISSUE TITLE
Gen 7 QR Generation suggestion

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#438]
First off, thank you to you and SciresM for implementing this, the feature has been nothing but fantastic ever since its implementation. I'd just like to request two things for it.

First off: at the bottom left after a QR Code is generated, you're able to choose which of the 32 Boxes you'd like the Pokemon to be injected to. While it does work, perhaps instead of being able to select which Box number, have it let the user choose a Box from a drop-down list, similar to the Box interface on the main form of PKHeX (picture provided below as an example). This would come in handy for people (such as myself) that have Boxes named differently depending on what they are (i.e. Legendary, Shiny, Event, etc.), rather than keeping them named Box 1, Box 2, so on and so forth. I could imagine it would be annoying having to remember which number Box has all of your Legendary Pokemon, especially if you have lots of Boxes filled.

![image](https://cloud.githubusercontent.com/assets/17801814/20452293/587718da-add4-11e6-913e-7d9f73d212d4.png)

Secondly: while not so much a request, but rather a question... is it possible to inject Pokemon into our current Party? If so, implementation would be nice.

Thanks again :)

**Comment by SciresM** [comment]
Not going to add the Box name selection feature -- consider that these QRs are meant to be system-agnostic, and it would be confusing to label Box 7 with a name other than Box 7, since not every system has those nicknames.

Second: I can consider adding it, but I'd rather stick to boxes, to be honest, for simplicity -- what advantages does party provide over box?

I'm going to close, this, too, but please comment with your response anyway, I'd like to hear the rationale.
