### ISSUE TITLE
Incorrect Inventory Pouch Names

### ISSUE THREAD

**Issue by codemonkey85** [kwsch/PKHeX#4391]
**Describe the bug**
Some of the inventory pouch tabs have the wrong name (and icon?). For instance: Let's Go Pikachu / Eevee have a "Z-Crystals" pouch which appears to be for evolution stones and PP items. Pokémon Scarlet / Violet have a "Candy" tab which appears to be crafting components for TMs.

**To Reproduce**
1. Load any Let's Go Pikachu or Eevee save file.
2. Go to SAV tab -> Items button.
3. Check the tab icons / tooltip text.

**Expected behavior**
The tabs should match the pouches found in-game.

**Screenshots**
![image](https://github.com/user-attachments/assets/957cb208-ae53-48f9-84e8-98fb64162c6a)
![image](https://github.com/user-attachments/assets/2d9cce6a-840d-4bf1-9a27-1b3b5e3c271c)

**Comment by codemonkey85** [comment]
Same deal with Sword / Shield: 
![image](https://github.com/user-attachments/assets/471b1bfa-6035-4464-9fcc-e799b81ffea7)

I'm also seeing 'PC Items' for Legends Arceus. I'm guessing there just wasn't a custom category for the storage box. 
![image](https://github.com/user-attachments/assets/ce8566b2-d5d8-4db1-8573-49de912fd2a8)

**Comment by kwsch** [comment]
Correct, they're just reused icons because there's no localization/sprites duplicated for each bag type.

Pouches likely aren't consistently localized (eg one language might be consistent, but might change between generations for others) so it's not really a high-interest/high-priority thing to differentiate besides a unique icon. The initial goal was to just visually distinguish pouches without wordy/english-only names, hence the sprite-for-each.
