### ISSUE TITLE
PKHex Illegal Mode issue: Can't Create Illegal quantities

### ISSUE THREAD

**Issue by PKMWM1** [kwsch/PKHeX#473]
This is a small thing but something that is important to me. When I want to set an item quantity in Illegal Mode to something above 999, such as 65535, represented in-game as ?35, it still sets my quantity back to 999, despite the fact that is should be stable in the games and should be possible in illegal mode. Its small but I would like to make it so I don't have to re-upload my save for a new stack of rare candies. You also can't do it with money, BP or Festival Coins. Simply disabling the quantity regulator in illegal mode is all I'd want.

**Comment by kwsch** [comment]
Gen7 inventory items are physically capped at 10 bits (1023). The game's setter caps it at 999 if the total is above 999. Even if I bumped it to the physical cap, you'd only get 24 extra items in the stack. Might want to just give yourself a few full stacks since a glitch stack is impossible.

BP/Coin setters are just mimicking the game's setters. You can always create a fork to try and tweak the code as you wish.

HaX was never intended to be used outside of PKM editing :)

**Comment by PKMWM1** [comment]
I would be I can't figure out where that value is set in the code. Also, I'd like to have it for older games as well, as Gen 3 - 6 have the cap up to 65535.

**Comment by kwsch** [comment]
[Gens 1-6 already have max stack tweaks for HaX](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Subforms/Save%20Editors/SAV_Inventory.cs#L168-L174).
