### ISSUE TITLE
Can not alter 7th Gen OT

### ISSUE THREAD

**Issue by SabithaSuki** [kwsch/PKHeX#504]
Whenever I try to modifiy the OT to make a valid 7th gen Pokemon, it defaults to the old gen 6 and bellow. To be specific, I am trying to make a Manaphy that is traded up from Soul Silver, yet has the same OT as my 7th gen trainer.

It just doesn't seem to be happening. Whenever I try and battle with friends it says "There is a problem with one or more of your pokemon."

**Comment by kwsch** [comment]
Transporting past gen pkm to gen7 is not officially available, hence why online is blocking you.

**Comment by ApacheThunder** [comment]
Server is also actively blocking national dex mons not available in alola. This includes Pokémon bred from eggs (so that they hatch with legitimate stats and what not) so even if they were correct, the servers will still not allow you to use them until after the Pokébank update. I don't think it's just that issues converting gen 6 mons to gen 7. There's a blacklist of unavailable mons. This doesn't seem to carry over to egg moves and what not as it seems I can use egg moves on mons that aren't available in gen 7 without Pokébank sourced parents.

**Comment by White-Canary** [comment]
> This doesn't seem to carry over to egg moves however as it seems I can use egg moves on mons that aren't available in gen 7 without Pokébank sourced parents. Assist Spinda, and Self-Destruct Snorlax are two notable examples I have been able to use online.

Those are already legal though since they can breed with Smeargle.

**Comment by ApacheThunder** [comment]
Hmm that might explain it then. I forgot you can bring hard to get egg moves from Smeargle.

**Comment by White-Canary** [comment]
Actually Snorlax is only in the Monster group, which is weird because it's a mammal. But Assist Spinda is definitely legal.

**Comment by ApacheThunder** [comment]
Yeah I don't think Smeargle is the sole reason the egg moves are legal. The servers just don't check for them. Pretty sure Smeargle isn't in the same egg group as Palosand and I was able to use Ancient Power on it as an egg move. Which I believe it's not supposed to get. Unless there's some kind of chain breeding you can do with Smeargle to eventually get the egg move to the Palosand.
