### ISSUE TITLE
Feature request: Pokeball and Shiny sprites

### ISSUE THREAD

**Issue by lomejor18** [kwsch/PKHeX#505]
it would be so great! so you can pick a matching ball... somebody is making those sprites:
https://github.com/msikma/pokesprite

![sin titulo](https://cloud.githubusercontent.com/assets/24194552/20642946/e0ac082c-b3f2-11e6-8feb-3b6ce504e5a5.png)

**Comment by sora10pls** [comment]
Personally I too would like to see the Poke Ball images, but I feel like the shiny sprite addition isn't necessary. The star feels like enough to differentiate between shiny and non-shiny

**Comment by lomejor18** [comment]
the star tells you that the pokemon is shiny, but you need to know the actual color to choose a matching ball... i'm an old player, but is difficult to remember every single shiny color

**Comment by NinFanBoyFTW** [comment]
I would love to see this implemented. the pokeballs would be very useful especially for the obscure ones like friend ball or moon ball and I think it would be awesome to have the shiny sprites as long as it wouldnt take too much work since they already have most of them done from that link you posted.
