### ISSUE TITLE
batch editor guide

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#516]
Hi. with the hacking of project pokemon and those resources being down for a while now I wanted to know if you would be able to put a somewhat guide or at least all of the commands that are possible in the batch editor. I thinkit would be very useful and make the batch editor much more usable. I think this would be something that should go in the about section on pkhex just like normal shortcuts and the changelog. I normally wouldnt ask for something like this but with seeing how fragile project pokemon can be with all of the possible good resources I can find, I think it would be pretty necessary

**Comment by evandixon** [comment]
Via Kaphotics's original post, will be available once we're finished setting up the forums:
----------

**Using the Batch Editor**

**Caution:**

When using the Batch Editor, there is no UNDO.
* If you modify the contents of a Folder, the changes are permanent to those files.
* If you modify the contents of a Save File, the changes are permanent unless you re-load the Save File.

![Screenshot](http://i.imgur.com/OoqWsvK.png)

The Batch Editor is a powerful tool in which the user can make mass modifications to Pokémon in either their save file or supplied folder. By using the built in 'script builder', you may select from properties to either 'set' them or 'filter' according to its value. The script in the image above is an example of how to redefine the trainer and friendship details of the Pokémon, effectively 'stealing' it from another trainer.

There are three types of 'script commands' that may be entered:
```
 .    This sets the property of the Pokémon equal to the value.
 =    This requires the property to be EQUAL to the value.
 !    This requires the property to be NOT EQUAL to the valueIf a 'filter' (=,!) is not satisfied, the Pokémon is skipped.
```

The script interpreter is smart enough to understand the difference between numbers, strings, and booleans; quotation marks are interpreted literally and should not be used.

Empty or invalid slots are skipped by default. A slot / file must have a valid Pokémon in order to be modified

----------

An advanced modification script is demonstrated in the following image:
![Screenshot](http://i.imgur.com/RnAXoCT.png)

```
 =Box=1!Slot=1.Species=7=IsNicknamed=false
```

Filters are interpreted first. Even though the "=IsNicknamed=false" appears after the ".Species=7" command, the batch editor will require all filters to be satisfied before any modifications are made. To explain what the above script does, it requires the Pokémon to be in the first box, but not in the first slot, and to be not nicknamed. It then sets the Species ID to 7 (Squirtle).

**Special Tricks**
1. Randomize a PID: use ".PID=$rand".
2. Randomize EncryptionConstant: use ".EncryptionConstant=$rand"
3. Shiny Pokémon: use ".PID=$shiny".
4. Set EC = PID: use ".EC=PID"
5. Delete Pokémon: use ".Species=0"
6. Set Date (Met / EggMet): use yyyyMMdd for the string. Example: ".MetDate=20160409" will set the Met Date to April 9th, 2016.
7. A full up to date list is available by reading the source code (BatchEditor.cs, ProcessPKM method).

----------

Remember that certain formats/generations do not always have future properties. There are many applications of the Batch Editor including mass hatching, deleting, making everything shiny, or clearing EVs from all applicable Pokémon.

**Comment by NinFanBoyFTW** [comment]
Thanks. I still think that we should put at least all of the special commands in the about section of pkhex because then you wouldn't need a post to be able to use the batch editor. Thanks again

**Comment by Ninjistix** [comment]
quick question on the pkmn OT rename, would how would I be able to rename only pkm with a certain trainer name, like if i wanted to rename my trainer sav and all pkmn caught by my previous OT name.

Eg. my sav file says "Ninji" but I want to rename it to Elijah and rename just the pkmn caught by Ninji to Elijah

**Comment by kwsch** [comment]
the dropdowns in the batch editor help you build the instructions

require OT_Name = Ninji
set OT_Name = Elijah

results in:

```
=OT_Name=Ninji
.OT_Name=Elijah
```

**Comment by Ninjistix** [comment]
nice, thanks alot, will help also help me in converting some of my sav's to a diff version

**Comment by xXAquaNightXx** [comment]
I am test running this batch edit on my save file but when I set .CurrentHandler=0 it still remains my OT name. How do i clear Latest (not OT) Handler? to make pokemon mine?

.Country=49
.Region=36
.ConsoleRegion=1
.TID=12345
.SID=54321
.OT_Name=Ash
.OT_Gender=2
.CurrentHandler=0
.EncryptionConstant=$rand
.PID=$rand

![trainer info](https://cloud.githubusercontent.com/assets/24309423/20824491/b2e57be0-b833-11e6-85ff-4829811ceb22.png)

**Comment by matthewjdavis85** [comment]
Is there a file with the country, region and console region codes?

**Comment by xXAquaNightXx** [comment]
Sorry I don't have a file with the codes I used trail and error to figure out the ones I wanted.  But the range of numbers is how many items there are on each list. Just create a pokemon and run the editor with different numbers to narrow it down.

**Comment by kwsch** [comment]
[Pick a countryID](https://github.com/kwsch/PKHeX/blob/master/PKHeX/Resources/text/locale/countries.txt)
[Pick a SubRegion ID based off countryID](https://github.com/kwsch/PKHeX/tree/master/PKHeX/Resources/text/locale/sr_ID)

**Comment by xXAquaNightXx** [comment]
@kwsch thank you!

**Comment by luedgo** [comment]
hello! help me in change version game, X to Moon for example

**Comment by xXAquaNightXx** [comment]
![1](https://cloud.githubusercontent.com/assets/24309423/21034931/f94918fe-bd91-11e6-9d0c-6dc753b4c75a.png)

Sapphire: 1
Ruby: 2
Emerald: 3
FireRed: 4
LeafGreen: 5
Heart Gold: 7
Soul Silver: 8
Diamond: 10
Pearl: 11
Platinum: 12
Colosseum/XD: 15
White: 20
Black: 21
White 2: 22
Black 2: 23
X: 24
Y: 25
AS: 26
OR: 27
Sun: 30
Moon: 31

**Comment by luedgo** [comment]
xXAquaNightXx Thanks Very much!!

**Comment by luedgo** [comment]
.Egg_Location= <---Paniola Ranch value?
.Met_Location= <---pokepelago value?

Is there a document with the location values? 
Exist a code for set default move and relearn move?

Sorry for asking so many questions @xXAquaNightXx

**Comment by xXAquaNightXx** [comment]
You can download the zip from here and extract it, the files are located in PKHEX>Resources>text open them with something like Notepad++ and you'll see the values there

**Comment by mudkip83** [comment]
How do you edit the met section in batch editor? Im trying to set it to daycare center but it wont apply. Any ideas

**Comment by camus0314** [comment]
How do I add removable movements with the Batch Editor to 700 different Pokémon?
