### ISSUE TITLE
mass editor integration?

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#535]
Hi I wanted to know if you would consider working to possibly add the pkhex mass editor to pkhex
https://github.com/FullLifeGames/Mass-Editor

I know you already have the batch editor but it seems very complicated even for more advanced users like me and I suggested adding a command list in the about button on pkhex but I still think it would be amazing if you worked with the person managing this project to add this to pkhex. I feel that a lot of people would love this in addition to or instead of the batch editor just for the simple fact that it seems more intuitive with obvious buttons for things like making pokemon shiny. I know its a bit of a stretch but if you did work with the guy involved with this project (who's already trying to add 7th gen support) I think it could make the mass editor/batch editor much more user friendly and I think you should keep the batch editor in addition to this.

**Comment by NinFanBoyFTW** [comment]
also I know that you probably already know about this program but maybe for other people that are unfamiliar here's a screenshot, and maybe we can get some feedback on whether or not people would like this addition
![untitled-1](https://cloud.githubusercontent.com/assets/21354941/20741324/84390962-b697-11e6-8ef8-55c351ed330d.png)

**Comment by kwsch** [comment]
Both tools have their pros/cons:

Batch Editor
- Has Filters to only modify suitable PKM.
- Has no heavy interface allowing for multi-generation support.
- Separate from Main form, different interface means Main form bugs/updates do not impact batch editing.
- Executed script is copy/pasteable and shareable, allowing for others to reuse and improve.
- Numbers instead of strings (except for a few supported string types)
- All properties are searchable

Mass Editor
- No filtering
- Has heavy & rigid interface that is only set up for gen6/7 support.
- Redundant controls required for property differences (gen6 markings true/false, gen7 markings 0/1/2).
- Cannot save/share program state
- Completely visual/GUI based
- All properties are displayed

The Batch Editor was designed to be an easy to maintain bulk modifier that can support multiple generations without much clutter. Not many users end up touching it anyway.

Closing as this will not be incorporated -- the Batch Editor serves the same purpose and users are free to use both programs.
