### ISSUE TITLE
Lycanroc bug

### ISSUE THREAD

**Issue by Odaxis** [kwsch/PKHeX#540]
Bred Lycanroc with Sucker Punch and Fire Fang marked as illegal without having a "Latest (not OT) Handler" in place.
![p1](https://cloud.githubusercontent.com/assets/18354599/20770984/36a822a6-b722-11e6-82d6-300ec7df103a.PNG)
![p2](https://cloud.githubusercontent.com/assets/18354599/20770985/36aa117e-b722-11e6-94d1-e1dcb6a6e0f4.PNG)
![p3](https://cloud.githubusercontent.com/assets/18354599/20770983/36a5927a-b722-11e6-82b8-7311e7d10a89.PNG)

**Comment by kwsch** [comment]
Riddle me this:
How did you evolve the Rockruff -> Lycanroc-Day without trading it from Moon?

The legality checker does not unroll the evolution chain to Rockruff's species ID because the evolution is invalid. The checker's first thing it checks is relearn moves to help determine what encounter type it was.

I'll probably end up adding a new check for gen7 version specific evolutions not being traded away so that the error message gives a better hint as to what is really wrong.
