### ISSUE TITLE
Battle Box support in SM

### ISSUE THREAD

**Issue by NinFanBoyFTW** [kwsch/PKHeX#544]
Hey I wanted to know if there will be support for the battle boxes in the pc for sun and moon. Im sure your probably already aware but in the pc you can go to the battle box section and now there is 5 teams you can use instead of the previous one team. So I wanted to know if you were going to add support to add pokemon to the battle box teams to make it easier to set up teams

EDIT: It seems that when you "register" a pokemon to the battle box it stays in the pc with a battle box symbol on it so I guess if you were to add it would would have to be read only which I think it usually is. Thanks

**Comment by kwsch** [comment]
It's a bit much to do anything about. Basically the game stores which box/slot is used for a given team.

PKHeX allows set/delete in addition to box filling/deleting/cloning. 
How would PKHeX handle slots that are used by the Battle Box?
How would PKHeX handle slots that are overwritten by many of the 'cheat' operations listed above?
How would PKHeX handle moving/swapping a pkm between party/slot?

PKHeX isn't a box simulator, and obviously there are tons of what ifs. The easiest solution is to do nothing about it, because players can use their game to manage their battle box.

Plus, modifying battle box contents is NOT something I'd want to do, considering the possible abuse some nefarious users may try.

**Comment by ApacheThunder** [comment]
The "Team Boxes" that gen 7 uses don't store pokemon the same way as gen 6. There's 6 team boxes instead of 1 battle box and unlike the battle box they aren't used as additional storage in the PC. The Pokémon are "registered" to each slot in the team slot while the original mon remains in the normal 30 or so PC boxes. You can move those mons around in the PC and they remain registered in the team box. (unless you move them to your party in which case they become unregistered from any team boxes they are associated with)

Unlike gen 6, I think we can do without the ability to read them. Moving mons there doesn't make then inaccessible from PkHeX as they remain in their original box slot. So at the moment I don't see the rush to get this implemented anytime soon. :P

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/251dc9c46a68aa9251ab00d0d5db60c68dfef02e
