### ISSUE TITLE
Batch MarkIV does not work

### ISSUE THREAD

**Issue by matthewjdavis85** [kwsch/PKHeX#571]
I ran this:

.MarkCircle=True
.MarkDiamond=True
.MarkHeart=True
.MarkSquare=True
.MarkStar=True
.MarkTriangle=True

and it marked all Circle IVs fine. But nothing else was marked. I ran each of them individually and it did not work either. Using False works on Circle as well, but nothing else.

**Comment by kwsch** [comment]
You'd have to use MarkValue (it's a private property so it doesn't display in the drop down).
Since gen7 has a different marking format, setting the value directly is the only clean way of doing it.

Gen3
.MarkValue=15
Gen4-6
.MarkValue=63
Gen7+ (all blue)
.MarkValue=1365
Gen7+ (all pink)
.MarkValue=2730

For a mixed combination, convert the numbers to binary and compare the count of markings to the possible range.

**Comment by kwsch** [comment]
Actually to make it easier on everyone, just set the individual mark to 1 for gens 3-6

For gen7 you can set individual marks to 0/1/2 for none/blue/pink
