### ISSUE TITLE
Legal error

### ISSUE THREAD

**Issue by hogeunk** [kwsch/PKHeX#604]
1) Klinklang
http://i.imgur.com/rZ6o0Nw.png

2) Conkeldurr
http://i.imgur.com/EDAxA8z.png

3)
Snivy, Litwick -> Error mark, but legal when checking
Tepig -> Legal
http://i.imgur.com/UJfnicQ.png

4)
Poké Pelago -> Unknown encounter

**Comment by kwsch** [comment]
Can't really tell what the exact issue is without pkm files.

1. Data isn't matching up with an Island Scan entry
2. Requires a trade evolution (thus a Handling Trainer)
3. Recently fixed a bug with Handling Trainer gender, the info is fixed whenever PKHeX sets from tabs or checks the legality status.
4. Unsupported since nobody has documented the level ranges.

https://github.com/kwsch/PKHeX/blob/master/PKHeX/Legality/Tables7.cs#L197

**Comment by mcdrill89** [comment]
So would it help if we added this site doesn't support attaching .pkm files

**Comment by blahbax** [comment]
Just zip your pkm files and attach.

**Comment by Dandy562** [comment]
is giving a legal error with kingdra, it says is legal, but once i try to use him online, says something is wrong with the pokemon.

**Comment by mcdrill89** [comment]
Hope this helps
[PKMS.zip](https://github.com/kwsch/PKHeX/files/644926/PKMS.zip)

**Comment by kwsch** [comment]
@mcdrill89 all files you posted are legal on the latest commits; old versions of PKHeX would incorrectly set Handling Trainer Gender to 2 instead of 0 in the case of no Handling Trainer gender being present.

Same error as described and explained above.

**Comment by mcdrill89** [comment]
I just saw that but is there a way to fix the Greninja case or do I have to reload the Mystery Gift because it's still giving me an error

**Comment by kwsch** [comment]
@mcdrill89 are you using the latest commit as of 8 minutes ago?

**Comment by mcdrill89** [comment]
Let me do that

**Comment by Dandy562** [comment]
am having problems with serperior and Scolipede marks both of them legal, bu wont trade online, on my scolipede i have Adamant/Speed boost/lifeorb/protec-batonpass-bugbite-earthquake seems to be legal so am having problems finding what the problem is. same problem with seperior timid-contrary-hiddenPower-LeafStorm-GrassPlegde-FrenzyPlnat was able to use it before fine.

**Comment by rehv** [comment]
@Dandy562 are any of those abilities or moves only available after pokémon bank? That might be the issue. For example, Lurantis with Weather Ball is considered valid for PKHeX but you can only get Roserade after Bank.

**Comment by mcdrill89** [comment]
@Dandy I'm not sure about the moves but Hidden Abilities for Island Scan mons aren't available since they cannot SOS

**Comment by kwsch** [comment]
Closed, remaining poke pelago issue is duplicate with #590

**Comment by mcdrill89** [comment]
![conkelldurr](https://cloud.githubusercontent.com/assets/3318921/21596765/bf3639c8-d10d-11e6-914e-ff0d8b3d1e8c.png)

So should I just ignore this error since it was legally caught in game at the Poni Plains via Island Scan and shouldn't need to have a Handling trainer correct?
