### ISSUE TITLE
Fill Dex misses some pokemon

### ISSUE THREAD

**Issue by SubstituteCS** [kwsch/PKHeX#61]
Fill Dex sets Pokemon (such as Gallade) to obtained, but not seen, resulting in an inconsistent pokedex. (more obtained than seen.)

**Comment by kwsch** [comment]
Is this with a version you built yourself from source or one posted somewhere?

What version?

The latest commits changed how the Pokédex was displayed; there is no such thing as obtained/seen (only seen/displayed). The Fill Dex codes have not been updated yet, I'll probably do something about that now.

**Comment by SubstituteCS** [comment]
Latest source (@20 hours ago) built on VS 2013 Ultimate.

**Comment by kwsch** [comment]
Rewrote the 'Fill Dex' method in the following commit: https://github.com/kwsch/PKHeX/commit/6431ef1f68b16d38dfa6bfb6539ba454447ba91d

Should behave properly now. We still don't know how many form bits are used per game, but it doesn't really hurt to have everything flagged.

**Comment by SubstituteCS** [comment]
Thanks, I'll test it today.
I have a question, would it be OK if I hosted pre-compiled versions of PKHeX on my server?

**Comment by kwsch** [comment]
Due to my laziness I don't branch to have a separate running-beta with new features. Only when things get stable with new features/fixes do I post a new release @ ProjectPokemon.

I have no problem with rehosting a current compile as long as it's small scale and not advertised in place of the stable version. Previously some youtubers rehosted instead of pointing to the main thread, leading to people using out of date versions (with bugs or lacking new features). It also lessens traffic to PP, gotta keep that ad traffic ;)

I do intend to post a new release this weekend; I'm pretty satisfied with the current state and the Database&Search tool.

**Comment by SubstituteCS** [comment]
Alright, I was going to do something like this
http://chromium.woolyss.com/

**Comment by SubstituteCS** [comment]
Basic version is now up.
http://pkhex.rileystrickland.com/

**Comment by SubstituteCS** [comment]
Added linkbacks and disclaimer

**Comment by kwsch** [comment]
I approve ;)
