### ISSUE TITLE
How to make Totem Pokemon?

### ISSUE THREAD

**Issue by Mephes** [kwsch/PKHeX#668]
I've been trying to find a way to make Totem Pokemon for a while, and I haven't found out how. How can I make Totem Pokemon, or can I even make them at all?

**Comment by sora10pls** [comment]
Use PKHaX, change Form number accordingly.

So for example, if you want Totem Lurantis, make it Form 1.
Form 0 = Normal
Form 1 = Totem

Special cases are:

Raticate
- Form 0 = Normal
- Form 1 = Alola
- Form 2 = Totem

Mimikyu
- Form 0 = Normal
- Form 1 = Busted
- Form 2 = Totem
- Form 3 = Totem (Busted)

Probably a few others too but you get my point.

**Comment by Mephes** [comment]
That's a bit of what I'm looking for, but is there any way to give them the totem aura? The solution you gave only makes them slightly bigger.

**Comment by sora10pls** [comment]
That's not possible with PKHeX, as it's related to the ROM data rather than the save data.

The only reason they have aura during battles with them is due to how the game (I would assume) scripts that encounter; it makes sense since in a recent randomizer I did, whatever the Totem Pokemon got randomized into had that same aura. The only difference between the Forms is, as you said, their sizes.

**Comment by Mephes** [comment]
Ah, so that's why I've never found a way to give them the totem aura. Well, the size increase is good enough, I suppose.
