### ISSUE TITLE
QR Code injection is capable of overwriting Battle (locked) Pokemon

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#680]
As the title says.

@SciresM

**Comment by kwsch** [comment]
Since the QRs can be generated and injected to another save file, this isn't so much a PKHeX issue but instead a 'should the QR custom code allow it if the battle box is locked?' I'm not sure how much space is left in the QR injection routine, but maybe if it checked the 6 bool flags in the save file and reject the operation if a battle box is currently locked.

`Savedata::BOX::IsTeamLock(int blockPtr, int teamNumber)` is the relevant method, just check teams 0-5 and abort the QR operation if any is locked.
