### ISSUE TITLE
Batch editor help

### ISSUE THREAD

**Issue by mudkip83** [kwsch/PKHeX#704]
Im new to pkhex and batch editor. I managed to find most of my questions on my own by just playing around it with it. Im trying to edit some others but can't figure it out. Perhaps anyone can help?

1. I need help changing met location to daycare. What value do i need to enter for that to show.

2. How do it edit them all to shiny status?

3. Finally how do it mass edit the ones who have mega forms and want to make the mega forms permanent?

if anyone has any of this info please help? even if you dont know all of it i just cant figure the 1st one

**Comment by kwsch** [comment]
1. I've added [current value indication](https://github.com/kwsch/PKHeX/commit/1fcdffc65450317011802cfe400c64082dd5e927); just load the appropriate properties to the main tabs before opening the Batch Editor if you want hints on what values to enter.
2. `.PID=$shiny`
3. Mega forms can only be 'saved' if they are boxed. Upon loading the game, Mega Forms in the party are reverted.

**Comment by mudkip83** [comment]
is all this on a updated pkhex or is it just updated in this article?

**Comment by kwsch** [comment]
The posted download on the forums is the latest stable version, which is captured on the date listed in the changelog.

The recent change I just added is NOT in the forum downloads section, because new features/etc need to be tested & solidified so that less bugs are present in the actual release. You can always recompile from source, download it from the CI server (go to the Commits tab, click on the green checkmark for a given commit and go to the artifacts tab of whatever OS-specific version you want), or wait until a stable version is posted.
