### ISSUE TITLE
With Pre-bank check gone it says Legal to the dates before release.

### ISSUE THREAD

**Issue by DracoMilesX** [kwsch/PKHeX#779]
With the Pre-bank legal check gone it now says gives the Pokemon genned with a date before the bank release as legal.

Would it be possible to get the Pre-bank check back with an added part for Met Date/Egg Met Conditions Date if before bank release it's illegal?

Might just be the Egg conditions dunno how it behaves if a you transfer a Pokemon caught in earlier games if it updates the Met Date then?

**Comment by gocario** [comment]
The date depends on the 3DS', you can change it to whatever you want. You can't rely on such information for legality.

**Comment by Dionicio3** [comment]
It would be nice if it said "Fishy: Pokemon met date before bank release", especially with all the recent bans.

**Comment by apassiou** [comment]
Whats fishy about it? The date is set by your 3DS when receiving from bank. You can set the date to 2010, and get pokemon from bank and his met date will be set to 2010.

**Comment by sora10pls** [comment]
If this were taken into consideration, we'd have to add date checks for EVERY species, and EVERY event.

- Event Pokemon couldn't have met dates other than when they were being distributed (this could very well vary between regions).
- Gen 7 Pokemon couldn't be obtained prior to November 18th (23rd for EUR).

The checks are unnecessary because of the 3DS Date/Time being changeable at any given time.

**Comment by Dionicio3** [comment]
@apassiou I doubt Nintendo expects people to have their dates set far into the past. Plus, it would still be "legal". The message could be there just to warn people to be careful.

**Comment by kwsch** [comment]
GameFreak don't check dates, neither should users have to worry about it.
