### ISSUE TITLE
FEATURE REQUEST: BALL ILLEGAL NOTIFIER

### ISSUE THREAD

**Issue by matthewjdavis85** [kwsch/PKHeX#843]
Similar to how there is a Red ! next to invalid moves, it would be great to have this next to other areas as well.

One area where I think it would be particularly useful is next to "Ball"

Other possible locations could be next to Level if invalid, or next to ability if invalid (such as with certain Hidden Abilities)

In addition, it would be great if you could click those errors, and have it apply suggested fixes. For example with Ball, you could have it apply a Pokeball. With Ability, any known ability. With Level, the lowest working level etc.

**Comment by kwsch** [comment]
Indication next to the text labels is not compatible with the GUI setup due to labels being fixed width to accommodate every language.

The overall legality can be re-checked whenever the indicator to the left of the preview sprite is clicked. Moves are critical to determining a Pokémon's origin, hence why they are flagged individually. If the overall indication says the ability is not valid, it's a simple change the user can do. Same for ball. 

There's already a met+level suggestion by clicking the Met Location label; encounter conditions and moves are really the only things that are complex enough to warrant a fix-button -- everything else can be changed by the user.
