### ISSUE TITLE
Changing Pokemon Language does not update Nickname

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#849]
PKHeX used to do this, but upon changing a Pokemon's Language, it no longer automatically updates the nickname to match the species name in whatever Language it's been set to.

Before changing:
![image](https://cloud.githubusercontent.com/assets/17801814/22864546/856da170-f121-11e6-8b64-38c0adce06d2.png)

After changing:
![image](https://cloud.githubusercontent.com/assets/17801814/22864550/993fd27c-f121-11e6-8c09-fb6828a19a54.png)

**Comment by kwsch** [comment]
Had to tweak behavior to prevent the nickname from updating if nickname unchecked & the name matches another language.

Should be committing something shortly so that users can freeze the nickname with the checkbox and uncheck after changing to the desired language, else it'll behave like prior versions.
