### ISSUE TITLE
Festival Plaza Text Display Errors

### ISSUE THREAD

**Issue by mjd85** [kwsch/PKHeX#854]
![stival plaza](https://cloud.githubusercontent.com/assets/2186585/22899475/f59b1af4-f1f8-11e6-8836-f5408cd024e0.jpg)

Screenshot attached. Anywhere it is supposed to say "Festival Plaza" it simply says "stival Plaza"

I looked through previous issues and nothing seemed to mention it. Any idea what the problem is or how to fix it?

**Comment by kwsch** [comment]
Initial S/M versions of PKHeX had an incorrect offset (off by 2 bytes), causing it to overwrite the Festival Plaza name.

"Fe" was overwritten. Try opening the "main" file in HxD and find "estival Plaza" as a Text string with Unicode checked. Should be somewhere near 0x50D08; just manually edit it to have whatever string you want.

**Comment by matthewjdavis85** [comment]
I'm not an expert in this, so I apologize.

I found the string, but have not been able to successfully fix the error without changing the file size and corrupting the save

Here is the overwritten version.
00050CF0: 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00050D00: 00 00 00 00 00 00 00 00 7F 96 98 00 7F 96 98 00
00050D10: 7F 96 98 00 73 00 74 00 69 00 76 00 61 00 6C 00
00050D20: 20 00 50 00 6C 00 61 00 7A 00 61 00 00 00 00 00
00050D30: 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00
00050D40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00


.........................–˜..–˜..–˜.s.t.i.v.a.l. .P.l.a.z.a.....................................            -is what the lines appear as.

What would be a good thing to change it to in order to fix the issue without corrupting the saves?

**Comment by kwsch** [comment]
>00050D10: 7F 96 98 00

replace the 4 bytes with:

>46 00 65 00

then load the save in PKHeX and re-export

Alternatively, if someone tells me the max length the plaza can be named, I can add a plaza name editing textbox. I suspect it's 20 characters...

**Comment by matthewjdavis85** [comment]
Could be I was doing something wrong last night, but the edit you displayed opens fine with Pkhex, but still corrupts the save when I apply it via JKSM.

Could be I was doing something wrong. I'll try again when I am home from work and see if I can't get it figured out.

**Comment by Mrtops** [comment]
@kwsch You are correct I just checked and the max number of characters (including spaces) is 20

**Comment by Mrtops** [comment]
@mjd85 Did you check to make sure that JKSM was injecting the right save file is it possible that you did not replace the old save with the new save when you exported?

**Comment by kwsch** [comment]
Double check that the imported folder contains only the "main" file, not a "main.bak"; certain programs love to save unprompted backup files. JKSM should only be importing "main".

**Comment by mjd85** [comment]
Yeah I deleted the main.bak out of there, and ensured it was using only the newer file. If it was using the old file, it would've worked fine still with it saying "stival Plaza"
