### ISSUE TITLE
Save file load bug(s)

### ISSUE THREAD

**Issue by sora10pls** [kwsch/PKHeX#855]
What I did to have these bugs occur:

Open PKHeX -> Blank Sun save file is loaded -> Import a Pokemon Blue VC save file -> Once loaded, immediately import a Pokemon Moon save file

Upon doing so, the top of the window no longer shows the version, save version (i.e. "SAV7"), file name, and game version (this can be seen in the below screenshot).

In addition to that, checking legality for Pokemon results in the following:
![image](https://cloud.githubusercontent.com/assets/17801814/22902083/d2c4a3ca-f201-11e6-90b1-e0218b64ff8e.png)

Loading another save file fixes this issue.

**Comment by Mrtops** [comment]
Wow! Ok that is weird

**Comment by kwsch** [comment]
First bug: translating form on generational change, need to keep window title from resetting back to PKHeX.
Second bug: The GameOrigin combobox wasn't accepting any updates until it was redrawn due to it being hidden for Gens 1/2. A little bit of UI hackwork triggers it to show temporarily before loading the template data.
