### ISSUE TITLE
Disorted pokemon images in latest commits

### ISSUE THREAD

**Issue by PrometheusG** [kwsch/PKHeX#857]
Hi,

In gen 6 and 7 games which I have tested, some pokemon have their image disorted,more like zoomed in.Below are the images showing that:

In the Gen 6 AS main.sav file,this happens to some .pk5(shiny metagross-event from white) and .pk6 files(the rest 3 shinies). The other 4 above them are the same pokemon without being shiny(I have generated them just to show you the difference),the image is normal on them. When I change them again to shiny they gain the disorted image again:
![2017-02-14](https://cloud.githubusercontent.com/assets/20145301/22930918/37f2d96e-f2cb-11e6-93c2-7eef60bf660c.png)

In Gen 7 now the imported sableye, which is from my AS save and transfered to Moon via Pokemon Bank, the image is disorted without being shiny and changing the shiny mark doesn't affect it, it retains the same image:
![2017-02-14 1](https://cloud.githubusercontent.com/assets/20145301/22931019/b41b3da6-f2cb-11e6-943c-b65cf7300f10.png)

The .pk7 sableye that I have in my box looks normal without it's shiny form unlike the .pk6 imported from my AS.Changing it though from shiny to non shiny the image gets disorted again:
![2017-02-14 2](https://cloud.githubusercontent.com/assets/20145301/22931157/3f249884-f2cc-11e6-8103-46f39c958d94.png)
![2017-02-14 3](https://cloud.githubusercontent.com/assets/20145301/22931201/6432191c-f2cc-11e6-96d9-7177298374e9.png)

This bug only occurs in the latest commits not the stable version (2017.02.07)
Thank you

**Comment by kwsch** [comment]
@sora10pls https://github.com/kwsch/PKHeX/pull/851

**Comment by sora10pls** [comment]
Probably has to do with how the sprites are aligned in the images I pushed; I had them centered exactly in the middle through Photoshop, didn't expect to see this happen :P 

I'd assume it's an easy fix, let me see if I can work something out.

**Comment by sora10pls** [comment]
Update on that... it seems that I've gotten every single sprite working now, barring Steelix. I've tried basically every single possible alignment I could do, pixel by pixel, and they all end up distorting the sprite regardless.

I could only imagine it's because the Steelix sprite that was added in OR/AS is significantly larger in comparison to that of X/Y.

X/Y:
![208 1](https://cloud.githubusercontent.com/assets/17801814/22940975/bb1a5d4a-f2b1-11e6-840c-c34230ad5e11.png)
OR/AS:
![208](https://cloud.githubusercontent.com/assets/17801814/22940972/b8b70904-f2b1-11e6-89c9-73cdcb9a0e45.png)

Screenshots:
![image](https://cloud.githubusercontent.com/assets/17801814/22940894/70ecbbd2-f2b1-11e6-8834-ed7b469d7735.png)
![image](https://cloud.githubusercontent.com/assets/17801814/22940918/83e66f26-f2b1-11e6-8fac-a83ee098fb59.png)
![image](https://cloud.githubusercontent.com/assets/17801814/22940933/93695a1c-f2b1-11e6-88d8-3d1fec5b8168.png)

If anything else, we can always go back to the original Steelix sprite and I'll submit a pull request with all the fixes. Your call @kwsch :)

**Comment by sora10pls** [comment]
Submitted a pull request regardless that fixes the issue: #858
