### ISSUE TITLE
Can't find the SaveDataBackup folder

### ISSUE THREAD

**Issue by greenDarkness** [kwsch/PKHeX#861]
I was checking to see if my save was being  backed up to the usual "bak" folder, when I didn't receive a prompted asking if PKHeX should back up my save upon launch. I've looked through the options and I was unable to find a way to turn that feature back on. When I go to >Tools>Other>Open SaveDataBackup it alerts me that it can't find the folder. Did the name for the backup folder change?

Thanks for reading.

**Comment by kwsch** [comment]
SaveDataBackup is for save_manager -- [the homebrew app stores its data on the 3DS's SD card in a "saveDataBackup" folder](https://www.reddit.com/r/3dshacks/comments/3j273o/save_manager/). This is not the same as PKHeX's bak folder.

PKHeX's backup folder is determined as follows:
`BackupPath => Path.Combine(WorkingDirectory, "bak");`
WorkingDirectory is determined as follows:
`WinFormsUtil.IsClickonceDeployed ? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "PKHeX") : Environment.CurrentDirectory;`

Since the program isn't ClickOnce deployed, it's in the current directory of the .exe.

**Comment by greenDarkness** [comment]
Thank you!
