### ISSUE TITLE
Give all gen 3 and lower

### ISSUE THREAD

**Issue by Mrtops** [kwsch/PKHeX#880]
Would it be possible to add a give a button to gen three and lower?

Also is it really necessary to include a font file with the program?

**Comment by ReignOfComputer** [comment]
... What?

And yes, the PGL font file is necessary for stuff like the Pokemon symbols. It's packaged during compilation anyway.

**Comment by kwsch** [comment]
If you're referring to the lack of [Give All] for gen3/2/1 in the Inventory editor, it's because the inventory cannot hold every item at the same time. Only in gen4+ did the capacity increase to accommodate every possible item.

For the reason listed above, it's impossible to give all, hence the lack of the option.
